package org.apache.nutch.parse.html.video.database.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.nutch.parse.html.video.database.model.AreaCategoryTbl;
import org.apache.nutch.parse.html.video.database.model.AreaCategoryTblExample;

public interface AreaCategoryTblMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_category_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int countByExample(AreaCategoryTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_category_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int deleteByExample(AreaCategoryTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_category_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int deleteByPrimaryKey(Short acId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_category_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int insert(AreaCategoryTbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_category_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int insertSelective(AreaCategoryTbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_category_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    List<AreaCategoryTbl> selectByExample(AreaCategoryTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_category_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    AreaCategoryTbl selectByPrimaryKey(Short acId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_category_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int updateByExampleSelective(@Param("record") AreaCategoryTbl record, @Param("example") AreaCategoryTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_category_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int updateByExample(@Param("record") AreaCategoryTbl record, @Param("example") AreaCategoryTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_category_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int updateByPrimaryKeySelective(AreaCategoryTbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_category_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int updateByPrimaryKey(AreaCategoryTbl record);
}