package org.apache.nutch.parse.html.video.database.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.nutch.parse.html.video.database.model.FirstlevelCategoryTbl;
import org.apache.nutch.parse.html.video.database.model.FirstlevelCategoryTblExample;

public interface FirstlevelCategoryTblMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firstlevel_category_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int countByExample(FirstlevelCategoryTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firstlevel_category_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int deleteByExample(FirstlevelCategoryTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firstlevel_category_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int deleteByPrimaryKey(Short fcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firstlevel_category_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int insert(FirstlevelCategoryTbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firstlevel_category_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int insertSelective(FirstlevelCategoryTbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firstlevel_category_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    List<FirstlevelCategoryTbl> selectByExample(FirstlevelCategoryTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firstlevel_category_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    FirstlevelCategoryTbl selectByPrimaryKey(Short fcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firstlevel_category_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int updateByExampleSelective(@Param("record") FirstlevelCategoryTbl record, @Param("example") FirstlevelCategoryTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firstlevel_category_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int updateByExample(@Param("record") FirstlevelCategoryTbl record, @Param("example") FirstlevelCategoryTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firstlevel_category_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int updateByPrimaryKeySelective(FirstlevelCategoryTbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firstlevel_category_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int updateByPrimaryKey(FirstlevelCategoryTbl record);
}