package org.apache.nutch.parse.html.video.database.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.nutch.parse.html.video.database.model.SecondlevelCategoryTbl;
import org.apache.nutch.parse.html.video.database.model.SecondlevelCategoryTblExample;

public interface SecondlevelCategoryTblMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secondlevel_category_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int countByExample(SecondlevelCategoryTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secondlevel_category_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int deleteByExample(SecondlevelCategoryTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secondlevel_category_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int deleteByPrimaryKey(Short scId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secondlevel_category_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int insert(SecondlevelCategoryTbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secondlevel_category_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int insertSelective(SecondlevelCategoryTbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secondlevel_category_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    List<SecondlevelCategoryTbl> selectByExample(SecondlevelCategoryTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secondlevel_category_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    SecondlevelCategoryTbl selectByPrimaryKey(Short scId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secondlevel_category_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int updateByExampleSelective(@Param("record") SecondlevelCategoryTbl record, @Param("example") SecondlevelCategoryTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secondlevel_category_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int updateByExample(@Param("record") SecondlevelCategoryTbl record, @Param("example") SecondlevelCategoryTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secondlevel_category_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int updateByPrimaryKeySelective(SecondlevelCategoryTbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secondlevel_category_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int updateByPrimaryKey(SecondlevelCategoryTbl record);
}