package org.apache.nutch.parse.html.video.database.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.nutch.parse.html.video.database.model.VideoBaseinfoTbl;
import org.apache.nutch.parse.html.video.database.model.VideoBaseinfoTblExample;

public interface VideoBaseinfoTblMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_baseinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int countByExample(VideoBaseinfoTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_baseinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int deleteByExample(VideoBaseinfoTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_baseinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int deleteByPrimaryKey(Integer vbId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_baseinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int insert(VideoBaseinfoTbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_baseinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int insertSelective(VideoBaseinfoTbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_baseinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    List<VideoBaseinfoTbl> selectByExample(VideoBaseinfoTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_baseinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    VideoBaseinfoTbl selectByPrimaryKey(Integer vbId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_baseinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int updateByExampleSelective(@Param("record") VideoBaseinfoTbl record, @Param("example") VideoBaseinfoTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_baseinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int updateByExample(@Param("record") VideoBaseinfoTbl record, @Param("example") VideoBaseinfoTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_baseinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int updateByPrimaryKeySelective(VideoBaseinfoTbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_baseinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int updateByPrimaryKey(VideoBaseinfoTbl record);
}