package org.apache.nutch.parse.html.video.database.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.nutch.parse.html.video.database.model.VideoScRefTbl;
import org.apache.nutch.parse.html.video.database.model.VideoScRefTblExample;

public interface VideoScRefTblMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_sc_ref_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int countByExample(VideoScRefTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_sc_ref_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int deleteByExample(VideoScRefTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_sc_ref_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_sc_ref_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int insert(VideoScRefTbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_sc_ref_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int insertSelective(VideoScRefTbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_sc_ref_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    List<VideoScRefTbl> selectByExample(VideoScRefTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_sc_ref_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    VideoScRefTbl selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_sc_ref_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int updateByExampleSelective(@Param("record") VideoScRefTbl record, @Param("example") VideoScRefTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_sc_ref_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int updateByExample(@Param("record") VideoScRefTbl record, @Param("example") VideoScRefTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_sc_ref_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int updateByPrimaryKeySelective(VideoScRefTbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_sc_ref_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int updateByPrimaryKey(VideoScRefTbl record);
}