package org.apache.nutch.parse.html.video.database.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.nutch.parse.html.video.database.model.VideoSourceinfoTbl;
import org.apache.nutch.parse.html.video.database.model.VideoSourceinfoTblExample;

public interface VideoSourceinfoTblMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_sourceinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int countByExample(VideoSourceinfoTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_sourceinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int deleteByExample(VideoSourceinfoTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_sourceinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_sourceinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int insert(VideoSourceinfoTbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_sourceinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int insertSelective(VideoSourceinfoTbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_sourceinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    List<VideoSourceinfoTbl> selectByExample(VideoSourceinfoTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_sourceinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    VideoSourceinfoTbl selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_sourceinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int updateByExampleSelective(@Param("record") VideoSourceinfoTbl record, @Param("example") VideoSourceinfoTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_sourceinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int updateByExample(@Param("record") VideoSourceinfoTbl record, @Param("example") VideoSourceinfoTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_sourceinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int updateByPrimaryKeySelective(VideoSourceinfoTbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_sourceinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int updateByPrimaryKey(VideoSourceinfoTbl record);
}