package org.apache.nutch.parse.html.video.database.model;

public class AreaCategoryTbl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_category_tbl.ac_id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private Short acId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_category_tbl.ac_name
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private String acName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_category_tbl.relate_acid
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private Short relateAcid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_category_tbl.is_pub
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private Boolean isPub;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_category_tbl.ac_id
     *
     * @return the value of area_category_tbl.ac_id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Short getAcId() {
        return acId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_category_tbl.ac_id
     *
     * @param acId the value for area_category_tbl.ac_id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setAcId(Short acId) {
        this.acId = acId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_category_tbl.ac_name
     *
     * @return the value of area_category_tbl.ac_name
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getAcName() {
        return acName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_category_tbl.ac_name
     *
     * @param acName the value for area_category_tbl.ac_name
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setAcName(String acName) {
        this.acName = acName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_category_tbl.relate_acid
     *
     * @return the value of area_category_tbl.relate_acid
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Short getRelateAcid() {
        return relateAcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_category_tbl.relate_acid
     *
     * @param relateAcid the value for area_category_tbl.relate_acid
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setRelateAcid(Short relateAcid) {
        this.relateAcid = relateAcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_category_tbl.is_pub
     *
     * @return the value of area_category_tbl.is_pub
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Boolean getIsPub() {
        return isPub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_category_tbl.is_pub
     *
     * @param isPub the value for area_category_tbl.is_pub
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setIsPub(Boolean isPub) {
        this.isPub = isPub;
    }
}