package org.apache.nutch.parse.html.video.database.model;

public class SecondlevelCategoryTbl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column secondlevel_category_tbl.sc_id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private Short scId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column secondlevel_category_tbl.sc_name
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private String scName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column secondlevel_category_tbl.fc_id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private Short fcId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column secondlevel_category_tbl.relate_scid
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private Short relateScid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column secondlevel_category_tbl.is_pub
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private Boolean isPub;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column secondlevel_category_tbl.sc_id
     *
     * @return the value of secondlevel_category_tbl.sc_id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Short getScId() {
        return scId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secondlevel_category_tbl.sc_id
     *
     * @param scId the value for secondlevel_category_tbl.sc_id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setScId(Short scId) {
        this.scId = scId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column secondlevel_category_tbl.sc_name
     *
     * @return the value of secondlevel_category_tbl.sc_name
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getScName() {
        return scName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secondlevel_category_tbl.sc_name
     *
     * @param scName the value for secondlevel_category_tbl.sc_name
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setScName(String scName) {
        this.scName = scName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column secondlevel_category_tbl.fc_id
     *
     * @return the value of secondlevel_category_tbl.fc_id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Short getFcId() {
        return fcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secondlevel_category_tbl.fc_id
     *
     * @param fcId the value for secondlevel_category_tbl.fc_id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setFcId(Short fcId) {
        this.fcId = fcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column secondlevel_category_tbl.relate_scid
     *
     * @return the value of secondlevel_category_tbl.relate_scid
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Short getRelateScid() {
        return relateScid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secondlevel_category_tbl.relate_scid
     *
     * @param relateScid the value for secondlevel_category_tbl.relate_scid
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setRelateScid(Short relateScid) {
        this.relateScid = relateScid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column secondlevel_category_tbl.is_pub
     *
     * @return the value of secondlevel_category_tbl.is_pub
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Boolean getIsPub() {
        return isPub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secondlevel_category_tbl.is_pub
     *
     * @param isPub the value for secondlevel_category_tbl.is_pub
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setIsPub(Boolean isPub) {
        this.isPub = isPub;
    }
}