package org.apache.nutch.parse.html.video.database.model;

import java.util.ArrayList;
import java.util.List;

public class VideoSourceinfoTblExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table video_sourceinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table video_sourceinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table video_sourceinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_sourceinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public VideoSourceinfoTblExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_sourceinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_sourceinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_sourceinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_sourceinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_sourceinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_sourceinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_sourceinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_sourceinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_sourceinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_sourceinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table video_sourceinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andVsSubvidIsNull() {
            addCriterion("vs_subvid is null");
            return (Criteria) this;
        }

        public Criteria andVsSubvidIsNotNull() {
            addCriterion("vs_subvid is not null");
            return (Criteria) this;
        }

        public Criteria andVsSubvidEqualTo(String value) {
            addCriterion("vs_subvid =", value, "vsSubvid");
            return (Criteria) this;
        }

        public Criteria andVsSubvidNotEqualTo(String value) {
            addCriterion("vs_subvid <>", value, "vsSubvid");
            return (Criteria) this;
        }

        public Criteria andVsSubvidGreaterThan(String value) {
            addCriterion("vs_subvid >", value, "vsSubvid");
            return (Criteria) this;
        }

        public Criteria andVsSubvidGreaterThanOrEqualTo(String value) {
            addCriterion("vs_subvid >=", value, "vsSubvid");
            return (Criteria) this;
        }

        public Criteria andVsSubvidLessThan(String value) {
            addCriterion("vs_subvid <", value, "vsSubvid");
            return (Criteria) this;
        }

        public Criteria andVsSubvidLessThanOrEqualTo(String value) {
            addCriterion("vs_subvid <=", value, "vsSubvid");
            return (Criteria) this;
        }

        public Criteria andVsSubvidLike(String value) {
            addCriterion("vs_subvid like", value, "vsSubvid");
            return (Criteria) this;
        }

        public Criteria andVsSubvidNotLike(String value) {
            addCriterion("vs_subvid not like", value, "vsSubvid");
            return (Criteria) this;
        }

        public Criteria andVsSubvidIn(List<String> values) {
            addCriterion("vs_subvid in", values, "vsSubvid");
            return (Criteria) this;
        }

        public Criteria andVsSubvidNotIn(List<String> values) {
            addCriterion("vs_subvid not in", values, "vsSubvid");
            return (Criteria) this;
        }

        public Criteria andVsSubvidBetween(String value1, String value2) {
            addCriterion("vs_subvid between", value1, value2, "vsSubvid");
            return (Criteria) this;
        }

        public Criteria andVsSubvidNotBetween(String value1, String value2) {
            addCriterion("vs_subvid not between", value1, value2, "vsSubvid");
            return (Criteria) this;
        }

        public Criteria andVsSetnumberIsNull() {
            addCriterion("vs_setnumber is null");
            return (Criteria) this;
        }

        public Criteria andVsSetnumberIsNotNull() {
            addCriterion("vs_setnumber is not null");
            return (Criteria) this;
        }

        public Criteria andVsSetnumberEqualTo(String value) {
            addCriterion("vs_setnumber =", value, "vsSetnumber");
            return (Criteria) this;
        }

        public Criteria andVsSetnumberNotEqualTo(String value) {
            addCriterion("vs_setnumber <>", value, "vsSetnumber");
            return (Criteria) this;
        }

        public Criteria andVsSetnumberGreaterThan(String value) {
            addCriterion("vs_setnumber >", value, "vsSetnumber");
            return (Criteria) this;
        }

        public Criteria andVsSetnumberGreaterThanOrEqualTo(String value) {
            addCriterion("vs_setnumber >=", value, "vsSetnumber");
            return (Criteria) this;
        }

        public Criteria andVsSetnumberLessThan(String value) {
            addCriterion("vs_setnumber <", value, "vsSetnumber");
            return (Criteria) this;
        }

        public Criteria andVsSetnumberLessThanOrEqualTo(String value) {
            addCriterion("vs_setnumber <=", value, "vsSetnumber");
            return (Criteria) this;
        }

        public Criteria andVsSetnumberLike(String value) {
            addCriterion("vs_setnumber like", value, "vsSetnumber");
            return (Criteria) this;
        }

        public Criteria andVsSetnumberNotLike(String value) {
            addCriterion("vs_setnumber not like", value, "vsSetnumber");
            return (Criteria) this;
        }

        public Criteria andVsSetnumberIn(List<String> values) {
            addCriterion("vs_setnumber in", values, "vsSetnumber");
            return (Criteria) this;
        }

        public Criteria andVsSetnumberNotIn(List<String> values) {
            addCriterion("vs_setnumber not in", values, "vsSetnumber");
            return (Criteria) this;
        }

        public Criteria andVsSetnumberBetween(String value1, String value2) {
            addCriterion("vs_setnumber between", value1, value2, "vsSetnumber");
            return (Criteria) this;
        }

        public Criteria andVsSetnumberNotBetween(String value1, String value2) {
            addCriterion("vs_setnumber not between", value1, value2, "vsSetnumber");
            return (Criteria) this;
        }

        public Criteria andVsSourceurlIsNull() {
            addCriterion("vs_sourceurl is null");
            return (Criteria) this;
        }

        public Criteria andVsSourceurlIsNotNull() {
            addCriterion("vs_sourceurl is not null");
            return (Criteria) this;
        }

        public Criteria andVsSourceurlEqualTo(String value) {
            addCriterion("vs_sourceurl =", value, "vsSourceurl");
            return (Criteria) this;
        }

        public Criteria andVsSourceurlNotEqualTo(String value) {
            addCriterion("vs_sourceurl <>", value, "vsSourceurl");
            return (Criteria) this;
        }

        public Criteria andVsSourceurlGreaterThan(String value) {
            addCriterion("vs_sourceurl >", value, "vsSourceurl");
            return (Criteria) this;
        }

        public Criteria andVsSourceurlGreaterThanOrEqualTo(String value) {
            addCriterion("vs_sourceurl >=", value, "vsSourceurl");
            return (Criteria) this;
        }

        public Criteria andVsSourceurlLessThan(String value) {
            addCriterion("vs_sourceurl <", value, "vsSourceurl");
            return (Criteria) this;
        }

        public Criteria andVsSourceurlLessThanOrEqualTo(String value) {
            addCriterion("vs_sourceurl <=", value, "vsSourceurl");
            return (Criteria) this;
        }

        public Criteria andVsSourceurlLike(String value) {
            addCriterion("vs_sourceurl like", value, "vsSourceurl");
            return (Criteria) this;
        }

        public Criteria andVsSourceurlNotLike(String value) {
            addCriterion("vs_sourceurl not like", value, "vsSourceurl");
            return (Criteria) this;
        }

        public Criteria andVsSourceurlIn(List<String> values) {
            addCriterion("vs_sourceurl in", values, "vsSourceurl");
            return (Criteria) this;
        }

        public Criteria andVsSourceurlNotIn(List<String> values) {
            addCriterion("vs_sourceurl not in", values, "vsSourceurl");
            return (Criteria) this;
        }

        public Criteria andVsSourceurlBetween(String value1, String value2) {
            addCriterion("vs_sourceurl between", value1, value2, "vsSourceurl");
            return (Criteria) this;
        }

        public Criteria andVsSourceurlNotBetween(String value1, String value2) {
            addCriterion("vs_sourceurl not between", value1, value2, "vsSourceurl");
            return (Criteria) this;
        }

        public Criteria andVsUrlvalidIsNull() {
            addCriterion("vs_urlvalid is null");
            return (Criteria) this;
        }

        public Criteria andVsUrlvalidIsNotNull() {
            addCriterion("vs_urlvalid is not null");
            return (Criteria) this;
        }

        public Criteria andVsUrlvalidEqualTo(Boolean value) {
            addCriterion("vs_urlvalid =", value, "vsUrlvalid");
            return (Criteria) this;
        }

        public Criteria andVsUrlvalidNotEqualTo(Boolean value) {
            addCriterion("vs_urlvalid <>", value, "vsUrlvalid");
            return (Criteria) this;
        }

        public Criteria andVsUrlvalidGreaterThan(Boolean value) {
            addCriterion("vs_urlvalid >", value, "vsUrlvalid");
            return (Criteria) this;
        }

        public Criteria andVsUrlvalidGreaterThanOrEqualTo(Boolean value) {
            addCriterion("vs_urlvalid >=", value, "vsUrlvalid");
            return (Criteria) this;
        }

        public Criteria andVsUrlvalidLessThan(Boolean value) {
            addCriterion("vs_urlvalid <", value, "vsUrlvalid");
            return (Criteria) this;
        }

        public Criteria andVsUrlvalidLessThanOrEqualTo(Boolean value) {
            addCriterion("vs_urlvalid <=", value, "vsUrlvalid");
            return (Criteria) this;
        }

        public Criteria andVsUrlvalidIn(List<Boolean> values) {
            addCriterion("vs_urlvalid in", values, "vsUrlvalid");
            return (Criteria) this;
        }

        public Criteria andVsUrlvalidNotIn(List<Boolean> values) {
            addCriterion("vs_urlvalid not in", values, "vsUrlvalid");
            return (Criteria) this;
        }

        public Criteria andVsUrlvalidBetween(Boolean value1, Boolean value2) {
            addCriterion("vs_urlvalid between", value1, value2, "vsUrlvalid");
            return (Criteria) this;
        }

        public Criteria andVsUrlvalidNotBetween(Boolean value1, Boolean value2) {
            addCriterion("vs_urlvalid not between", value1, value2, "vsUrlvalid");
            return (Criteria) this;
        }

        public Criteria andVsSubdurationIsNull() {
            addCriterion("vs_subduration is null");
            return (Criteria) this;
        }

        public Criteria andVsSubdurationIsNotNull() {
            addCriterion("vs_subduration is not null");
            return (Criteria) this;
        }

        public Criteria andVsSubdurationEqualTo(String value) {
            addCriterion("vs_subduration =", value, "vsSubduration");
            return (Criteria) this;
        }

        public Criteria andVsSubdurationNotEqualTo(String value) {
            addCriterion("vs_subduration <>", value, "vsSubduration");
            return (Criteria) this;
        }

        public Criteria andVsSubdurationGreaterThan(String value) {
            addCriterion("vs_subduration >", value, "vsSubduration");
            return (Criteria) this;
        }

        public Criteria andVsSubdurationGreaterThanOrEqualTo(String value) {
            addCriterion("vs_subduration >=", value, "vsSubduration");
            return (Criteria) this;
        }

        public Criteria andVsSubdurationLessThan(String value) {
            addCriterion("vs_subduration <", value, "vsSubduration");
            return (Criteria) this;
        }

        public Criteria andVsSubdurationLessThanOrEqualTo(String value) {
            addCriterion("vs_subduration <=", value, "vsSubduration");
            return (Criteria) this;
        }

        public Criteria andVsSubdurationLike(String value) {
            addCriterion("vs_subduration like", value, "vsSubduration");
            return (Criteria) this;
        }

        public Criteria andVsSubdurationNotLike(String value) {
            addCriterion("vs_subduration not like", value, "vsSubduration");
            return (Criteria) this;
        }

        public Criteria andVsSubdurationIn(List<String> values) {
            addCriterion("vs_subduration in", values, "vsSubduration");
            return (Criteria) this;
        }

        public Criteria andVsSubdurationNotIn(List<String> values) {
            addCriterion("vs_subduration not in", values, "vsSubduration");
            return (Criteria) this;
        }

        public Criteria andVsSubdurationBetween(String value1, String value2) {
            addCriterion("vs_subduration between", value1, value2, "vsSubduration");
            return (Criteria) this;
        }

        public Criteria andVsSubdurationNotBetween(String value1, String value2) {
            addCriterion("vs_subduration not between", value1, value2, "vsSubduration");
            return (Criteria) this;
        }

        public Criteria andVsSubtitleIsNull() {
            addCriterion("vs_subtitle is null");
            return (Criteria) this;
        }

        public Criteria andVsSubtitleIsNotNull() {
            addCriterion("vs_subtitle is not null");
            return (Criteria) this;
        }

        public Criteria andVsSubtitleEqualTo(String value) {
            addCriterion("vs_subtitle =", value, "vsSubtitle");
            return (Criteria) this;
        }

        public Criteria andVsSubtitleNotEqualTo(String value) {
            addCriterion("vs_subtitle <>", value, "vsSubtitle");
            return (Criteria) this;
        }

        public Criteria andVsSubtitleGreaterThan(String value) {
            addCriterion("vs_subtitle >", value, "vsSubtitle");
            return (Criteria) this;
        }

        public Criteria andVsSubtitleGreaterThanOrEqualTo(String value) {
            addCriterion("vs_subtitle >=", value, "vsSubtitle");
            return (Criteria) this;
        }

        public Criteria andVsSubtitleLessThan(String value) {
            addCriterion("vs_subtitle <", value, "vsSubtitle");
            return (Criteria) this;
        }

        public Criteria andVsSubtitleLessThanOrEqualTo(String value) {
            addCriterion("vs_subtitle <=", value, "vsSubtitle");
            return (Criteria) this;
        }

        public Criteria andVsSubtitleLike(String value) {
            addCriterion("vs_subtitle like", value, "vsSubtitle");
            return (Criteria) this;
        }

        public Criteria andVsSubtitleNotLike(String value) {
            addCriterion("vs_subtitle not like", value, "vsSubtitle");
            return (Criteria) this;
        }

        public Criteria andVsSubtitleIn(List<String> values) {
            addCriterion("vs_subtitle in", values, "vsSubtitle");
            return (Criteria) this;
        }

        public Criteria andVsSubtitleNotIn(List<String> values) {
            addCriterion("vs_subtitle not in", values, "vsSubtitle");
            return (Criteria) this;
        }

        public Criteria andVsSubtitleBetween(String value1, String value2) {
            addCriterion("vs_subtitle between", value1, value2, "vsSubtitle");
            return (Criteria) this;
        }

        public Criteria andVsSubtitleNotBetween(String value1, String value2) {
            addCriterion("vs_subtitle not between", value1, value2, "vsSubtitle");
            return (Criteria) this;
        }

        public Criteria andVsSubdescIsNull() {
            addCriterion("vs_subdesc is null");
            return (Criteria) this;
        }

        public Criteria andVsSubdescIsNotNull() {
            addCriterion("vs_subdesc is not null");
            return (Criteria) this;
        }

        public Criteria andVsSubdescEqualTo(String value) {
            addCriterion("vs_subdesc =", value, "vsSubdesc");
            return (Criteria) this;
        }

        public Criteria andVsSubdescNotEqualTo(String value) {
            addCriterion("vs_subdesc <>", value, "vsSubdesc");
            return (Criteria) this;
        }

        public Criteria andVsSubdescGreaterThan(String value) {
            addCriterion("vs_subdesc >", value, "vsSubdesc");
            return (Criteria) this;
        }

        public Criteria andVsSubdescGreaterThanOrEqualTo(String value) {
            addCriterion("vs_subdesc >=", value, "vsSubdesc");
            return (Criteria) this;
        }

        public Criteria andVsSubdescLessThan(String value) {
            addCriterion("vs_subdesc <", value, "vsSubdesc");
            return (Criteria) this;
        }

        public Criteria andVsSubdescLessThanOrEqualTo(String value) {
            addCriterion("vs_subdesc <=", value, "vsSubdesc");
            return (Criteria) this;
        }

        public Criteria andVsSubdescLike(String value) {
            addCriterion("vs_subdesc like", value, "vsSubdesc");
            return (Criteria) this;
        }

        public Criteria andVsSubdescNotLike(String value) {
            addCriterion("vs_subdesc not like", value, "vsSubdesc");
            return (Criteria) this;
        }

        public Criteria andVsSubdescIn(List<String> values) {
            addCriterion("vs_subdesc in", values, "vsSubdesc");
            return (Criteria) this;
        }

        public Criteria andVsSubdescNotIn(List<String> values) {
            addCriterion("vs_subdesc not in", values, "vsSubdesc");
            return (Criteria) this;
        }

        public Criteria andVsSubdescBetween(String value1, String value2) {
            addCriterion("vs_subdesc between", value1, value2, "vsSubdesc");
            return (Criteria) this;
        }

        public Criteria andVsSubdescNotBetween(String value1, String value2) {
            addCriterion("vs_subdesc not between", value1, value2, "vsSubdesc");
            return (Criteria) this;
        }

        public Criteria andVsSubthumbIsNull() {
            addCriterion("vs_subthumb is null");
            return (Criteria) this;
        }

        public Criteria andVsSubthumbIsNotNull() {
            addCriterion("vs_subthumb is not null");
            return (Criteria) this;
        }

        public Criteria andVsSubthumbEqualTo(String value) {
            addCriterion("vs_subthumb =", value, "vsSubthumb");
            return (Criteria) this;
        }

        public Criteria andVsSubthumbNotEqualTo(String value) {
            addCriterion("vs_subthumb <>", value, "vsSubthumb");
            return (Criteria) this;
        }

        public Criteria andVsSubthumbGreaterThan(String value) {
            addCriterion("vs_subthumb >", value, "vsSubthumb");
            return (Criteria) this;
        }

        public Criteria andVsSubthumbGreaterThanOrEqualTo(String value) {
            addCriterion("vs_subthumb >=", value, "vsSubthumb");
            return (Criteria) this;
        }

        public Criteria andVsSubthumbLessThan(String value) {
            addCriterion("vs_subthumb <", value, "vsSubthumb");
            return (Criteria) this;
        }

        public Criteria andVsSubthumbLessThanOrEqualTo(String value) {
            addCriterion("vs_subthumb <=", value, "vsSubthumb");
            return (Criteria) this;
        }

        public Criteria andVsSubthumbLike(String value) {
            addCriterion("vs_subthumb like", value, "vsSubthumb");
            return (Criteria) this;
        }

        public Criteria andVsSubthumbNotLike(String value) {
            addCriterion("vs_subthumb not like", value, "vsSubthumb");
            return (Criteria) this;
        }

        public Criteria andVsSubthumbIn(List<String> values) {
            addCriterion("vs_subthumb in", values, "vsSubthumb");
            return (Criteria) this;
        }

        public Criteria andVsSubthumbNotIn(List<String> values) {
            addCriterion("vs_subthumb not in", values, "vsSubthumb");
            return (Criteria) this;
        }

        public Criteria andVsSubthumbBetween(String value1, String value2) {
            addCriterion("vs_subthumb between", value1, value2, "vsSubthumb");
            return (Criteria) this;
        }

        public Criteria andVsSubthumbNotBetween(String value1, String value2) {
            addCriterion("vs_subthumb not between", value1, value2, "vsSubthumb");
            return (Criteria) this;
        }

        public Criteria andVsHostIsNull() {
            addCriterion("vs_host is null");
            return (Criteria) this;
        }

        public Criteria andVsHostIsNotNull() {
            addCriterion("vs_host is not null");
            return (Criteria) this;
        }

        public Criteria andVsHostEqualTo(String value) {
            addCriterion("vs_host =", value, "vsHost");
            return (Criteria) this;
        }

        public Criteria andVsHostNotEqualTo(String value) {
            addCriterion("vs_host <>", value, "vsHost");
            return (Criteria) this;
        }

        public Criteria andVsHostGreaterThan(String value) {
            addCriterion("vs_host >", value, "vsHost");
            return (Criteria) this;
        }

        public Criteria andVsHostGreaterThanOrEqualTo(String value) {
            addCriterion("vs_host >=", value, "vsHost");
            return (Criteria) this;
        }

        public Criteria andVsHostLessThan(String value) {
            addCriterion("vs_host <", value, "vsHost");
            return (Criteria) this;
        }

        public Criteria andVsHostLessThanOrEqualTo(String value) {
            addCriterion("vs_host <=", value, "vsHost");
            return (Criteria) this;
        }

        public Criteria andVsHostLike(String value) {
            addCriterion("vs_host like", value, "vsHost");
            return (Criteria) this;
        }

        public Criteria andVsHostNotLike(String value) {
            addCriterion("vs_host not like", value, "vsHost");
            return (Criteria) this;
        }

        public Criteria andVsHostIn(List<String> values) {
            addCriterion("vs_host in", values, "vsHost");
            return (Criteria) this;
        }

        public Criteria andVsHostNotIn(List<String> values) {
            addCriterion("vs_host not in", values, "vsHost");
            return (Criteria) this;
        }

        public Criteria andVsHostBetween(String value1, String value2) {
            addCriterion("vs_host between", value1, value2, "vsHost");
            return (Criteria) this;
        }

        public Criteria andVsHostNotBetween(String value1, String value2) {
            addCriterion("vs_host not between", value1, value2, "vsHost");
            return (Criteria) this;
        }

        public Criteria andVsGuestIsNull() {
            addCriterion("vs_guest is null");
            return (Criteria) this;
        }

        public Criteria andVsGuestIsNotNull() {
            addCriterion("vs_guest is not null");
            return (Criteria) this;
        }

        public Criteria andVsGuestEqualTo(String value) {
            addCriterion("vs_guest =", value, "vsGuest");
            return (Criteria) this;
        }

        public Criteria andVsGuestNotEqualTo(String value) {
            addCriterion("vs_guest <>", value, "vsGuest");
            return (Criteria) this;
        }

        public Criteria andVsGuestGreaterThan(String value) {
            addCriterion("vs_guest >", value, "vsGuest");
            return (Criteria) this;
        }

        public Criteria andVsGuestGreaterThanOrEqualTo(String value) {
            addCriterion("vs_guest >=", value, "vsGuest");
            return (Criteria) this;
        }

        public Criteria andVsGuestLessThan(String value) {
            addCriterion("vs_guest <", value, "vsGuest");
            return (Criteria) this;
        }

        public Criteria andVsGuestLessThanOrEqualTo(String value) {
            addCriterion("vs_guest <=", value, "vsGuest");
            return (Criteria) this;
        }

        public Criteria andVsGuestLike(String value) {
            addCriterion("vs_guest like", value, "vsGuest");
            return (Criteria) this;
        }

        public Criteria andVsGuestNotLike(String value) {
            addCriterion("vs_guest not like", value, "vsGuest");
            return (Criteria) this;
        }

        public Criteria andVsGuestIn(List<String> values) {
            addCriterion("vs_guest in", values, "vsGuest");
            return (Criteria) this;
        }

        public Criteria andVsGuestNotIn(List<String> values) {
            addCriterion("vs_guest not in", values, "vsGuest");
            return (Criteria) this;
        }

        public Criteria andVsGuestBetween(String value1, String value2) {
            addCriterion("vs_guest between", value1, value2, "vsGuest");
            return (Criteria) this;
        }

        public Criteria andVsGuestNotBetween(String value1, String value2) {
            addCriterion("vs_guest not between", value1, value2, "vsGuest");
            return (Criteria) this;
        }

        public Criteria andCsIdIsNull() {
            addCriterion("cs_id is null");
            return (Criteria) this;
        }

        public Criteria andCsIdIsNotNull() {
            addCriterion("cs_id is not null");
            return (Criteria) this;
        }

        public Criteria andCsIdEqualTo(Short value) {
            addCriterion("cs_id =", value, "csId");
            return (Criteria) this;
        }

        public Criteria andCsIdNotEqualTo(Short value) {
            addCriterion("cs_id <>", value, "csId");
            return (Criteria) this;
        }

        public Criteria andCsIdGreaterThan(Short value) {
            addCriterion("cs_id >", value, "csId");
            return (Criteria) this;
        }

        public Criteria andCsIdGreaterThanOrEqualTo(Short value) {
            addCriterion("cs_id >=", value, "csId");
            return (Criteria) this;
        }

        public Criteria andCsIdLessThan(Short value) {
            addCriterion("cs_id <", value, "csId");
            return (Criteria) this;
        }

        public Criteria andCsIdLessThanOrEqualTo(Short value) {
            addCriterion("cs_id <=", value, "csId");
            return (Criteria) this;
        }

        public Criteria andCsIdIn(List<Short> values) {
            addCriterion("cs_id in", values, "csId");
            return (Criteria) this;
        }

        public Criteria andCsIdNotIn(List<Short> values) {
            addCriterion("cs_id not in", values, "csId");
            return (Criteria) this;
        }

        public Criteria andCsIdBetween(Short value1, Short value2) {
            addCriterion("cs_id between", value1, value2, "csId");
            return (Criteria) this;
        }

        public Criteria andCsIdNotBetween(Short value1, Short value2) {
            addCriterion("cs_id not between", value1, value2, "csId");
            return (Criteria) this;
        }

        public Criteria andVbIdIsNull() {
            addCriterion("vb_id is null");
            return (Criteria) this;
        }

        public Criteria andVbIdIsNotNull() {
            addCriterion("vb_id is not null");
            return (Criteria) this;
        }

        public Criteria andVbIdEqualTo(Integer value) {
            addCriterion("vb_id =", value, "vbId");
            return (Criteria) this;
        }

        public Criteria andVbIdNotEqualTo(Integer value) {
            addCriterion("vb_id <>", value, "vbId");
            return (Criteria) this;
        }

        public Criteria andVbIdGreaterThan(Integer value) {
            addCriterion("vb_id >", value, "vbId");
            return (Criteria) this;
        }

        public Criteria andVbIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("vb_id >=", value, "vbId");
            return (Criteria) this;
        }

        public Criteria andVbIdLessThan(Integer value) {
            addCriterion("vb_id <", value, "vbId");
            return (Criteria) this;
        }

        public Criteria andVbIdLessThanOrEqualTo(Integer value) {
            addCriterion("vb_id <=", value, "vbId");
            return (Criteria) this;
        }

        public Criteria andVbIdIn(List<Integer> values) {
            addCriterion("vb_id in", values, "vbId");
            return (Criteria) this;
        }

        public Criteria andVbIdNotIn(List<Integer> values) {
            addCriterion("vb_id not in", values, "vbId");
            return (Criteria) this;
        }

        public Criteria andVbIdBetween(Integer value1, Integer value2) {
            addCriterion("vb_id between", value1, value2, "vbId");
            return (Criteria) this;
        }

        public Criteria andVbIdNotBetween(Integer value1, Integer value2) {
            addCriterion("vb_id not between", value1, value2, "vbId");
            return (Criteria) this;
        }

        public Criteria andVsReserved0IsNull() {
            addCriterion("vs_reserved_0 is null");
            return (Criteria) this;
        }

        public Criteria andVsReserved0IsNotNull() {
            addCriterion("vs_reserved_0 is not null");
            return (Criteria) this;
        }

        public Criteria andVsReserved0EqualTo(String value) {
            addCriterion("vs_reserved_0 =", value, "vsReserved0");
            return (Criteria) this;
        }

        public Criteria andVsReserved0NotEqualTo(String value) {
            addCriterion("vs_reserved_0 <>", value, "vsReserved0");
            return (Criteria) this;
        }

        public Criteria andVsReserved0GreaterThan(String value) {
            addCriterion("vs_reserved_0 >", value, "vsReserved0");
            return (Criteria) this;
        }

        public Criteria andVsReserved0GreaterThanOrEqualTo(String value) {
            addCriterion("vs_reserved_0 >=", value, "vsReserved0");
            return (Criteria) this;
        }

        public Criteria andVsReserved0LessThan(String value) {
            addCriterion("vs_reserved_0 <", value, "vsReserved0");
            return (Criteria) this;
        }

        public Criteria andVsReserved0LessThanOrEqualTo(String value) {
            addCriterion("vs_reserved_0 <=", value, "vsReserved0");
            return (Criteria) this;
        }

        public Criteria andVsReserved0Like(String value) {
            addCriterion("vs_reserved_0 like", value, "vsReserved0");
            return (Criteria) this;
        }

        public Criteria andVsReserved0NotLike(String value) {
            addCriterion("vs_reserved_0 not like", value, "vsReserved0");
            return (Criteria) this;
        }

        public Criteria andVsReserved0In(List<String> values) {
            addCriterion("vs_reserved_0 in", values, "vsReserved0");
            return (Criteria) this;
        }

        public Criteria andVsReserved0NotIn(List<String> values) {
            addCriterion("vs_reserved_0 not in", values, "vsReserved0");
            return (Criteria) this;
        }

        public Criteria andVsReserved0Between(String value1, String value2) {
            addCriterion("vs_reserved_0 between", value1, value2, "vsReserved0");
            return (Criteria) this;
        }

        public Criteria andVsReserved0NotBetween(String value1, String value2) {
            addCriterion("vs_reserved_0 not between", value1, value2, "vsReserved0");
            return (Criteria) this;
        }

        public Criteria andVsReserved1IsNull() {
            addCriterion("vs_reserved_1 is null");
            return (Criteria) this;
        }

        public Criteria andVsReserved1IsNotNull() {
            addCriterion("vs_reserved_1 is not null");
            return (Criteria) this;
        }

        public Criteria andVsReserved1EqualTo(String value) {
            addCriterion("vs_reserved_1 =", value, "vsReserved1");
            return (Criteria) this;
        }

        public Criteria andVsReserved1NotEqualTo(String value) {
            addCriterion("vs_reserved_1 <>", value, "vsReserved1");
            return (Criteria) this;
        }

        public Criteria andVsReserved1GreaterThan(String value) {
            addCriterion("vs_reserved_1 >", value, "vsReserved1");
            return (Criteria) this;
        }

        public Criteria andVsReserved1GreaterThanOrEqualTo(String value) {
            addCriterion("vs_reserved_1 >=", value, "vsReserved1");
            return (Criteria) this;
        }

        public Criteria andVsReserved1LessThan(String value) {
            addCriterion("vs_reserved_1 <", value, "vsReserved1");
            return (Criteria) this;
        }

        public Criteria andVsReserved1LessThanOrEqualTo(String value) {
            addCriterion("vs_reserved_1 <=", value, "vsReserved1");
            return (Criteria) this;
        }

        public Criteria andVsReserved1Like(String value) {
            addCriterion("vs_reserved_1 like", value, "vsReserved1");
            return (Criteria) this;
        }

        public Criteria andVsReserved1NotLike(String value) {
            addCriterion("vs_reserved_1 not like", value, "vsReserved1");
            return (Criteria) this;
        }

        public Criteria andVsReserved1In(List<String> values) {
            addCriterion("vs_reserved_1 in", values, "vsReserved1");
            return (Criteria) this;
        }

        public Criteria andVsReserved1NotIn(List<String> values) {
            addCriterion("vs_reserved_1 not in", values, "vsReserved1");
            return (Criteria) this;
        }

        public Criteria andVsReserved1Between(String value1, String value2) {
            addCriterion("vs_reserved_1 between", value1, value2, "vsReserved1");
            return (Criteria) this;
        }

        public Criteria andVsReserved1NotBetween(String value1, String value2) {
            addCriterion("vs_reserved_1 not between", value1, value2, "vsReserved1");
            return (Criteria) this;
        }

        public Criteria andVsReserved2IsNull() {
            addCriterion("vs_reserved_2 is null");
            return (Criteria) this;
        }

        public Criteria andVsReserved2IsNotNull() {
            addCriterion("vs_reserved_2 is not null");
            return (Criteria) this;
        }

        public Criteria andVsReserved2EqualTo(String value) {
            addCriterion("vs_reserved_2 =", value, "vsReserved2");
            return (Criteria) this;
        }

        public Criteria andVsReserved2NotEqualTo(String value) {
            addCriterion("vs_reserved_2 <>", value, "vsReserved2");
            return (Criteria) this;
        }

        public Criteria andVsReserved2GreaterThan(String value) {
            addCriterion("vs_reserved_2 >", value, "vsReserved2");
            return (Criteria) this;
        }

        public Criteria andVsReserved2GreaterThanOrEqualTo(String value) {
            addCriterion("vs_reserved_2 >=", value, "vsReserved2");
            return (Criteria) this;
        }

        public Criteria andVsReserved2LessThan(String value) {
            addCriterion("vs_reserved_2 <", value, "vsReserved2");
            return (Criteria) this;
        }

        public Criteria andVsReserved2LessThanOrEqualTo(String value) {
            addCriterion("vs_reserved_2 <=", value, "vsReserved2");
            return (Criteria) this;
        }

        public Criteria andVsReserved2Like(String value) {
            addCriterion("vs_reserved_2 like", value, "vsReserved2");
            return (Criteria) this;
        }

        public Criteria andVsReserved2NotLike(String value) {
            addCriterion("vs_reserved_2 not like", value, "vsReserved2");
            return (Criteria) this;
        }

        public Criteria andVsReserved2In(List<String> values) {
            addCriterion("vs_reserved_2 in", values, "vsReserved2");
            return (Criteria) this;
        }

        public Criteria andVsReserved2NotIn(List<String> values) {
            addCriterion("vs_reserved_2 not in", values, "vsReserved2");
            return (Criteria) this;
        }

        public Criteria andVsReserved2Between(String value1, String value2) {
            addCriterion("vs_reserved_2 between", value1, value2, "vsReserved2");
            return (Criteria) this;
        }

        public Criteria andVsReserved2NotBetween(String value1, String value2) {
            addCriterion("vs_reserved_2 not between", value1, value2, "vsReserved2");
            return (Criteria) this;
        }

        public Criteria andVsReserved3IsNull() {
            addCriterion("vs_reserved_3 is null");
            return (Criteria) this;
        }

        public Criteria andVsReserved3IsNotNull() {
            addCriterion("vs_reserved_3 is not null");
            return (Criteria) this;
        }

        public Criteria andVsReserved3EqualTo(String value) {
            addCriterion("vs_reserved_3 =", value, "vsReserved3");
            return (Criteria) this;
        }

        public Criteria andVsReserved3NotEqualTo(String value) {
            addCriterion("vs_reserved_3 <>", value, "vsReserved3");
            return (Criteria) this;
        }

        public Criteria andVsReserved3GreaterThan(String value) {
            addCriterion("vs_reserved_3 >", value, "vsReserved3");
            return (Criteria) this;
        }

        public Criteria andVsReserved3GreaterThanOrEqualTo(String value) {
            addCriterion("vs_reserved_3 >=", value, "vsReserved3");
            return (Criteria) this;
        }

        public Criteria andVsReserved3LessThan(String value) {
            addCriterion("vs_reserved_3 <", value, "vsReserved3");
            return (Criteria) this;
        }

        public Criteria andVsReserved3LessThanOrEqualTo(String value) {
            addCriterion("vs_reserved_3 <=", value, "vsReserved3");
            return (Criteria) this;
        }

        public Criteria andVsReserved3Like(String value) {
            addCriterion("vs_reserved_3 like", value, "vsReserved3");
            return (Criteria) this;
        }

        public Criteria andVsReserved3NotLike(String value) {
            addCriterion("vs_reserved_3 not like", value, "vsReserved3");
            return (Criteria) this;
        }

        public Criteria andVsReserved3In(List<String> values) {
            addCriterion("vs_reserved_3 in", values, "vsReserved3");
            return (Criteria) this;
        }

        public Criteria andVsReserved3NotIn(List<String> values) {
            addCriterion("vs_reserved_3 not in", values, "vsReserved3");
            return (Criteria) this;
        }

        public Criteria andVsReserved3Between(String value1, String value2) {
            addCriterion("vs_reserved_3 between", value1, value2, "vsReserved3");
            return (Criteria) this;
        }

        public Criteria andVsReserved3NotBetween(String value1, String value2) {
            addCriterion("vs_reserved_3 not between", value1, value2, "vsReserved3");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table video_sourceinfo_tbl
     *
     * @mbggenerated do_not_delete_during_merge Wed Jan 23 17:42:39 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table video_sourceinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}