package org.apache.nutch.parse.html.video.database.model;

import java.util.ArrayList;
import java.util.List;

public class VideoPlayinfoTblExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table video_playinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table video_playinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table video_playinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_playinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public VideoPlayinfoTblExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_playinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_playinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_playinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_playinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_playinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_playinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_playinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_playinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_playinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_playinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table video_playinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andVsSubvidIsNull() {
            addCriterion("vs_subvid is null");
            return (Criteria) this;
        }

        public Criteria andVsSubvidIsNotNull() {
            addCriterion("vs_subvid is not null");
            return (Criteria) this;
        }

        public Criteria andVsSubvidEqualTo(String value) {
            addCriterion("vs_subvid =", value, "vsSubvid");
            return (Criteria) this;
        }

        public Criteria andVsSubvidNotEqualTo(String value) {
            addCriterion("vs_subvid <>", value, "vsSubvid");
            return (Criteria) this;
        }

        public Criteria andVsSubvidGreaterThan(String value) {
            addCriterion("vs_subvid >", value, "vsSubvid");
            return (Criteria) this;
        }

        public Criteria andVsSubvidGreaterThanOrEqualTo(String value) {
            addCriterion("vs_subvid >=", value, "vsSubvid");
            return (Criteria) this;
        }

        public Criteria andVsSubvidLessThan(String value) {
            addCriterion("vs_subvid <", value, "vsSubvid");
            return (Criteria) this;
        }

        public Criteria andVsSubvidLessThanOrEqualTo(String value) {
            addCriterion("vs_subvid <=", value, "vsSubvid");
            return (Criteria) this;
        }

        public Criteria andVsSubvidLike(String value) {
            addCriterion("vs_subvid like", value, "vsSubvid");
            return (Criteria) this;
        }

        public Criteria andVsSubvidNotLike(String value) {
            addCriterion("vs_subvid not like", value, "vsSubvid");
            return (Criteria) this;
        }

        public Criteria andVsSubvidIn(List<String> values) {
            addCriterion("vs_subvid in", values, "vsSubvid");
            return (Criteria) this;
        }

        public Criteria andVsSubvidNotIn(List<String> values) {
            addCriterion("vs_subvid not in", values, "vsSubvid");
            return (Criteria) this;
        }

        public Criteria andVsSubvidBetween(String value1, String value2) {
            addCriterion("vs_subvid between", value1, value2, "vsSubvid");
            return (Criteria) this;
        }

        public Criteria andVsSubvidNotBetween(String value1, String value2) {
            addCriterion("vs_subvid not between", value1, value2, "vsSubvid");
            return (Criteria) this;
        }

        public Criteria andVpDefinitionIsNull() {
            addCriterion("vp_definition is null");
            return (Criteria) this;
        }

        public Criteria andVpDefinitionIsNotNull() {
            addCriterion("vp_definition is not null");
            return (Criteria) this;
        }

        public Criteria andVpDefinitionEqualTo(Short value) {
            addCriterion("vp_definition =", value, "vpDefinition");
            return (Criteria) this;
        }

        public Criteria andVpDefinitionNotEqualTo(Short value) {
            addCriterion("vp_definition <>", value, "vpDefinition");
            return (Criteria) this;
        }

        public Criteria andVpDefinitionGreaterThan(Short value) {
            addCriterion("vp_definition >", value, "vpDefinition");
            return (Criteria) this;
        }

        public Criteria andVpDefinitionGreaterThanOrEqualTo(Short value) {
            addCriterion("vp_definition >=", value, "vpDefinition");
            return (Criteria) this;
        }

        public Criteria andVpDefinitionLessThan(Short value) {
            addCriterion("vp_definition <", value, "vpDefinition");
            return (Criteria) this;
        }

        public Criteria andVpDefinitionLessThanOrEqualTo(Short value) {
            addCriterion("vp_definition <=", value, "vpDefinition");
            return (Criteria) this;
        }

        public Criteria andVpDefinitionIn(List<Short> values) {
            addCriterion("vp_definition in", values, "vpDefinition");
            return (Criteria) this;
        }

        public Criteria andVpDefinitionNotIn(List<Short> values) {
            addCriterion("vp_definition not in", values, "vpDefinition");
            return (Criteria) this;
        }

        public Criteria andVpDefinitionBetween(Short value1, Short value2) {
            addCriterion("vp_definition between", value1, value2, "vpDefinition");
            return (Criteria) this;
        }

        public Criteria andVpDefinitionNotBetween(Short value1, Short value2) {
            addCriterion("vp_definition not between", value1, value2, "vpDefinition");
            return (Criteria) this;
        }

        public Criteria andVpPlayurlIsNull() {
            addCriterion("vp_playurl is null");
            return (Criteria) this;
        }

        public Criteria andVpPlayurlIsNotNull() {
            addCriterion("vp_playurl is not null");
            return (Criteria) this;
        }

        public Criteria andVpPlayurlEqualTo(String value) {
            addCriterion("vp_playurl =", value, "vpPlayurl");
            return (Criteria) this;
        }

        public Criteria andVpPlayurlNotEqualTo(String value) {
            addCriterion("vp_playurl <>", value, "vpPlayurl");
            return (Criteria) this;
        }

        public Criteria andVpPlayurlGreaterThan(String value) {
            addCriterion("vp_playurl >", value, "vpPlayurl");
            return (Criteria) this;
        }

        public Criteria andVpPlayurlGreaterThanOrEqualTo(String value) {
            addCriterion("vp_playurl >=", value, "vpPlayurl");
            return (Criteria) this;
        }

        public Criteria andVpPlayurlLessThan(String value) {
            addCriterion("vp_playurl <", value, "vpPlayurl");
            return (Criteria) this;
        }

        public Criteria andVpPlayurlLessThanOrEqualTo(String value) {
            addCriterion("vp_playurl <=", value, "vpPlayurl");
            return (Criteria) this;
        }

        public Criteria andVpPlayurlLike(String value) {
            addCriterion("vp_playurl like", value, "vpPlayurl");
            return (Criteria) this;
        }

        public Criteria andVpPlayurlNotLike(String value) {
            addCriterion("vp_playurl not like", value, "vpPlayurl");
            return (Criteria) this;
        }

        public Criteria andVpPlayurlIn(List<String> values) {
            addCriterion("vp_playurl in", values, "vpPlayurl");
            return (Criteria) this;
        }

        public Criteria andVpPlayurlNotIn(List<String> values) {
            addCriterion("vp_playurl not in", values, "vpPlayurl");
            return (Criteria) this;
        }

        public Criteria andVpPlayurlBetween(String value1, String value2) {
            addCriterion("vp_playurl between", value1, value2, "vpPlayurl");
            return (Criteria) this;
        }

        public Criteria andVpPlayurlNotBetween(String value1, String value2) {
            addCriterion("vp_playurl not between", value1, value2, "vpPlayurl");
            return (Criteria) this;
        }

        public Criteria andVpReserved0IsNull() {
            addCriterion("vp_reserved_0 is null");
            return (Criteria) this;
        }

        public Criteria andVpReserved0IsNotNull() {
            addCriterion("vp_reserved_0 is not null");
            return (Criteria) this;
        }

        public Criteria andVpReserved0EqualTo(String value) {
            addCriterion("vp_reserved_0 =", value, "vpReserved0");
            return (Criteria) this;
        }

        public Criteria andVpReserved0NotEqualTo(String value) {
            addCriterion("vp_reserved_0 <>", value, "vpReserved0");
            return (Criteria) this;
        }

        public Criteria andVpReserved0GreaterThan(String value) {
            addCriterion("vp_reserved_0 >", value, "vpReserved0");
            return (Criteria) this;
        }

        public Criteria andVpReserved0GreaterThanOrEqualTo(String value) {
            addCriterion("vp_reserved_0 >=", value, "vpReserved0");
            return (Criteria) this;
        }

        public Criteria andVpReserved0LessThan(String value) {
            addCriterion("vp_reserved_0 <", value, "vpReserved0");
            return (Criteria) this;
        }

        public Criteria andVpReserved0LessThanOrEqualTo(String value) {
            addCriterion("vp_reserved_0 <=", value, "vpReserved0");
            return (Criteria) this;
        }

        public Criteria andVpReserved0Like(String value) {
            addCriterion("vp_reserved_0 like", value, "vpReserved0");
            return (Criteria) this;
        }

        public Criteria andVpReserved0NotLike(String value) {
            addCriterion("vp_reserved_0 not like", value, "vpReserved0");
            return (Criteria) this;
        }

        public Criteria andVpReserved0In(List<String> values) {
            addCriterion("vp_reserved_0 in", values, "vpReserved0");
            return (Criteria) this;
        }

        public Criteria andVpReserved0NotIn(List<String> values) {
            addCriterion("vp_reserved_0 not in", values, "vpReserved0");
            return (Criteria) this;
        }

        public Criteria andVpReserved0Between(String value1, String value2) {
            addCriterion("vp_reserved_0 between", value1, value2, "vpReserved0");
            return (Criteria) this;
        }

        public Criteria andVpReserved0NotBetween(String value1, String value2) {
            addCriterion("vp_reserved_0 not between", value1, value2, "vpReserved0");
            return (Criteria) this;
        }

        public Criteria andVpReserved1IsNull() {
            addCriterion("vp_reserved_1 is null");
            return (Criteria) this;
        }

        public Criteria andVpReserved1IsNotNull() {
            addCriterion("vp_reserved_1 is not null");
            return (Criteria) this;
        }

        public Criteria andVpReserved1EqualTo(String value) {
            addCriterion("vp_reserved_1 =", value, "vpReserved1");
            return (Criteria) this;
        }

        public Criteria andVpReserved1NotEqualTo(String value) {
            addCriterion("vp_reserved_1 <>", value, "vpReserved1");
            return (Criteria) this;
        }

        public Criteria andVpReserved1GreaterThan(String value) {
            addCriterion("vp_reserved_1 >", value, "vpReserved1");
            return (Criteria) this;
        }

        public Criteria andVpReserved1GreaterThanOrEqualTo(String value) {
            addCriterion("vp_reserved_1 >=", value, "vpReserved1");
            return (Criteria) this;
        }

        public Criteria andVpReserved1LessThan(String value) {
            addCriterion("vp_reserved_1 <", value, "vpReserved1");
            return (Criteria) this;
        }

        public Criteria andVpReserved1LessThanOrEqualTo(String value) {
            addCriterion("vp_reserved_1 <=", value, "vpReserved1");
            return (Criteria) this;
        }

        public Criteria andVpReserved1Like(String value) {
            addCriterion("vp_reserved_1 like", value, "vpReserved1");
            return (Criteria) this;
        }

        public Criteria andVpReserved1NotLike(String value) {
            addCriterion("vp_reserved_1 not like", value, "vpReserved1");
            return (Criteria) this;
        }

        public Criteria andVpReserved1In(List<String> values) {
            addCriterion("vp_reserved_1 in", values, "vpReserved1");
            return (Criteria) this;
        }

        public Criteria andVpReserved1NotIn(List<String> values) {
            addCriterion("vp_reserved_1 not in", values, "vpReserved1");
            return (Criteria) this;
        }

        public Criteria andVpReserved1Between(String value1, String value2) {
            addCriterion("vp_reserved_1 between", value1, value2, "vpReserved1");
            return (Criteria) this;
        }

        public Criteria andVpReserved1NotBetween(String value1, String value2) {
            addCriterion("vp_reserved_1 not between", value1, value2, "vpReserved1");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table video_playinfo_tbl
     *
     * @mbggenerated do_not_delete_during_merge Wed Jan 23 17:42:39 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table video_playinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}