package org.apache.nutch.parse.html.video.database.model;

import java.util.Date;

public class VideoCrawlinfoTbl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_crawlinfo_tbl.id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_crawlinfo_tbl.vc_vid
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private String vcVid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_crawlinfo_tbl.vc_orifc
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private String vcOrifc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_crawlinfo_tbl.vc_orisc
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private String vcOrisc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_crawlinfo_tbl.vc_settotal
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private Integer vcSettotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_crawlinfo_tbl.vc_setlast
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private Integer vcSetlast;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_crawlinfo_tbl.vc_score
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private String vcScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_crawlinfo_tbl.vc_favor
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private Integer vcFavor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_crawlinfo_tbl.vc_step
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private Integer vcStep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_crawlinfo_tbl.vc_vod
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private Integer vcVod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_crawlinfo_tbl.vc_cost
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private Short vcCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_crawlinfo_tbl.vc_detailurl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private String vcDetailurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_crawlinfo_tbl.vc_orilast
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private Integer vcOrilast;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_crawlinfo_tbl.vc_orihot
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private Integer vcOrihot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_crawlinfo_tbl.vc_orihotfavor
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private Integer vcOrihotfavor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_crawlinfo_tbl.vc_orisearch
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private Integer vcOrisearch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_crawlinfo_tbl.vc_crawldate
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private Date vcCrawldate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_crawlinfo_tbl.vc_reserved_0
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private String vcReserved0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_crawlinfo_tbl.vc_reserved_1
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private String vcReserved1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_crawlinfo_tbl.vc_reserved_2
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private String vcReserved2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_crawlinfo_tbl.vc_reserved_3
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private String vcReserved3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_crawlinfo_tbl.cs_id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private Short csId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_crawlinfo_tbl.vb_id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private Integer vbId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_crawlinfo_tbl.id
     *
     * @return the value of video_crawlinfo_tbl.id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_crawlinfo_tbl.id
     *
     * @param id the value for video_crawlinfo_tbl.id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_crawlinfo_tbl.vc_vid
     *
     * @return the value of video_crawlinfo_tbl.vc_vid
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getVcVid() {
        return vcVid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_crawlinfo_tbl.vc_vid
     *
     * @param vcVid the value for video_crawlinfo_tbl.vc_vid
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVcVid(String vcVid) {
        this.vcVid = vcVid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_crawlinfo_tbl.vc_orifc
     *
     * @return the value of video_crawlinfo_tbl.vc_orifc
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getVcOrifc() {
        return vcOrifc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_crawlinfo_tbl.vc_orifc
     *
     * @param vcOrifc the value for video_crawlinfo_tbl.vc_orifc
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVcOrifc(String vcOrifc) {
        this.vcOrifc = vcOrifc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_crawlinfo_tbl.vc_orisc
     *
     * @return the value of video_crawlinfo_tbl.vc_orisc
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getVcOrisc() {
        return vcOrisc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_crawlinfo_tbl.vc_orisc
     *
     * @param vcOrisc the value for video_crawlinfo_tbl.vc_orisc
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVcOrisc(String vcOrisc) {
        this.vcOrisc = vcOrisc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_crawlinfo_tbl.vc_settotal
     *
     * @return the value of video_crawlinfo_tbl.vc_settotal
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Integer getVcSettotal() {
        return vcSettotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_crawlinfo_tbl.vc_settotal
     *
     * @param vcSettotal the value for video_crawlinfo_tbl.vc_settotal
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVcSettotal(Integer vcSettotal) {
        this.vcSettotal = vcSettotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_crawlinfo_tbl.vc_setlast
     *
     * @return the value of video_crawlinfo_tbl.vc_setlast
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Integer getVcSetlast() {
        return vcSetlast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_crawlinfo_tbl.vc_setlast
     *
     * @param vcSetlast the value for video_crawlinfo_tbl.vc_setlast
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVcSetlast(Integer vcSetlast) {
        this.vcSetlast = vcSetlast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_crawlinfo_tbl.vc_score
     *
     * @return the value of video_crawlinfo_tbl.vc_score
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getVcScore() {
        return vcScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_crawlinfo_tbl.vc_score
     *
     * @param vcScore the value for video_crawlinfo_tbl.vc_score
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVcScore(String vcScore) {
        this.vcScore = vcScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_crawlinfo_tbl.vc_favor
     *
     * @return the value of video_crawlinfo_tbl.vc_favor
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Integer getVcFavor() {
        return vcFavor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_crawlinfo_tbl.vc_favor
     *
     * @param vcFavor the value for video_crawlinfo_tbl.vc_favor
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVcFavor(Integer vcFavor) {
        this.vcFavor = vcFavor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_crawlinfo_tbl.vc_step
     *
     * @return the value of video_crawlinfo_tbl.vc_step
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Integer getVcStep() {
        return vcStep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_crawlinfo_tbl.vc_step
     *
     * @param vcStep the value for video_crawlinfo_tbl.vc_step
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVcStep(Integer vcStep) {
        this.vcStep = vcStep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_crawlinfo_tbl.vc_vod
     *
     * @return the value of video_crawlinfo_tbl.vc_vod
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Integer getVcVod() {
        return vcVod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_crawlinfo_tbl.vc_vod
     *
     * @param vcVod the value for video_crawlinfo_tbl.vc_vod
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVcVod(Integer vcVod) {
        this.vcVod = vcVod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_crawlinfo_tbl.vc_cost
     *
     * @return the value of video_crawlinfo_tbl.vc_cost
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Short getVcCost() {
        return vcCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_crawlinfo_tbl.vc_cost
     *
     * @param vcCost the value for video_crawlinfo_tbl.vc_cost
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVcCost(Short vcCost) {
        this.vcCost = vcCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_crawlinfo_tbl.vc_detailurl
     *
     * @return the value of video_crawlinfo_tbl.vc_detailurl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getVcDetailurl() {
        return vcDetailurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_crawlinfo_tbl.vc_detailurl
     *
     * @param vcDetailurl the value for video_crawlinfo_tbl.vc_detailurl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVcDetailurl(String vcDetailurl) {
        this.vcDetailurl = vcDetailurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_crawlinfo_tbl.vc_orilast
     *
     * @return the value of video_crawlinfo_tbl.vc_orilast
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Integer getVcOrilast() {
        return vcOrilast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_crawlinfo_tbl.vc_orilast
     *
     * @param vcOrilast the value for video_crawlinfo_tbl.vc_orilast
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVcOrilast(Integer vcOrilast) {
        this.vcOrilast = vcOrilast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_crawlinfo_tbl.vc_orihot
     *
     * @return the value of video_crawlinfo_tbl.vc_orihot
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Integer getVcOrihot() {
        return vcOrihot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_crawlinfo_tbl.vc_orihot
     *
     * @param vcOrihot the value for video_crawlinfo_tbl.vc_orihot
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVcOrihot(Integer vcOrihot) {
        this.vcOrihot = vcOrihot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_crawlinfo_tbl.vc_orihotfavor
     *
     * @return the value of video_crawlinfo_tbl.vc_orihotfavor
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Integer getVcOrihotfavor() {
        return vcOrihotfavor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_crawlinfo_tbl.vc_orihotfavor
     *
     * @param vcOrihotfavor the value for video_crawlinfo_tbl.vc_orihotfavor
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVcOrihotfavor(Integer vcOrihotfavor) {
        this.vcOrihotfavor = vcOrihotfavor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_crawlinfo_tbl.vc_orisearch
     *
     * @return the value of video_crawlinfo_tbl.vc_orisearch
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Integer getVcOrisearch() {
        return vcOrisearch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_crawlinfo_tbl.vc_orisearch
     *
     * @param vcOrisearch the value for video_crawlinfo_tbl.vc_orisearch
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVcOrisearch(Integer vcOrisearch) {
        this.vcOrisearch = vcOrisearch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_crawlinfo_tbl.vc_crawldate
     *
     * @return the value of video_crawlinfo_tbl.vc_crawldate
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Date getVcCrawldate() {
        return vcCrawldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_crawlinfo_tbl.vc_crawldate
     *
     * @param vcCrawldate the value for video_crawlinfo_tbl.vc_crawldate
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVcCrawldate(Date vcCrawldate) {
        this.vcCrawldate = vcCrawldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_crawlinfo_tbl.vc_reserved_0
     *
     * @return the value of video_crawlinfo_tbl.vc_reserved_0
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getVcReserved0() {
        return vcReserved0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_crawlinfo_tbl.vc_reserved_0
     *
     * @param vcReserved0 the value for video_crawlinfo_tbl.vc_reserved_0
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVcReserved0(String vcReserved0) {
        this.vcReserved0 = vcReserved0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_crawlinfo_tbl.vc_reserved_1
     *
     * @return the value of video_crawlinfo_tbl.vc_reserved_1
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getVcReserved1() {
        return vcReserved1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_crawlinfo_tbl.vc_reserved_1
     *
     * @param vcReserved1 the value for video_crawlinfo_tbl.vc_reserved_1
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVcReserved1(String vcReserved1) {
        this.vcReserved1 = vcReserved1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_crawlinfo_tbl.vc_reserved_2
     *
     * @return the value of video_crawlinfo_tbl.vc_reserved_2
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getVcReserved2() {
        return vcReserved2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_crawlinfo_tbl.vc_reserved_2
     *
     * @param vcReserved2 the value for video_crawlinfo_tbl.vc_reserved_2
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVcReserved2(String vcReserved2) {
        this.vcReserved2 = vcReserved2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_crawlinfo_tbl.vc_reserved_3
     *
     * @return the value of video_crawlinfo_tbl.vc_reserved_3
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getVcReserved3() {
        return vcReserved3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_crawlinfo_tbl.vc_reserved_3
     *
     * @param vcReserved3 the value for video_crawlinfo_tbl.vc_reserved_3
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVcReserved3(String vcReserved3) {
        this.vcReserved3 = vcReserved3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_crawlinfo_tbl.cs_id
     *
     * @return the value of video_crawlinfo_tbl.cs_id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Short getCsId() {
        return csId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_crawlinfo_tbl.cs_id
     *
     * @param csId the value for video_crawlinfo_tbl.cs_id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setCsId(Short csId) {
        this.csId = csId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_crawlinfo_tbl.vb_id
     *
     * @return the value of video_crawlinfo_tbl.vb_id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Integer getVbId() {
        return vbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_crawlinfo_tbl.vb_id
     *
     * @param vbId the value for video_crawlinfo_tbl.vb_id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVbId(Integer vbId) {
        this.vbId = vbId;
    }
}