package org.apache.nutch.parse.html.video.database.model;

public class VideoBaseinfoTbl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_baseinfo_tbl.vb_id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private Integer vbId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_baseinfo_tbl.vb_name
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private String vbName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_baseinfo_tbl.vb_alias
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private String vbAlias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_baseinfo_tbl.vb_spec
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private Short vbSpec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_baseinfo_tbl.vb_year
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private String vbYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_baseinfo_tbl.vb_director
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private String vbDirector;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_baseinfo_tbl.vb_actor
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private String vbActor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_baseinfo_tbl.vb_label
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private String vbLabel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_baseinfo_tbl.vb_duration
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private Short vbDuration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_baseinfo_tbl.vb_language
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private String vbLanguage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_baseinfo_tbl.vb_simpledesc
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private String vbSimpledesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_baseinfo_tbl.vb_longdesc
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private String vbLongdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_baseinfo_tbl.vb_avescore
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private String vbAvescore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_baseinfo_tbl.vb_totalfavor
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private Integer vbTotalfavor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_baseinfo_tbl.vb_totalstep
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private Integer vbTotalstep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_baseinfo_tbl.vb_totalvod
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private Integer vbTotalvod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_baseinfo_tbl.vb_firstsource
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private Short vbFirstsource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_baseinfo_tbl.vb_firstletter
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private String vbFirstletter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_baseinfo_tbl.vb_pinyin
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private String vbPinyin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_baseinfo_tbl.vb_totallast
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private Integer vbTotallast;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_baseinfo_tbl.vb_totalhot
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private Integer vbTotalhot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_baseinfo_tbl.vb_totalhotfavor
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private Integer vbTotalhotfavor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_baseinfo_tbl.vb_totalsearch
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private Integer vbTotalsearch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_baseinfo_tbl.vb_doubanscore
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private String vbDoubanscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_baseinfo_tbl.vb_doubancomment
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private String vbDoubancomment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_baseinfo_tbl.vb_reserved_0
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private String vbReserved0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_baseinfo_tbl.vb_reserved_1
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private String vbReserved1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_baseinfo_tbl.vb_reserved_2
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private String vbReserved2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_baseinfo_tbl.vb_reserved_3
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private String vbReserved3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_baseinfo_tbl.fc_id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private Short fcId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_baseinfo_tbl.ac_id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private Short acId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_baseinfo_tbl.vb_id
     *
     * @return the value of video_baseinfo_tbl.vb_id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Integer getVbId() {
        return vbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_baseinfo_tbl.vb_id
     *
     * @param vbId the value for video_baseinfo_tbl.vb_id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVbId(Integer vbId) {
        this.vbId = vbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_baseinfo_tbl.vb_name
     *
     * @return the value of video_baseinfo_tbl.vb_name
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getVbName() {
        return vbName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_baseinfo_tbl.vb_name
     *
     * @param vbName the value for video_baseinfo_tbl.vb_name
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVbName(String vbName) {
        this.vbName = vbName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_baseinfo_tbl.vb_alias
     *
     * @return the value of video_baseinfo_tbl.vb_alias
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getVbAlias() {
        return vbAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_baseinfo_tbl.vb_alias
     *
     * @param vbAlias the value for video_baseinfo_tbl.vb_alias
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVbAlias(String vbAlias) {
        this.vbAlias = vbAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_baseinfo_tbl.vb_spec
     *
     * @return the value of video_baseinfo_tbl.vb_spec
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Short getVbSpec() {
        return vbSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_baseinfo_tbl.vb_spec
     *
     * @param vbSpec the value for video_baseinfo_tbl.vb_spec
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVbSpec(Short vbSpec) {
        this.vbSpec = vbSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_baseinfo_tbl.vb_year
     *
     * @return the value of video_baseinfo_tbl.vb_year
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getVbYear() {
        return vbYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_baseinfo_tbl.vb_year
     *
     * @param vbYear the value for video_baseinfo_tbl.vb_year
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVbYear(String vbYear) {
        this.vbYear = vbYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_baseinfo_tbl.vb_director
     *
     * @return the value of video_baseinfo_tbl.vb_director
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getVbDirector() {
        return vbDirector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_baseinfo_tbl.vb_director
     *
     * @param vbDirector the value for video_baseinfo_tbl.vb_director
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVbDirector(String vbDirector) {
        this.vbDirector = vbDirector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_baseinfo_tbl.vb_actor
     *
     * @return the value of video_baseinfo_tbl.vb_actor
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getVbActor() {
        return vbActor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_baseinfo_tbl.vb_actor
     *
     * @param vbActor the value for video_baseinfo_tbl.vb_actor
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVbActor(String vbActor) {
        this.vbActor = vbActor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_baseinfo_tbl.vb_label
     *
     * @return the value of video_baseinfo_tbl.vb_label
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getVbLabel() {
        return vbLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_baseinfo_tbl.vb_label
     *
     * @param vbLabel the value for video_baseinfo_tbl.vb_label
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVbLabel(String vbLabel) {
        this.vbLabel = vbLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_baseinfo_tbl.vb_duration
     *
     * @return the value of video_baseinfo_tbl.vb_duration
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Short getVbDuration() {
        return vbDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_baseinfo_tbl.vb_duration
     *
     * @param vbDuration the value for video_baseinfo_tbl.vb_duration
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVbDuration(Short vbDuration) {
        this.vbDuration = vbDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_baseinfo_tbl.vb_language
     *
     * @return the value of video_baseinfo_tbl.vb_language
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getVbLanguage() {
        return vbLanguage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_baseinfo_tbl.vb_language
     *
     * @param vbLanguage the value for video_baseinfo_tbl.vb_language
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVbLanguage(String vbLanguage) {
        this.vbLanguage = vbLanguage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_baseinfo_tbl.vb_simpledesc
     *
     * @return the value of video_baseinfo_tbl.vb_simpledesc
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getVbSimpledesc() {
        return vbSimpledesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_baseinfo_tbl.vb_simpledesc
     *
     * @param vbSimpledesc the value for video_baseinfo_tbl.vb_simpledesc
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVbSimpledesc(String vbSimpledesc) {
        this.vbSimpledesc = vbSimpledesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_baseinfo_tbl.vb_longdesc
     *
     * @return the value of video_baseinfo_tbl.vb_longdesc
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getVbLongdesc() {
        return vbLongdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_baseinfo_tbl.vb_longdesc
     *
     * @param vbLongdesc the value for video_baseinfo_tbl.vb_longdesc
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVbLongdesc(String vbLongdesc) {
        this.vbLongdesc = vbLongdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_baseinfo_tbl.vb_avescore
     *
     * @return the value of video_baseinfo_tbl.vb_avescore
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getVbAvescore() {
        return vbAvescore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_baseinfo_tbl.vb_avescore
     *
     * @param vbAvescore the value for video_baseinfo_tbl.vb_avescore
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVbAvescore(String vbAvescore) {
        this.vbAvescore = vbAvescore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_baseinfo_tbl.vb_totalfavor
     *
     * @return the value of video_baseinfo_tbl.vb_totalfavor
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Integer getVbTotalfavor() {
        return vbTotalfavor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_baseinfo_tbl.vb_totalfavor
     *
     * @param vbTotalfavor the value for video_baseinfo_tbl.vb_totalfavor
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVbTotalfavor(Integer vbTotalfavor) {
        this.vbTotalfavor = vbTotalfavor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_baseinfo_tbl.vb_totalstep
     *
     * @return the value of video_baseinfo_tbl.vb_totalstep
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Integer getVbTotalstep() {
        return vbTotalstep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_baseinfo_tbl.vb_totalstep
     *
     * @param vbTotalstep the value for video_baseinfo_tbl.vb_totalstep
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVbTotalstep(Integer vbTotalstep) {
        this.vbTotalstep = vbTotalstep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_baseinfo_tbl.vb_totalvod
     *
     * @return the value of video_baseinfo_tbl.vb_totalvod
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Integer getVbTotalvod() {
        return vbTotalvod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_baseinfo_tbl.vb_totalvod
     *
     * @param vbTotalvod the value for video_baseinfo_tbl.vb_totalvod
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVbTotalvod(Integer vbTotalvod) {
        this.vbTotalvod = vbTotalvod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_baseinfo_tbl.vb_firstsource
     *
     * @return the value of video_baseinfo_tbl.vb_firstsource
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Short getVbFirstsource() {
        return vbFirstsource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_baseinfo_tbl.vb_firstsource
     *
     * @param vbFirstsource the value for video_baseinfo_tbl.vb_firstsource
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVbFirstsource(Short vbFirstsource) {
        this.vbFirstsource = vbFirstsource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_baseinfo_tbl.vb_firstletter
     *
     * @return the value of video_baseinfo_tbl.vb_firstletter
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getVbFirstletter() {
        return vbFirstletter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_baseinfo_tbl.vb_firstletter
     *
     * @param vbFirstletter the value for video_baseinfo_tbl.vb_firstletter
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVbFirstletter(String vbFirstletter) {
        this.vbFirstletter = vbFirstletter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_baseinfo_tbl.vb_pinyin
     *
     * @return the value of video_baseinfo_tbl.vb_pinyin
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getVbPinyin() {
        return vbPinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_baseinfo_tbl.vb_pinyin
     *
     * @param vbPinyin the value for video_baseinfo_tbl.vb_pinyin
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVbPinyin(String vbPinyin) {
        this.vbPinyin = vbPinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_baseinfo_tbl.vb_totallast
     *
     * @return the value of video_baseinfo_tbl.vb_totallast
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Integer getVbTotallast() {
        return vbTotallast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_baseinfo_tbl.vb_totallast
     *
     * @param vbTotallast the value for video_baseinfo_tbl.vb_totallast
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVbTotallast(Integer vbTotallast) {
        this.vbTotallast = vbTotallast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_baseinfo_tbl.vb_totalhot
     *
     * @return the value of video_baseinfo_tbl.vb_totalhot
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Integer getVbTotalhot() {
        return vbTotalhot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_baseinfo_tbl.vb_totalhot
     *
     * @param vbTotalhot the value for video_baseinfo_tbl.vb_totalhot
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVbTotalhot(Integer vbTotalhot) {
        this.vbTotalhot = vbTotalhot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_baseinfo_tbl.vb_totalhotfavor
     *
     * @return the value of video_baseinfo_tbl.vb_totalhotfavor
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Integer getVbTotalhotfavor() {
        return vbTotalhotfavor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_baseinfo_tbl.vb_totalhotfavor
     *
     * @param vbTotalhotfavor the value for video_baseinfo_tbl.vb_totalhotfavor
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVbTotalhotfavor(Integer vbTotalhotfavor) {
        this.vbTotalhotfavor = vbTotalhotfavor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_baseinfo_tbl.vb_totalsearch
     *
     * @return the value of video_baseinfo_tbl.vb_totalsearch
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Integer getVbTotalsearch() {
        return vbTotalsearch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_baseinfo_tbl.vb_totalsearch
     *
     * @param vbTotalsearch the value for video_baseinfo_tbl.vb_totalsearch
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVbTotalsearch(Integer vbTotalsearch) {
        this.vbTotalsearch = vbTotalsearch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_baseinfo_tbl.vb_doubanscore
     *
     * @return the value of video_baseinfo_tbl.vb_doubanscore
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getVbDoubanscore() {
        return vbDoubanscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_baseinfo_tbl.vb_doubanscore
     *
     * @param vbDoubanscore the value for video_baseinfo_tbl.vb_doubanscore
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVbDoubanscore(String vbDoubanscore) {
        this.vbDoubanscore = vbDoubanscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_baseinfo_tbl.vb_doubancomment
     *
     * @return the value of video_baseinfo_tbl.vb_doubancomment
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getVbDoubancomment() {
        return vbDoubancomment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_baseinfo_tbl.vb_doubancomment
     *
     * @param vbDoubancomment the value for video_baseinfo_tbl.vb_doubancomment
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVbDoubancomment(String vbDoubancomment) {
        this.vbDoubancomment = vbDoubancomment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_baseinfo_tbl.vb_reserved_0
     *
     * @return the value of video_baseinfo_tbl.vb_reserved_0
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getVbReserved0() {
        return vbReserved0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_baseinfo_tbl.vb_reserved_0
     *
     * @param vbReserved0 the value for video_baseinfo_tbl.vb_reserved_0
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVbReserved0(String vbReserved0) {
        this.vbReserved0 = vbReserved0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_baseinfo_tbl.vb_reserved_1
     *
     * @return the value of video_baseinfo_tbl.vb_reserved_1
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getVbReserved1() {
        return vbReserved1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_baseinfo_tbl.vb_reserved_1
     *
     * @param vbReserved1 the value for video_baseinfo_tbl.vb_reserved_1
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVbReserved1(String vbReserved1) {
        this.vbReserved1 = vbReserved1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_baseinfo_tbl.vb_reserved_2
     *
     * @return the value of video_baseinfo_tbl.vb_reserved_2
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getVbReserved2() {
        return vbReserved2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_baseinfo_tbl.vb_reserved_2
     *
     * @param vbReserved2 the value for video_baseinfo_tbl.vb_reserved_2
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVbReserved2(String vbReserved2) {
        this.vbReserved2 = vbReserved2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_baseinfo_tbl.vb_reserved_3
     *
     * @return the value of video_baseinfo_tbl.vb_reserved_3
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getVbReserved3() {
        return vbReserved3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_baseinfo_tbl.vb_reserved_3
     *
     * @param vbReserved3 the value for video_baseinfo_tbl.vb_reserved_3
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVbReserved3(String vbReserved3) {
        this.vbReserved3 = vbReserved3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_baseinfo_tbl.fc_id
     *
     * @return the value of video_baseinfo_tbl.fc_id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Short getFcId() {
        return fcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_baseinfo_tbl.fc_id
     *
     * @param fcId the value for video_baseinfo_tbl.fc_id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setFcId(Short fcId) {
        this.fcId = fcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_baseinfo_tbl.ac_id
     *
     * @return the value of video_baseinfo_tbl.ac_id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Short getAcId() {
        return acId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_baseinfo_tbl.ac_id
     *
     * @param acId the value for video_baseinfo_tbl.ac_id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setAcId(Short acId) {
        this.acId = acId;
    }
}