package org.apache.nutch.parse.html.video.database.model;

public class ContentSupplierTbl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_supplier_tbl.cs_id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private Short csId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_supplier_tbl.cs_name
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private String csName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_supplier_tbl.cs_logo_path
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private String csLogoPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_supplier_tbl.cs_baseurl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private String csBaseurl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_supplier_tbl.cs_id
     *
     * @return the value of content_supplier_tbl.cs_id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Short getCsId() {
        return csId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_supplier_tbl.cs_id
     *
     * @param csId the value for content_supplier_tbl.cs_id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setCsId(Short csId) {
        this.csId = csId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_supplier_tbl.cs_name
     *
     * @return the value of content_supplier_tbl.cs_name
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getCsName() {
        return csName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_supplier_tbl.cs_name
     *
     * @param csName the value for content_supplier_tbl.cs_name
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setCsName(String csName) {
        this.csName = csName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_supplier_tbl.cs_logo_path
     *
     * @return the value of content_supplier_tbl.cs_logo_path
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getCsLogoPath() {
        return csLogoPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_supplier_tbl.cs_logo_path
     *
     * @param csLogoPath the value for content_supplier_tbl.cs_logo_path
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setCsLogoPath(String csLogoPath) {
        this.csLogoPath = csLogoPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_supplier_tbl.cs_baseurl
     *
     * @return the value of content_supplier_tbl.cs_baseurl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getCsBaseurl() {
        return csBaseurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_supplier_tbl.cs_baseurl
     *
     * @param csBaseurl the value for content_supplier_tbl.cs_baseurl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setCsBaseurl(String csBaseurl) {
        this.csBaseurl = csBaseurl;
    }
}