package org.apache.nutch.parse.html.video.database.model;

public class FirstlevelCategoryTbl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firstlevel_category_tbl.fc_id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private Short fcId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firstlevel_category_tbl.fc_name
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private String fcName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firstlevel_category_tbl.fc_img_path
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private String fcImgPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firstlevel_category_tbl.relate_fcid
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private Short relateFcid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firstlevel_category_tbl.is_pub
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private Boolean isPub;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firstlevel_category_tbl.fc_id
     *
     * @return the value of firstlevel_category_tbl.fc_id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Short getFcId() {
        return fcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firstlevel_category_tbl.fc_id
     *
     * @param fcId the value for firstlevel_category_tbl.fc_id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setFcId(Short fcId) {
        this.fcId = fcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firstlevel_category_tbl.fc_name
     *
     * @return the value of firstlevel_category_tbl.fc_name
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getFcName() {
        return fcName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firstlevel_category_tbl.fc_name
     *
     * @param fcName the value for firstlevel_category_tbl.fc_name
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setFcName(String fcName) {
        this.fcName = fcName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firstlevel_category_tbl.fc_img_path
     *
     * @return the value of firstlevel_category_tbl.fc_img_path
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getFcImgPath() {
        return fcImgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firstlevel_category_tbl.fc_img_path
     *
     * @param fcImgPath the value for firstlevel_category_tbl.fc_img_path
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setFcImgPath(String fcImgPath) {
        this.fcImgPath = fcImgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firstlevel_category_tbl.relate_fcid
     *
     * @return the value of firstlevel_category_tbl.relate_fcid
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Short getRelateFcid() {
        return relateFcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firstlevel_category_tbl.relate_fcid
     *
     * @param relateFcid the value for firstlevel_category_tbl.relate_fcid
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setRelateFcid(Short relateFcid) {
        this.relateFcid = relateFcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firstlevel_category_tbl.is_pub
     *
     * @return the value of firstlevel_category_tbl.is_pub
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Boolean getIsPub() {
        return isPub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firstlevel_category_tbl.is_pub
     *
     * @param isPub the value for firstlevel_category_tbl.is_pub
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setIsPub(Boolean isPub) {
        this.isPub = isPub;
    }
}