package org.apache.nutch.parse.html.video.database.model;

public class VideoScRefTbl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_sc_ref_tbl.id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_sc_ref_tbl.sc_id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private Short scId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_sc_ref_tbl.vb_id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private Integer vbId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_sc_ref_tbl.id
     *
     * @return the value of video_sc_ref_tbl.id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_sc_ref_tbl.id
     *
     * @param id the value for video_sc_ref_tbl.id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_sc_ref_tbl.sc_id
     *
     * @return the value of video_sc_ref_tbl.sc_id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Short getScId() {
        return scId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_sc_ref_tbl.sc_id
     *
     * @param scId the value for video_sc_ref_tbl.sc_id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setScId(Short scId) {
        this.scId = scId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_sc_ref_tbl.vb_id
     *
     * @return the value of video_sc_ref_tbl.vb_id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Integer getVbId() {
        return vbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_sc_ref_tbl.vb_id
     *
     * @param vbId the value for video_sc_ref_tbl.vb_id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVbId(Integer vbId) {
        this.vbId = vbId;
    }
}