package org.apache.nutch.parse.html.video.database.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class VideoCrawlinfoTblExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table video_crawlinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table video_crawlinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table video_crawlinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_crawlinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public VideoCrawlinfoTblExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_crawlinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_crawlinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_crawlinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_crawlinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_crawlinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_crawlinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_crawlinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_crawlinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_crawlinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_crawlinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table video_crawlinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andVcVidIsNull() {
            addCriterion("vc_vid is null");
            return (Criteria) this;
        }

        public Criteria andVcVidIsNotNull() {
            addCriterion("vc_vid is not null");
            return (Criteria) this;
        }

        public Criteria andVcVidEqualTo(String value) {
            addCriterion("vc_vid =", value, "vcVid");
            return (Criteria) this;
        }

        public Criteria andVcVidNotEqualTo(String value) {
            addCriterion("vc_vid <>", value, "vcVid");
            return (Criteria) this;
        }

        public Criteria andVcVidGreaterThan(String value) {
            addCriterion("vc_vid >", value, "vcVid");
            return (Criteria) this;
        }

        public Criteria andVcVidGreaterThanOrEqualTo(String value) {
            addCriterion("vc_vid >=", value, "vcVid");
            return (Criteria) this;
        }

        public Criteria andVcVidLessThan(String value) {
            addCriterion("vc_vid <", value, "vcVid");
            return (Criteria) this;
        }

        public Criteria andVcVidLessThanOrEqualTo(String value) {
            addCriterion("vc_vid <=", value, "vcVid");
            return (Criteria) this;
        }

        public Criteria andVcVidLike(String value) {
            addCriterion("vc_vid like", value, "vcVid");
            return (Criteria) this;
        }

        public Criteria andVcVidNotLike(String value) {
            addCriterion("vc_vid not like", value, "vcVid");
            return (Criteria) this;
        }

        public Criteria andVcVidIn(List<String> values) {
            addCriterion("vc_vid in", values, "vcVid");
            return (Criteria) this;
        }

        public Criteria andVcVidNotIn(List<String> values) {
            addCriterion("vc_vid not in", values, "vcVid");
            return (Criteria) this;
        }

        public Criteria andVcVidBetween(String value1, String value2) {
            addCriterion("vc_vid between", value1, value2, "vcVid");
            return (Criteria) this;
        }

        public Criteria andVcVidNotBetween(String value1, String value2) {
            addCriterion("vc_vid not between", value1, value2, "vcVid");
            return (Criteria) this;
        }

        public Criteria andVcOrifcIsNull() {
            addCriterion("vc_orifc is null");
            return (Criteria) this;
        }

        public Criteria andVcOrifcIsNotNull() {
            addCriterion("vc_orifc is not null");
            return (Criteria) this;
        }

        public Criteria andVcOrifcEqualTo(String value) {
            addCriterion("vc_orifc =", value, "vcOrifc");
            return (Criteria) this;
        }

        public Criteria andVcOrifcNotEqualTo(String value) {
            addCriterion("vc_orifc <>", value, "vcOrifc");
            return (Criteria) this;
        }

        public Criteria andVcOrifcGreaterThan(String value) {
            addCriterion("vc_orifc >", value, "vcOrifc");
            return (Criteria) this;
        }

        public Criteria andVcOrifcGreaterThanOrEqualTo(String value) {
            addCriterion("vc_orifc >=", value, "vcOrifc");
            return (Criteria) this;
        }

        public Criteria andVcOrifcLessThan(String value) {
            addCriterion("vc_orifc <", value, "vcOrifc");
            return (Criteria) this;
        }

        public Criteria andVcOrifcLessThanOrEqualTo(String value) {
            addCriterion("vc_orifc <=", value, "vcOrifc");
            return (Criteria) this;
        }

        public Criteria andVcOrifcLike(String value) {
            addCriterion("vc_orifc like", value, "vcOrifc");
            return (Criteria) this;
        }

        public Criteria andVcOrifcNotLike(String value) {
            addCriterion("vc_orifc not like", value, "vcOrifc");
            return (Criteria) this;
        }

        public Criteria andVcOrifcIn(List<String> values) {
            addCriterion("vc_orifc in", values, "vcOrifc");
            return (Criteria) this;
        }

        public Criteria andVcOrifcNotIn(List<String> values) {
            addCriterion("vc_orifc not in", values, "vcOrifc");
            return (Criteria) this;
        }

        public Criteria andVcOrifcBetween(String value1, String value2) {
            addCriterion("vc_orifc between", value1, value2, "vcOrifc");
            return (Criteria) this;
        }

        public Criteria andVcOrifcNotBetween(String value1, String value2) {
            addCriterion("vc_orifc not between", value1, value2, "vcOrifc");
            return (Criteria) this;
        }

        public Criteria andVcOriscIsNull() {
            addCriterion("vc_orisc is null");
            return (Criteria) this;
        }

        public Criteria andVcOriscIsNotNull() {
            addCriterion("vc_orisc is not null");
            return (Criteria) this;
        }

        public Criteria andVcOriscEqualTo(String value) {
            addCriterion("vc_orisc =", value, "vcOrisc");
            return (Criteria) this;
        }

        public Criteria andVcOriscNotEqualTo(String value) {
            addCriterion("vc_orisc <>", value, "vcOrisc");
            return (Criteria) this;
        }

        public Criteria andVcOriscGreaterThan(String value) {
            addCriterion("vc_orisc >", value, "vcOrisc");
            return (Criteria) this;
        }

        public Criteria andVcOriscGreaterThanOrEqualTo(String value) {
            addCriterion("vc_orisc >=", value, "vcOrisc");
            return (Criteria) this;
        }

        public Criteria andVcOriscLessThan(String value) {
            addCriterion("vc_orisc <", value, "vcOrisc");
            return (Criteria) this;
        }

        public Criteria andVcOriscLessThanOrEqualTo(String value) {
            addCriterion("vc_orisc <=", value, "vcOrisc");
            return (Criteria) this;
        }

        public Criteria andVcOriscLike(String value) {
            addCriterion("vc_orisc like", value, "vcOrisc");
            return (Criteria) this;
        }

        public Criteria andVcOriscNotLike(String value) {
            addCriterion("vc_orisc not like", value, "vcOrisc");
            return (Criteria) this;
        }

        public Criteria andVcOriscIn(List<String> values) {
            addCriterion("vc_orisc in", values, "vcOrisc");
            return (Criteria) this;
        }

        public Criteria andVcOriscNotIn(List<String> values) {
            addCriterion("vc_orisc not in", values, "vcOrisc");
            return (Criteria) this;
        }

        public Criteria andVcOriscBetween(String value1, String value2) {
            addCriterion("vc_orisc between", value1, value2, "vcOrisc");
            return (Criteria) this;
        }

        public Criteria andVcOriscNotBetween(String value1, String value2) {
            addCriterion("vc_orisc not between", value1, value2, "vcOrisc");
            return (Criteria) this;
        }

        public Criteria andVcSettotalIsNull() {
            addCriterion("vc_settotal is null");
            return (Criteria) this;
        }

        public Criteria andVcSettotalIsNotNull() {
            addCriterion("vc_settotal is not null");
            return (Criteria) this;
        }

        public Criteria andVcSettotalEqualTo(Integer value) {
            addCriterion("vc_settotal =", value, "vcSettotal");
            return (Criteria) this;
        }

        public Criteria andVcSettotalNotEqualTo(Integer value) {
            addCriterion("vc_settotal <>", value, "vcSettotal");
            return (Criteria) this;
        }

        public Criteria andVcSettotalGreaterThan(Integer value) {
            addCriterion("vc_settotal >", value, "vcSettotal");
            return (Criteria) this;
        }

        public Criteria andVcSettotalGreaterThanOrEqualTo(Integer value) {
            addCriterion("vc_settotal >=", value, "vcSettotal");
            return (Criteria) this;
        }

        public Criteria andVcSettotalLessThan(Integer value) {
            addCriterion("vc_settotal <", value, "vcSettotal");
            return (Criteria) this;
        }

        public Criteria andVcSettotalLessThanOrEqualTo(Integer value) {
            addCriterion("vc_settotal <=", value, "vcSettotal");
            return (Criteria) this;
        }

        public Criteria andVcSettotalIn(List<Integer> values) {
            addCriterion("vc_settotal in", values, "vcSettotal");
            return (Criteria) this;
        }

        public Criteria andVcSettotalNotIn(List<Integer> values) {
            addCriterion("vc_settotal not in", values, "vcSettotal");
            return (Criteria) this;
        }

        public Criteria andVcSettotalBetween(Integer value1, Integer value2) {
            addCriterion("vc_settotal between", value1, value2, "vcSettotal");
            return (Criteria) this;
        }

        public Criteria andVcSettotalNotBetween(Integer value1, Integer value2) {
            addCriterion("vc_settotal not between", value1, value2, "vcSettotal");
            return (Criteria) this;
        }

        public Criteria andVcSetlastIsNull() {
            addCriterion("vc_setlast is null");
            return (Criteria) this;
        }

        public Criteria andVcSetlastIsNotNull() {
            addCriterion("vc_setlast is not null");
            return (Criteria) this;
        }

        public Criteria andVcSetlastEqualTo(Integer value) {
            addCriterion("vc_setlast =", value, "vcSetlast");
            return (Criteria) this;
        }

        public Criteria andVcSetlastNotEqualTo(Integer value) {
            addCriterion("vc_setlast <>", value, "vcSetlast");
            return (Criteria) this;
        }

        public Criteria andVcSetlastGreaterThan(Integer value) {
            addCriterion("vc_setlast >", value, "vcSetlast");
            return (Criteria) this;
        }

        public Criteria andVcSetlastGreaterThanOrEqualTo(Integer value) {
            addCriterion("vc_setlast >=", value, "vcSetlast");
            return (Criteria) this;
        }

        public Criteria andVcSetlastLessThan(Integer value) {
            addCriterion("vc_setlast <", value, "vcSetlast");
            return (Criteria) this;
        }

        public Criteria andVcSetlastLessThanOrEqualTo(Integer value) {
            addCriterion("vc_setlast <=", value, "vcSetlast");
            return (Criteria) this;
        }

        public Criteria andVcSetlastIn(List<Integer> values) {
            addCriterion("vc_setlast in", values, "vcSetlast");
            return (Criteria) this;
        }

        public Criteria andVcSetlastNotIn(List<Integer> values) {
            addCriterion("vc_setlast not in", values, "vcSetlast");
            return (Criteria) this;
        }

        public Criteria andVcSetlastBetween(Integer value1, Integer value2) {
            addCriterion("vc_setlast between", value1, value2, "vcSetlast");
            return (Criteria) this;
        }

        public Criteria andVcSetlastNotBetween(Integer value1, Integer value2) {
            addCriterion("vc_setlast not between", value1, value2, "vcSetlast");
            return (Criteria) this;
        }

        public Criteria andVcScoreIsNull() {
            addCriterion("vc_score is null");
            return (Criteria) this;
        }

        public Criteria andVcScoreIsNotNull() {
            addCriterion("vc_score is not null");
            return (Criteria) this;
        }

        public Criteria andVcScoreEqualTo(String value) {
            addCriterion("vc_score =", value, "vcScore");
            return (Criteria) this;
        }

        public Criteria andVcScoreNotEqualTo(String value) {
            addCriterion("vc_score <>", value, "vcScore");
            return (Criteria) this;
        }

        public Criteria andVcScoreGreaterThan(String value) {
            addCriterion("vc_score >", value, "vcScore");
            return (Criteria) this;
        }

        public Criteria andVcScoreGreaterThanOrEqualTo(String value) {
            addCriterion("vc_score >=", value, "vcScore");
            return (Criteria) this;
        }

        public Criteria andVcScoreLessThan(String value) {
            addCriterion("vc_score <", value, "vcScore");
            return (Criteria) this;
        }

        public Criteria andVcScoreLessThanOrEqualTo(String value) {
            addCriterion("vc_score <=", value, "vcScore");
            return (Criteria) this;
        }

        public Criteria andVcScoreLike(String value) {
            addCriterion("vc_score like", value, "vcScore");
            return (Criteria) this;
        }

        public Criteria andVcScoreNotLike(String value) {
            addCriterion("vc_score not like", value, "vcScore");
            return (Criteria) this;
        }

        public Criteria andVcScoreIn(List<String> values) {
            addCriterion("vc_score in", values, "vcScore");
            return (Criteria) this;
        }

        public Criteria andVcScoreNotIn(List<String> values) {
            addCriterion("vc_score not in", values, "vcScore");
            return (Criteria) this;
        }

        public Criteria andVcScoreBetween(String value1, String value2) {
            addCriterion("vc_score between", value1, value2, "vcScore");
            return (Criteria) this;
        }

        public Criteria andVcScoreNotBetween(String value1, String value2) {
            addCriterion("vc_score not between", value1, value2, "vcScore");
            return (Criteria) this;
        }

        public Criteria andVcFavorIsNull() {
            addCriterion("vc_favor is null");
            return (Criteria) this;
        }

        public Criteria andVcFavorIsNotNull() {
            addCriterion("vc_favor is not null");
            return (Criteria) this;
        }

        public Criteria andVcFavorEqualTo(Integer value) {
            addCriterion("vc_favor =", value, "vcFavor");
            return (Criteria) this;
        }

        public Criteria andVcFavorNotEqualTo(Integer value) {
            addCriterion("vc_favor <>", value, "vcFavor");
            return (Criteria) this;
        }

        public Criteria andVcFavorGreaterThan(Integer value) {
            addCriterion("vc_favor >", value, "vcFavor");
            return (Criteria) this;
        }

        public Criteria andVcFavorGreaterThanOrEqualTo(Integer value) {
            addCriterion("vc_favor >=", value, "vcFavor");
            return (Criteria) this;
        }

        public Criteria andVcFavorLessThan(Integer value) {
            addCriterion("vc_favor <", value, "vcFavor");
            return (Criteria) this;
        }

        public Criteria andVcFavorLessThanOrEqualTo(Integer value) {
            addCriterion("vc_favor <=", value, "vcFavor");
            return (Criteria) this;
        }

        public Criteria andVcFavorIn(List<Integer> values) {
            addCriterion("vc_favor in", values, "vcFavor");
            return (Criteria) this;
        }

        public Criteria andVcFavorNotIn(List<Integer> values) {
            addCriterion("vc_favor not in", values, "vcFavor");
            return (Criteria) this;
        }

        public Criteria andVcFavorBetween(Integer value1, Integer value2) {
            addCriterion("vc_favor between", value1, value2, "vcFavor");
            return (Criteria) this;
        }

        public Criteria andVcFavorNotBetween(Integer value1, Integer value2) {
            addCriterion("vc_favor not between", value1, value2, "vcFavor");
            return (Criteria) this;
        }

        public Criteria andVcStepIsNull() {
            addCriterion("vc_step is null");
            return (Criteria) this;
        }

        public Criteria andVcStepIsNotNull() {
            addCriterion("vc_step is not null");
            return (Criteria) this;
        }

        public Criteria andVcStepEqualTo(Integer value) {
            addCriterion("vc_step =", value, "vcStep");
            return (Criteria) this;
        }

        public Criteria andVcStepNotEqualTo(Integer value) {
            addCriterion("vc_step <>", value, "vcStep");
            return (Criteria) this;
        }

        public Criteria andVcStepGreaterThan(Integer value) {
            addCriterion("vc_step >", value, "vcStep");
            return (Criteria) this;
        }

        public Criteria andVcStepGreaterThanOrEqualTo(Integer value) {
            addCriterion("vc_step >=", value, "vcStep");
            return (Criteria) this;
        }

        public Criteria andVcStepLessThan(Integer value) {
            addCriterion("vc_step <", value, "vcStep");
            return (Criteria) this;
        }

        public Criteria andVcStepLessThanOrEqualTo(Integer value) {
            addCriterion("vc_step <=", value, "vcStep");
            return (Criteria) this;
        }

        public Criteria andVcStepIn(List<Integer> values) {
            addCriterion("vc_step in", values, "vcStep");
            return (Criteria) this;
        }

        public Criteria andVcStepNotIn(List<Integer> values) {
            addCriterion("vc_step not in", values, "vcStep");
            return (Criteria) this;
        }

        public Criteria andVcStepBetween(Integer value1, Integer value2) {
            addCriterion("vc_step between", value1, value2, "vcStep");
            return (Criteria) this;
        }

        public Criteria andVcStepNotBetween(Integer value1, Integer value2) {
            addCriterion("vc_step not between", value1, value2, "vcStep");
            return (Criteria) this;
        }

        public Criteria andVcVodIsNull() {
            addCriterion("vc_vod is null");
            return (Criteria) this;
        }

        public Criteria andVcVodIsNotNull() {
            addCriterion("vc_vod is not null");
            return (Criteria) this;
        }

        public Criteria andVcVodEqualTo(Integer value) {
            addCriterion("vc_vod =", value, "vcVod");
            return (Criteria) this;
        }

        public Criteria andVcVodNotEqualTo(Integer value) {
            addCriterion("vc_vod <>", value, "vcVod");
            return (Criteria) this;
        }

        public Criteria andVcVodGreaterThan(Integer value) {
            addCriterion("vc_vod >", value, "vcVod");
            return (Criteria) this;
        }

        public Criteria andVcVodGreaterThanOrEqualTo(Integer value) {
            addCriterion("vc_vod >=", value, "vcVod");
            return (Criteria) this;
        }

        public Criteria andVcVodLessThan(Integer value) {
            addCriterion("vc_vod <", value, "vcVod");
            return (Criteria) this;
        }

        public Criteria andVcVodLessThanOrEqualTo(Integer value) {
            addCriterion("vc_vod <=", value, "vcVod");
            return (Criteria) this;
        }

        public Criteria andVcVodIn(List<Integer> values) {
            addCriterion("vc_vod in", values, "vcVod");
            return (Criteria) this;
        }

        public Criteria andVcVodNotIn(List<Integer> values) {
            addCriterion("vc_vod not in", values, "vcVod");
            return (Criteria) this;
        }

        public Criteria andVcVodBetween(Integer value1, Integer value2) {
            addCriterion("vc_vod between", value1, value2, "vcVod");
            return (Criteria) this;
        }

        public Criteria andVcVodNotBetween(Integer value1, Integer value2) {
            addCriterion("vc_vod not between", value1, value2, "vcVod");
            return (Criteria) this;
        }

        public Criteria andVcCostIsNull() {
            addCriterion("vc_cost is null");
            return (Criteria) this;
        }

        public Criteria andVcCostIsNotNull() {
            addCriterion("vc_cost is not null");
            return (Criteria) this;
        }

        public Criteria andVcCostEqualTo(Short value) {
            addCriterion("vc_cost =", value, "vcCost");
            return (Criteria) this;
        }

        public Criteria andVcCostNotEqualTo(Short value) {
            addCriterion("vc_cost <>", value, "vcCost");
            return (Criteria) this;
        }

        public Criteria andVcCostGreaterThan(Short value) {
            addCriterion("vc_cost >", value, "vcCost");
            return (Criteria) this;
        }

        public Criteria andVcCostGreaterThanOrEqualTo(Short value) {
            addCriterion("vc_cost >=", value, "vcCost");
            return (Criteria) this;
        }

        public Criteria andVcCostLessThan(Short value) {
            addCriterion("vc_cost <", value, "vcCost");
            return (Criteria) this;
        }

        public Criteria andVcCostLessThanOrEqualTo(Short value) {
            addCriterion("vc_cost <=", value, "vcCost");
            return (Criteria) this;
        }

        public Criteria andVcCostIn(List<Short> values) {
            addCriterion("vc_cost in", values, "vcCost");
            return (Criteria) this;
        }

        public Criteria andVcCostNotIn(List<Short> values) {
            addCriterion("vc_cost not in", values, "vcCost");
            return (Criteria) this;
        }

        public Criteria andVcCostBetween(Short value1, Short value2) {
            addCriterion("vc_cost between", value1, value2, "vcCost");
            return (Criteria) this;
        }

        public Criteria andVcCostNotBetween(Short value1, Short value2) {
            addCriterion("vc_cost not between", value1, value2, "vcCost");
            return (Criteria) this;
        }

        public Criteria andVcDetailurlIsNull() {
            addCriterion("vc_detailurl is null");
            return (Criteria) this;
        }

        public Criteria andVcDetailurlIsNotNull() {
            addCriterion("vc_detailurl is not null");
            return (Criteria) this;
        }

        public Criteria andVcDetailurlEqualTo(String value) {
            addCriterion("vc_detailurl =", value, "vcDetailurl");
            return (Criteria) this;
        }

        public Criteria andVcDetailurlNotEqualTo(String value) {
            addCriterion("vc_detailurl <>", value, "vcDetailurl");
            return (Criteria) this;
        }

        public Criteria andVcDetailurlGreaterThan(String value) {
            addCriterion("vc_detailurl >", value, "vcDetailurl");
            return (Criteria) this;
        }

        public Criteria andVcDetailurlGreaterThanOrEqualTo(String value) {
            addCriterion("vc_detailurl >=", value, "vcDetailurl");
            return (Criteria) this;
        }

        public Criteria andVcDetailurlLessThan(String value) {
            addCriterion("vc_detailurl <", value, "vcDetailurl");
            return (Criteria) this;
        }

        public Criteria andVcDetailurlLessThanOrEqualTo(String value) {
            addCriterion("vc_detailurl <=", value, "vcDetailurl");
            return (Criteria) this;
        }

        public Criteria andVcDetailurlLike(String value) {
            addCriterion("vc_detailurl like", value, "vcDetailurl");
            return (Criteria) this;
        }

        public Criteria andVcDetailurlNotLike(String value) {
            addCriterion("vc_detailurl not like", value, "vcDetailurl");
            return (Criteria) this;
        }

        public Criteria andVcDetailurlIn(List<String> values) {
            addCriterion("vc_detailurl in", values, "vcDetailurl");
            return (Criteria) this;
        }

        public Criteria andVcDetailurlNotIn(List<String> values) {
            addCriterion("vc_detailurl not in", values, "vcDetailurl");
            return (Criteria) this;
        }

        public Criteria andVcDetailurlBetween(String value1, String value2) {
            addCriterion("vc_detailurl between", value1, value2, "vcDetailurl");
            return (Criteria) this;
        }

        public Criteria andVcDetailurlNotBetween(String value1, String value2) {
            addCriterion("vc_detailurl not between", value1, value2, "vcDetailurl");
            return (Criteria) this;
        }

        public Criteria andVcOrilastIsNull() {
            addCriterion("vc_orilast is null");
            return (Criteria) this;
        }

        public Criteria andVcOrilastIsNotNull() {
            addCriterion("vc_orilast is not null");
            return (Criteria) this;
        }

        public Criteria andVcOrilastEqualTo(Integer value) {
            addCriterion("vc_orilast =", value, "vcOrilast");
            return (Criteria) this;
        }

        public Criteria andVcOrilastNotEqualTo(Integer value) {
            addCriterion("vc_orilast <>", value, "vcOrilast");
            return (Criteria) this;
        }

        public Criteria andVcOrilastGreaterThan(Integer value) {
            addCriterion("vc_orilast >", value, "vcOrilast");
            return (Criteria) this;
        }

        public Criteria andVcOrilastGreaterThanOrEqualTo(Integer value) {
            addCriterion("vc_orilast >=", value, "vcOrilast");
            return (Criteria) this;
        }

        public Criteria andVcOrilastLessThan(Integer value) {
            addCriterion("vc_orilast <", value, "vcOrilast");
            return (Criteria) this;
        }

        public Criteria andVcOrilastLessThanOrEqualTo(Integer value) {
            addCriterion("vc_orilast <=", value, "vcOrilast");
            return (Criteria) this;
        }

        public Criteria andVcOrilastIn(List<Integer> values) {
            addCriterion("vc_orilast in", values, "vcOrilast");
            return (Criteria) this;
        }

        public Criteria andVcOrilastNotIn(List<Integer> values) {
            addCriterion("vc_orilast not in", values, "vcOrilast");
            return (Criteria) this;
        }

        public Criteria andVcOrilastBetween(Integer value1, Integer value2) {
            addCriterion("vc_orilast between", value1, value2, "vcOrilast");
            return (Criteria) this;
        }

        public Criteria andVcOrilastNotBetween(Integer value1, Integer value2) {
            addCriterion("vc_orilast not between", value1, value2, "vcOrilast");
            return (Criteria) this;
        }

        public Criteria andVcOrihotIsNull() {
            addCriterion("vc_orihot is null");
            return (Criteria) this;
        }

        public Criteria andVcOrihotIsNotNull() {
            addCriterion("vc_orihot is not null");
            return (Criteria) this;
        }

        public Criteria andVcOrihotEqualTo(Integer value) {
            addCriterion("vc_orihot =", value, "vcOrihot");
            return (Criteria) this;
        }

        public Criteria andVcOrihotNotEqualTo(Integer value) {
            addCriterion("vc_orihot <>", value, "vcOrihot");
            return (Criteria) this;
        }

        public Criteria andVcOrihotGreaterThan(Integer value) {
            addCriterion("vc_orihot >", value, "vcOrihot");
            return (Criteria) this;
        }

        public Criteria andVcOrihotGreaterThanOrEqualTo(Integer value) {
            addCriterion("vc_orihot >=", value, "vcOrihot");
            return (Criteria) this;
        }

        public Criteria andVcOrihotLessThan(Integer value) {
            addCriterion("vc_orihot <", value, "vcOrihot");
            return (Criteria) this;
        }

        public Criteria andVcOrihotLessThanOrEqualTo(Integer value) {
            addCriterion("vc_orihot <=", value, "vcOrihot");
            return (Criteria) this;
        }

        public Criteria andVcOrihotIn(List<Integer> values) {
            addCriterion("vc_orihot in", values, "vcOrihot");
            return (Criteria) this;
        }

        public Criteria andVcOrihotNotIn(List<Integer> values) {
            addCriterion("vc_orihot not in", values, "vcOrihot");
            return (Criteria) this;
        }

        public Criteria andVcOrihotBetween(Integer value1, Integer value2) {
            addCriterion("vc_orihot between", value1, value2, "vcOrihot");
            return (Criteria) this;
        }

        public Criteria andVcOrihotNotBetween(Integer value1, Integer value2) {
            addCriterion("vc_orihot not between", value1, value2, "vcOrihot");
            return (Criteria) this;
        }

        public Criteria andVcOrihotfavorIsNull() {
            addCriterion("vc_orihotfavor is null");
            return (Criteria) this;
        }

        public Criteria andVcOrihotfavorIsNotNull() {
            addCriterion("vc_orihotfavor is not null");
            return (Criteria) this;
        }

        public Criteria andVcOrihotfavorEqualTo(Integer value) {
            addCriterion("vc_orihotfavor =", value, "vcOrihotfavor");
            return (Criteria) this;
        }

        public Criteria andVcOrihotfavorNotEqualTo(Integer value) {
            addCriterion("vc_orihotfavor <>", value, "vcOrihotfavor");
            return (Criteria) this;
        }

        public Criteria andVcOrihotfavorGreaterThan(Integer value) {
            addCriterion("vc_orihotfavor >", value, "vcOrihotfavor");
            return (Criteria) this;
        }

        public Criteria andVcOrihotfavorGreaterThanOrEqualTo(Integer value) {
            addCriterion("vc_orihotfavor >=", value, "vcOrihotfavor");
            return (Criteria) this;
        }

        public Criteria andVcOrihotfavorLessThan(Integer value) {
            addCriterion("vc_orihotfavor <", value, "vcOrihotfavor");
            return (Criteria) this;
        }

        public Criteria andVcOrihotfavorLessThanOrEqualTo(Integer value) {
            addCriterion("vc_orihotfavor <=", value, "vcOrihotfavor");
            return (Criteria) this;
        }

        public Criteria andVcOrihotfavorIn(List<Integer> values) {
            addCriterion("vc_orihotfavor in", values, "vcOrihotfavor");
            return (Criteria) this;
        }

        public Criteria andVcOrihotfavorNotIn(List<Integer> values) {
            addCriterion("vc_orihotfavor not in", values, "vcOrihotfavor");
            return (Criteria) this;
        }

        public Criteria andVcOrihotfavorBetween(Integer value1, Integer value2) {
            addCriterion("vc_orihotfavor between", value1, value2, "vcOrihotfavor");
            return (Criteria) this;
        }

        public Criteria andVcOrihotfavorNotBetween(Integer value1, Integer value2) {
            addCriterion("vc_orihotfavor not between", value1, value2, "vcOrihotfavor");
            return (Criteria) this;
        }

        public Criteria andVcOrisearchIsNull() {
            addCriterion("vc_orisearch is null");
            return (Criteria) this;
        }

        public Criteria andVcOrisearchIsNotNull() {
            addCriterion("vc_orisearch is not null");
            return (Criteria) this;
        }

        public Criteria andVcOrisearchEqualTo(Integer value) {
            addCriterion("vc_orisearch =", value, "vcOrisearch");
            return (Criteria) this;
        }

        public Criteria andVcOrisearchNotEqualTo(Integer value) {
            addCriterion("vc_orisearch <>", value, "vcOrisearch");
            return (Criteria) this;
        }

        public Criteria andVcOrisearchGreaterThan(Integer value) {
            addCriterion("vc_orisearch >", value, "vcOrisearch");
            return (Criteria) this;
        }

        public Criteria andVcOrisearchGreaterThanOrEqualTo(Integer value) {
            addCriterion("vc_orisearch >=", value, "vcOrisearch");
            return (Criteria) this;
        }

        public Criteria andVcOrisearchLessThan(Integer value) {
            addCriterion("vc_orisearch <", value, "vcOrisearch");
            return (Criteria) this;
        }

        public Criteria andVcOrisearchLessThanOrEqualTo(Integer value) {
            addCriterion("vc_orisearch <=", value, "vcOrisearch");
            return (Criteria) this;
        }

        public Criteria andVcOrisearchIn(List<Integer> values) {
            addCriterion("vc_orisearch in", values, "vcOrisearch");
            return (Criteria) this;
        }

        public Criteria andVcOrisearchNotIn(List<Integer> values) {
            addCriterion("vc_orisearch not in", values, "vcOrisearch");
            return (Criteria) this;
        }

        public Criteria andVcOrisearchBetween(Integer value1, Integer value2) {
            addCriterion("vc_orisearch between", value1, value2, "vcOrisearch");
            return (Criteria) this;
        }

        public Criteria andVcOrisearchNotBetween(Integer value1, Integer value2) {
            addCriterion("vc_orisearch not between", value1, value2, "vcOrisearch");
            return (Criteria) this;
        }

        public Criteria andVcCrawldateIsNull() {
            addCriterion("vc_crawldate is null");
            return (Criteria) this;
        }

        public Criteria andVcCrawldateIsNotNull() {
            addCriterion("vc_crawldate is not null");
            return (Criteria) this;
        }

        public Criteria andVcCrawldateEqualTo(Date value) {
            addCriterionForJDBCDate("vc_crawldate =", value, "vcCrawldate");
            return (Criteria) this;
        }

        public Criteria andVcCrawldateNotEqualTo(Date value) {
            addCriterionForJDBCDate("vc_crawldate <>", value, "vcCrawldate");
            return (Criteria) this;
        }

        public Criteria andVcCrawldateGreaterThan(Date value) {
            addCriterionForJDBCDate("vc_crawldate >", value, "vcCrawldate");
            return (Criteria) this;
        }

        public Criteria andVcCrawldateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("vc_crawldate >=", value, "vcCrawldate");
            return (Criteria) this;
        }

        public Criteria andVcCrawldateLessThan(Date value) {
            addCriterionForJDBCDate("vc_crawldate <", value, "vcCrawldate");
            return (Criteria) this;
        }

        public Criteria andVcCrawldateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("vc_crawldate <=", value, "vcCrawldate");
            return (Criteria) this;
        }

        public Criteria andVcCrawldateIn(List<Date> values) {
            addCriterionForJDBCDate("vc_crawldate in", values, "vcCrawldate");
            return (Criteria) this;
        }

        public Criteria andVcCrawldateNotIn(List<Date> values) {
            addCriterionForJDBCDate("vc_crawldate not in", values, "vcCrawldate");
            return (Criteria) this;
        }

        public Criteria andVcCrawldateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("vc_crawldate between", value1, value2, "vcCrawldate");
            return (Criteria) this;
        }

        public Criteria andVcCrawldateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("vc_crawldate not between", value1, value2, "vcCrawldate");
            return (Criteria) this;
        }

        public Criteria andVcReserved0IsNull() {
            addCriterion("vc_reserved_0 is null");
            return (Criteria) this;
        }

        public Criteria andVcReserved0IsNotNull() {
            addCriterion("vc_reserved_0 is not null");
            return (Criteria) this;
        }

        public Criteria andVcReserved0EqualTo(String value) {
            addCriterion("vc_reserved_0 =", value, "vcReserved0");
            return (Criteria) this;
        }

        public Criteria andVcReserved0NotEqualTo(String value) {
            addCriterion("vc_reserved_0 <>", value, "vcReserved0");
            return (Criteria) this;
        }

        public Criteria andVcReserved0GreaterThan(String value) {
            addCriterion("vc_reserved_0 >", value, "vcReserved0");
            return (Criteria) this;
        }

        public Criteria andVcReserved0GreaterThanOrEqualTo(String value) {
            addCriterion("vc_reserved_0 >=", value, "vcReserved0");
            return (Criteria) this;
        }

        public Criteria andVcReserved0LessThan(String value) {
            addCriterion("vc_reserved_0 <", value, "vcReserved0");
            return (Criteria) this;
        }

        public Criteria andVcReserved0LessThanOrEqualTo(String value) {
            addCriterion("vc_reserved_0 <=", value, "vcReserved0");
            return (Criteria) this;
        }

        public Criteria andVcReserved0Like(String value) {
            addCriterion("vc_reserved_0 like", value, "vcReserved0");
            return (Criteria) this;
        }

        public Criteria andVcReserved0NotLike(String value) {
            addCriterion("vc_reserved_0 not like", value, "vcReserved0");
            return (Criteria) this;
        }

        public Criteria andVcReserved0In(List<String> values) {
            addCriterion("vc_reserved_0 in", values, "vcReserved0");
            return (Criteria) this;
        }

        public Criteria andVcReserved0NotIn(List<String> values) {
            addCriterion("vc_reserved_0 not in", values, "vcReserved0");
            return (Criteria) this;
        }

        public Criteria andVcReserved0Between(String value1, String value2) {
            addCriterion("vc_reserved_0 between", value1, value2, "vcReserved0");
            return (Criteria) this;
        }

        public Criteria andVcReserved0NotBetween(String value1, String value2) {
            addCriterion("vc_reserved_0 not between", value1, value2, "vcReserved0");
            return (Criteria) this;
        }

        public Criteria andVcReserved1IsNull() {
            addCriterion("vc_reserved_1 is null");
            return (Criteria) this;
        }

        public Criteria andVcReserved1IsNotNull() {
            addCriterion("vc_reserved_1 is not null");
            return (Criteria) this;
        }

        public Criteria andVcReserved1EqualTo(String value) {
            addCriterion("vc_reserved_1 =", value, "vcReserved1");
            return (Criteria) this;
        }

        public Criteria andVcReserved1NotEqualTo(String value) {
            addCriterion("vc_reserved_1 <>", value, "vcReserved1");
            return (Criteria) this;
        }

        public Criteria andVcReserved1GreaterThan(String value) {
            addCriterion("vc_reserved_1 >", value, "vcReserved1");
            return (Criteria) this;
        }

        public Criteria andVcReserved1GreaterThanOrEqualTo(String value) {
            addCriterion("vc_reserved_1 >=", value, "vcReserved1");
            return (Criteria) this;
        }

        public Criteria andVcReserved1LessThan(String value) {
            addCriterion("vc_reserved_1 <", value, "vcReserved1");
            return (Criteria) this;
        }

        public Criteria andVcReserved1LessThanOrEqualTo(String value) {
            addCriterion("vc_reserved_1 <=", value, "vcReserved1");
            return (Criteria) this;
        }

        public Criteria andVcReserved1Like(String value) {
            addCriterion("vc_reserved_1 like", value, "vcReserved1");
            return (Criteria) this;
        }

        public Criteria andVcReserved1NotLike(String value) {
            addCriterion("vc_reserved_1 not like", value, "vcReserved1");
            return (Criteria) this;
        }

        public Criteria andVcReserved1In(List<String> values) {
            addCriterion("vc_reserved_1 in", values, "vcReserved1");
            return (Criteria) this;
        }

        public Criteria andVcReserved1NotIn(List<String> values) {
            addCriterion("vc_reserved_1 not in", values, "vcReserved1");
            return (Criteria) this;
        }

        public Criteria andVcReserved1Between(String value1, String value2) {
            addCriterion("vc_reserved_1 between", value1, value2, "vcReserved1");
            return (Criteria) this;
        }

        public Criteria andVcReserved1NotBetween(String value1, String value2) {
            addCriterion("vc_reserved_1 not between", value1, value2, "vcReserved1");
            return (Criteria) this;
        }

        public Criteria andVcReserved2IsNull() {
            addCriterion("vc_reserved_2 is null");
            return (Criteria) this;
        }

        public Criteria andVcReserved2IsNotNull() {
            addCriterion("vc_reserved_2 is not null");
            return (Criteria) this;
        }

        public Criteria andVcReserved2EqualTo(String value) {
            addCriterion("vc_reserved_2 =", value, "vcReserved2");
            return (Criteria) this;
        }

        public Criteria andVcReserved2NotEqualTo(String value) {
            addCriterion("vc_reserved_2 <>", value, "vcReserved2");
            return (Criteria) this;
        }

        public Criteria andVcReserved2GreaterThan(String value) {
            addCriterion("vc_reserved_2 >", value, "vcReserved2");
            return (Criteria) this;
        }

        public Criteria andVcReserved2GreaterThanOrEqualTo(String value) {
            addCriterion("vc_reserved_2 >=", value, "vcReserved2");
            return (Criteria) this;
        }

        public Criteria andVcReserved2LessThan(String value) {
            addCriterion("vc_reserved_2 <", value, "vcReserved2");
            return (Criteria) this;
        }

        public Criteria andVcReserved2LessThanOrEqualTo(String value) {
            addCriterion("vc_reserved_2 <=", value, "vcReserved2");
            return (Criteria) this;
        }

        public Criteria andVcReserved2Like(String value) {
            addCriterion("vc_reserved_2 like", value, "vcReserved2");
            return (Criteria) this;
        }

        public Criteria andVcReserved2NotLike(String value) {
            addCriterion("vc_reserved_2 not like", value, "vcReserved2");
            return (Criteria) this;
        }

        public Criteria andVcReserved2In(List<String> values) {
            addCriterion("vc_reserved_2 in", values, "vcReserved2");
            return (Criteria) this;
        }

        public Criteria andVcReserved2NotIn(List<String> values) {
            addCriterion("vc_reserved_2 not in", values, "vcReserved2");
            return (Criteria) this;
        }

        public Criteria andVcReserved2Between(String value1, String value2) {
            addCriterion("vc_reserved_2 between", value1, value2, "vcReserved2");
            return (Criteria) this;
        }

        public Criteria andVcReserved2NotBetween(String value1, String value2) {
            addCriterion("vc_reserved_2 not between", value1, value2, "vcReserved2");
            return (Criteria) this;
        }

        public Criteria andVcReserved3IsNull() {
            addCriterion("vc_reserved_3 is null");
            return (Criteria) this;
        }

        public Criteria andVcReserved3IsNotNull() {
            addCriterion("vc_reserved_3 is not null");
            return (Criteria) this;
        }

        public Criteria andVcReserved3EqualTo(String value) {
            addCriterion("vc_reserved_3 =", value, "vcReserved3");
            return (Criteria) this;
        }

        public Criteria andVcReserved3NotEqualTo(String value) {
            addCriterion("vc_reserved_3 <>", value, "vcReserved3");
            return (Criteria) this;
        }

        public Criteria andVcReserved3GreaterThan(String value) {
            addCriterion("vc_reserved_3 >", value, "vcReserved3");
            return (Criteria) this;
        }

        public Criteria andVcReserved3GreaterThanOrEqualTo(String value) {
            addCriterion("vc_reserved_3 >=", value, "vcReserved3");
            return (Criteria) this;
        }

        public Criteria andVcReserved3LessThan(String value) {
            addCriterion("vc_reserved_3 <", value, "vcReserved3");
            return (Criteria) this;
        }

        public Criteria andVcReserved3LessThanOrEqualTo(String value) {
            addCriterion("vc_reserved_3 <=", value, "vcReserved3");
            return (Criteria) this;
        }

        public Criteria andVcReserved3Like(String value) {
            addCriterion("vc_reserved_3 like", value, "vcReserved3");
            return (Criteria) this;
        }

        public Criteria andVcReserved3NotLike(String value) {
            addCriterion("vc_reserved_3 not like", value, "vcReserved3");
            return (Criteria) this;
        }

        public Criteria andVcReserved3In(List<String> values) {
            addCriterion("vc_reserved_3 in", values, "vcReserved3");
            return (Criteria) this;
        }

        public Criteria andVcReserved3NotIn(List<String> values) {
            addCriterion("vc_reserved_3 not in", values, "vcReserved3");
            return (Criteria) this;
        }

        public Criteria andVcReserved3Between(String value1, String value2) {
            addCriterion("vc_reserved_3 between", value1, value2, "vcReserved3");
            return (Criteria) this;
        }

        public Criteria andVcReserved3NotBetween(String value1, String value2) {
            addCriterion("vc_reserved_3 not between", value1, value2, "vcReserved3");
            return (Criteria) this;
        }

        public Criteria andCsIdIsNull() {
            addCriterion("cs_id is null");
            return (Criteria) this;
        }

        public Criteria andCsIdIsNotNull() {
            addCriterion("cs_id is not null");
            return (Criteria) this;
        }

        public Criteria andCsIdEqualTo(Short value) {
            addCriterion("cs_id =", value, "csId");
            return (Criteria) this;
        }

        public Criteria andCsIdNotEqualTo(Short value) {
            addCriterion("cs_id <>", value, "csId");
            return (Criteria) this;
        }

        public Criteria andCsIdGreaterThan(Short value) {
            addCriterion("cs_id >", value, "csId");
            return (Criteria) this;
        }

        public Criteria andCsIdGreaterThanOrEqualTo(Short value) {
            addCriterion("cs_id >=", value, "csId");
            return (Criteria) this;
        }

        public Criteria andCsIdLessThan(Short value) {
            addCriterion("cs_id <", value, "csId");
            return (Criteria) this;
        }

        public Criteria andCsIdLessThanOrEqualTo(Short value) {
            addCriterion("cs_id <=", value, "csId");
            return (Criteria) this;
        }

        public Criteria andCsIdIn(List<Short> values) {
            addCriterion("cs_id in", values, "csId");
            return (Criteria) this;
        }

        public Criteria andCsIdNotIn(List<Short> values) {
            addCriterion("cs_id not in", values, "csId");
            return (Criteria) this;
        }

        public Criteria andCsIdBetween(Short value1, Short value2) {
            addCriterion("cs_id between", value1, value2, "csId");
            return (Criteria) this;
        }

        public Criteria andCsIdNotBetween(Short value1, Short value2) {
            addCriterion("cs_id not between", value1, value2, "csId");
            return (Criteria) this;
        }

        public Criteria andVbIdIsNull() {
            addCriterion("vb_id is null");
            return (Criteria) this;
        }

        public Criteria andVbIdIsNotNull() {
            addCriterion("vb_id is not null");
            return (Criteria) this;
        }

        public Criteria andVbIdEqualTo(Integer value) {
            addCriterion("vb_id =", value, "vbId");
            return (Criteria) this;
        }

        public Criteria andVbIdNotEqualTo(Integer value) {
            addCriterion("vb_id <>", value, "vbId");
            return (Criteria) this;
        }

        public Criteria andVbIdGreaterThan(Integer value) {
            addCriterion("vb_id >", value, "vbId");
            return (Criteria) this;
        }

        public Criteria andVbIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("vb_id >=", value, "vbId");
            return (Criteria) this;
        }

        public Criteria andVbIdLessThan(Integer value) {
            addCriterion("vb_id <", value, "vbId");
            return (Criteria) this;
        }

        public Criteria andVbIdLessThanOrEqualTo(Integer value) {
            addCriterion("vb_id <=", value, "vbId");
            return (Criteria) this;
        }

        public Criteria andVbIdIn(List<Integer> values) {
            addCriterion("vb_id in", values, "vbId");
            return (Criteria) this;
        }

        public Criteria andVbIdNotIn(List<Integer> values) {
            addCriterion("vb_id not in", values, "vbId");
            return (Criteria) this;
        }

        public Criteria andVbIdBetween(Integer value1, Integer value2) {
            addCriterion("vb_id between", value1, value2, "vbId");
            return (Criteria) this;
        }

        public Criteria andVbIdNotBetween(Integer value1, Integer value2) {
            addCriterion("vb_id not between", value1, value2, "vbId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table video_crawlinfo_tbl
     *
     * @mbggenerated do_not_delete_during_merge Wed Jan 23 17:42:39 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table video_crawlinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}