package org.apache.nutch.parse.html.video.database.model;

import java.util.ArrayList;
import java.util.List;

public class VideoBaseinfoTblExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table video_baseinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table video_baseinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table video_baseinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_baseinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public VideoBaseinfoTblExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_baseinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_baseinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_baseinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_baseinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_baseinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_baseinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_baseinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_baseinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_baseinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_baseinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table video_baseinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andVbIdIsNull() {
            addCriterion("vb_id is null");
            return (Criteria) this;
        }

        public Criteria andVbIdIsNotNull() {
            addCriterion("vb_id is not null");
            return (Criteria) this;
        }

        public Criteria andVbIdEqualTo(Integer value) {
            addCriterion("vb_id =", value, "vbId");
            return (Criteria) this;
        }

        public Criteria andVbIdNotEqualTo(Integer value) {
            addCriterion("vb_id <>", value, "vbId");
            return (Criteria) this;
        }

        public Criteria andVbIdGreaterThan(Integer value) {
            addCriterion("vb_id >", value, "vbId");
            return (Criteria) this;
        }

        public Criteria andVbIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("vb_id >=", value, "vbId");
            return (Criteria) this;
        }

        public Criteria andVbIdLessThan(Integer value) {
            addCriterion("vb_id <", value, "vbId");
            return (Criteria) this;
        }

        public Criteria andVbIdLessThanOrEqualTo(Integer value) {
            addCriterion("vb_id <=", value, "vbId");
            return (Criteria) this;
        }

        public Criteria andVbIdIn(List<Integer> values) {
            addCriterion("vb_id in", values, "vbId");
            return (Criteria) this;
        }

        public Criteria andVbIdNotIn(List<Integer> values) {
            addCriterion("vb_id not in", values, "vbId");
            return (Criteria) this;
        }

        public Criteria andVbIdBetween(Integer value1, Integer value2) {
            addCriterion("vb_id between", value1, value2, "vbId");
            return (Criteria) this;
        }

        public Criteria andVbIdNotBetween(Integer value1, Integer value2) {
            addCriterion("vb_id not between", value1, value2, "vbId");
            return (Criteria) this;
        }

        public Criteria andVbNameIsNull() {
            addCriterion("vb_name is null");
            return (Criteria) this;
        }

        public Criteria andVbNameIsNotNull() {
            addCriterion("vb_name is not null");
            return (Criteria) this;
        }

        public Criteria andVbNameEqualTo(String value) {
            addCriterion("vb_name =", value, "vbName");
            return (Criteria) this;
        }

        public Criteria andVbNameNotEqualTo(String value) {
            addCriterion("vb_name <>", value, "vbName");
            return (Criteria) this;
        }

        public Criteria andVbNameGreaterThan(String value) {
            addCriterion("vb_name >", value, "vbName");
            return (Criteria) this;
        }

        public Criteria andVbNameGreaterThanOrEqualTo(String value) {
            addCriterion("vb_name >=", value, "vbName");
            return (Criteria) this;
        }

        public Criteria andVbNameLessThan(String value) {
            addCriterion("vb_name <", value, "vbName");
            return (Criteria) this;
        }

        public Criteria andVbNameLessThanOrEqualTo(String value) {
            addCriterion("vb_name <=", value, "vbName");
            return (Criteria) this;
        }

        public Criteria andVbNameLike(String value) {
            addCriterion("vb_name like", value, "vbName");
            return (Criteria) this;
        }

        public Criteria andVbNameNotLike(String value) {
            addCriterion("vb_name not like", value, "vbName");
            return (Criteria) this;
        }

        public Criteria andVbNameIn(List<String> values) {
            addCriterion("vb_name in", values, "vbName");
            return (Criteria) this;
        }

        public Criteria andVbNameNotIn(List<String> values) {
            addCriterion("vb_name not in", values, "vbName");
            return (Criteria) this;
        }

        public Criteria andVbNameBetween(String value1, String value2) {
            addCriterion("vb_name between", value1, value2, "vbName");
            return (Criteria) this;
        }

        public Criteria andVbNameNotBetween(String value1, String value2) {
            addCriterion("vb_name not between", value1, value2, "vbName");
            return (Criteria) this;
        }

        public Criteria andVbAliasIsNull() {
            addCriterion("vb_alias is null");
            return (Criteria) this;
        }

        public Criteria andVbAliasIsNotNull() {
            addCriterion("vb_alias is not null");
            return (Criteria) this;
        }

        public Criteria andVbAliasEqualTo(String value) {
            addCriterion("vb_alias =", value, "vbAlias");
            return (Criteria) this;
        }

        public Criteria andVbAliasNotEqualTo(String value) {
            addCriterion("vb_alias <>", value, "vbAlias");
            return (Criteria) this;
        }

        public Criteria andVbAliasGreaterThan(String value) {
            addCriterion("vb_alias >", value, "vbAlias");
            return (Criteria) this;
        }

        public Criteria andVbAliasGreaterThanOrEqualTo(String value) {
            addCriterion("vb_alias >=", value, "vbAlias");
            return (Criteria) this;
        }

        public Criteria andVbAliasLessThan(String value) {
            addCriterion("vb_alias <", value, "vbAlias");
            return (Criteria) this;
        }

        public Criteria andVbAliasLessThanOrEqualTo(String value) {
            addCriterion("vb_alias <=", value, "vbAlias");
            return (Criteria) this;
        }

        public Criteria andVbAliasLike(String value) {
            addCriterion("vb_alias like", value, "vbAlias");
            return (Criteria) this;
        }

        public Criteria andVbAliasNotLike(String value) {
            addCriterion("vb_alias not like", value, "vbAlias");
            return (Criteria) this;
        }

        public Criteria andVbAliasIn(List<String> values) {
            addCriterion("vb_alias in", values, "vbAlias");
            return (Criteria) this;
        }

        public Criteria andVbAliasNotIn(List<String> values) {
            addCriterion("vb_alias not in", values, "vbAlias");
            return (Criteria) this;
        }

        public Criteria andVbAliasBetween(String value1, String value2) {
            addCriterion("vb_alias between", value1, value2, "vbAlias");
            return (Criteria) this;
        }

        public Criteria andVbAliasNotBetween(String value1, String value2) {
            addCriterion("vb_alias not between", value1, value2, "vbAlias");
            return (Criteria) this;
        }

        public Criteria andVbSpecIsNull() {
            addCriterion("vb_spec is null");
            return (Criteria) this;
        }

        public Criteria andVbSpecIsNotNull() {
            addCriterion("vb_spec is not null");
            return (Criteria) this;
        }

        public Criteria andVbSpecEqualTo(Short value) {
            addCriterion("vb_spec =", value, "vbSpec");
            return (Criteria) this;
        }

        public Criteria andVbSpecNotEqualTo(Short value) {
            addCriterion("vb_spec <>", value, "vbSpec");
            return (Criteria) this;
        }

        public Criteria andVbSpecGreaterThan(Short value) {
            addCriterion("vb_spec >", value, "vbSpec");
            return (Criteria) this;
        }

        public Criteria andVbSpecGreaterThanOrEqualTo(Short value) {
            addCriterion("vb_spec >=", value, "vbSpec");
            return (Criteria) this;
        }

        public Criteria andVbSpecLessThan(Short value) {
            addCriterion("vb_spec <", value, "vbSpec");
            return (Criteria) this;
        }

        public Criteria andVbSpecLessThanOrEqualTo(Short value) {
            addCriterion("vb_spec <=", value, "vbSpec");
            return (Criteria) this;
        }

        public Criteria andVbSpecIn(List<Short> values) {
            addCriterion("vb_spec in", values, "vbSpec");
            return (Criteria) this;
        }

        public Criteria andVbSpecNotIn(List<Short> values) {
            addCriterion("vb_spec not in", values, "vbSpec");
            return (Criteria) this;
        }

        public Criteria andVbSpecBetween(Short value1, Short value2) {
            addCriterion("vb_spec between", value1, value2, "vbSpec");
            return (Criteria) this;
        }

        public Criteria andVbSpecNotBetween(Short value1, Short value2) {
            addCriterion("vb_spec not between", value1, value2, "vbSpec");
            return (Criteria) this;
        }

        public Criteria andVbYearIsNull() {
            addCriterion("vb_year is null");
            return (Criteria) this;
        }

        public Criteria andVbYearIsNotNull() {
            addCriterion("vb_year is not null");
            return (Criteria) this;
        }

        public Criteria andVbYearEqualTo(String value) {
            addCriterion("vb_year =", value, "vbYear");
            return (Criteria) this;
        }

        public Criteria andVbYearNotEqualTo(String value) {
            addCriterion("vb_year <>", value, "vbYear");
            return (Criteria) this;
        }

        public Criteria andVbYearGreaterThan(String value) {
            addCriterion("vb_year >", value, "vbYear");
            return (Criteria) this;
        }

        public Criteria andVbYearGreaterThanOrEqualTo(String value) {
            addCriterion("vb_year >=", value, "vbYear");
            return (Criteria) this;
        }

        public Criteria andVbYearLessThan(String value) {
            addCriterion("vb_year <", value, "vbYear");
            return (Criteria) this;
        }

        public Criteria andVbYearLessThanOrEqualTo(String value) {
            addCriterion("vb_year <=", value, "vbYear");
            return (Criteria) this;
        }

        public Criteria andVbYearLike(String value) {
            addCriterion("vb_year like", value, "vbYear");
            return (Criteria) this;
        }

        public Criteria andVbYearNotLike(String value) {
            addCriterion("vb_year not like", value, "vbYear");
            return (Criteria) this;
        }

        public Criteria andVbYearIn(List<String> values) {
            addCriterion("vb_year in", values, "vbYear");
            return (Criteria) this;
        }

        public Criteria andVbYearNotIn(List<String> values) {
            addCriterion("vb_year not in", values, "vbYear");
            return (Criteria) this;
        }

        public Criteria andVbYearBetween(String value1, String value2) {
            addCriterion("vb_year between", value1, value2, "vbYear");
            return (Criteria) this;
        }

        public Criteria andVbYearNotBetween(String value1, String value2) {
            addCriterion("vb_year not between", value1, value2, "vbYear");
            return (Criteria) this;
        }

        public Criteria andVbDirectorIsNull() {
            addCriterion("vb_director is null");
            return (Criteria) this;
        }

        public Criteria andVbDirectorIsNotNull() {
            addCriterion("vb_director is not null");
            return (Criteria) this;
        }

        public Criteria andVbDirectorEqualTo(String value) {
            addCriterion("vb_director =", value, "vbDirector");
            return (Criteria) this;
        }

        public Criteria andVbDirectorNotEqualTo(String value) {
            addCriterion("vb_director <>", value, "vbDirector");
            return (Criteria) this;
        }

        public Criteria andVbDirectorGreaterThan(String value) {
            addCriterion("vb_director >", value, "vbDirector");
            return (Criteria) this;
        }

        public Criteria andVbDirectorGreaterThanOrEqualTo(String value) {
            addCriterion("vb_director >=", value, "vbDirector");
            return (Criteria) this;
        }

        public Criteria andVbDirectorLessThan(String value) {
            addCriterion("vb_director <", value, "vbDirector");
            return (Criteria) this;
        }

        public Criteria andVbDirectorLessThanOrEqualTo(String value) {
            addCriterion("vb_director <=", value, "vbDirector");
            return (Criteria) this;
        }

        public Criteria andVbDirectorLike(String value) {
            addCriterion("vb_director like", value, "vbDirector");
            return (Criteria) this;
        }

        public Criteria andVbDirectorNotLike(String value) {
            addCriterion("vb_director not like", value, "vbDirector");
            return (Criteria) this;
        }

        public Criteria andVbDirectorIn(List<String> values) {
            addCriterion("vb_director in", values, "vbDirector");
            return (Criteria) this;
        }

        public Criteria andVbDirectorNotIn(List<String> values) {
            addCriterion("vb_director not in", values, "vbDirector");
            return (Criteria) this;
        }

        public Criteria andVbDirectorBetween(String value1, String value2) {
            addCriterion("vb_director between", value1, value2, "vbDirector");
            return (Criteria) this;
        }

        public Criteria andVbDirectorNotBetween(String value1, String value2) {
            addCriterion("vb_director not between", value1, value2, "vbDirector");
            return (Criteria) this;
        }

        public Criteria andVbActorIsNull() {
            addCriterion("vb_actor is null");
            return (Criteria) this;
        }

        public Criteria andVbActorIsNotNull() {
            addCriterion("vb_actor is not null");
            return (Criteria) this;
        }

        public Criteria andVbActorEqualTo(String value) {
            addCriterion("vb_actor =", value, "vbActor");
            return (Criteria) this;
        }

        public Criteria andVbActorNotEqualTo(String value) {
            addCriterion("vb_actor <>", value, "vbActor");
            return (Criteria) this;
        }

        public Criteria andVbActorGreaterThan(String value) {
            addCriterion("vb_actor >", value, "vbActor");
            return (Criteria) this;
        }

        public Criteria andVbActorGreaterThanOrEqualTo(String value) {
            addCriterion("vb_actor >=", value, "vbActor");
            return (Criteria) this;
        }

        public Criteria andVbActorLessThan(String value) {
            addCriterion("vb_actor <", value, "vbActor");
            return (Criteria) this;
        }

        public Criteria andVbActorLessThanOrEqualTo(String value) {
            addCriterion("vb_actor <=", value, "vbActor");
            return (Criteria) this;
        }

        public Criteria andVbActorLike(String value) {
            addCriterion("vb_actor like", value, "vbActor");
            return (Criteria) this;
        }

        public Criteria andVbActorNotLike(String value) {
            addCriterion("vb_actor not like", value, "vbActor");
            return (Criteria) this;
        }

        public Criteria andVbActorIn(List<String> values) {
            addCriterion("vb_actor in", values, "vbActor");
            return (Criteria) this;
        }

        public Criteria andVbActorNotIn(List<String> values) {
            addCriterion("vb_actor not in", values, "vbActor");
            return (Criteria) this;
        }

        public Criteria andVbActorBetween(String value1, String value2) {
            addCriterion("vb_actor between", value1, value2, "vbActor");
            return (Criteria) this;
        }

        public Criteria andVbActorNotBetween(String value1, String value2) {
            addCriterion("vb_actor not between", value1, value2, "vbActor");
            return (Criteria) this;
        }

        public Criteria andVbLabelIsNull() {
            addCriterion("vb_label is null");
            return (Criteria) this;
        }

        public Criteria andVbLabelIsNotNull() {
            addCriterion("vb_label is not null");
            return (Criteria) this;
        }

        public Criteria andVbLabelEqualTo(String value) {
            addCriterion("vb_label =", value, "vbLabel");
            return (Criteria) this;
        }

        public Criteria andVbLabelNotEqualTo(String value) {
            addCriterion("vb_label <>", value, "vbLabel");
            return (Criteria) this;
        }

        public Criteria andVbLabelGreaterThan(String value) {
            addCriterion("vb_label >", value, "vbLabel");
            return (Criteria) this;
        }

        public Criteria andVbLabelGreaterThanOrEqualTo(String value) {
            addCriterion("vb_label >=", value, "vbLabel");
            return (Criteria) this;
        }

        public Criteria andVbLabelLessThan(String value) {
            addCriterion("vb_label <", value, "vbLabel");
            return (Criteria) this;
        }

        public Criteria andVbLabelLessThanOrEqualTo(String value) {
            addCriterion("vb_label <=", value, "vbLabel");
            return (Criteria) this;
        }

        public Criteria andVbLabelLike(String value) {
            addCriterion("vb_label like", value, "vbLabel");
            return (Criteria) this;
        }

        public Criteria andVbLabelNotLike(String value) {
            addCriterion("vb_label not like", value, "vbLabel");
            return (Criteria) this;
        }

        public Criteria andVbLabelIn(List<String> values) {
            addCriterion("vb_label in", values, "vbLabel");
            return (Criteria) this;
        }

        public Criteria andVbLabelNotIn(List<String> values) {
            addCriterion("vb_label not in", values, "vbLabel");
            return (Criteria) this;
        }

        public Criteria andVbLabelBetween(String value1, String value2) {
            addCriterion("vb_label between", value1, value2, "vbLabel");
            return (Criteria) this;
        }

        public Criteria andVbLabelNotBetween(String value1, String value2) {
            addCriterion("vb_label not between", value1, value2, "vbLabel");
            return (Criteria) this;
        }

        public Criteria andVbDurationIsNull() {
            addCriterion("vb_duration is null");
            return (Criteria) this;
        }

        public Criteria andVbDurationIsNotNull() {
            addCriterion("vb_duration is not null");
            return (Criteria) this;
        }

        public Criteria andVbDurationEqualTo(Short value) {
            addCriterion("vb_duration =", value, "vbDuration");
            return (Criteria) this;
        }

        public Criteria andVbDurationNotEqualTo(Short value) {
            addCriterion("vb_duration <>", value, "vbDuration");
            return (Criteria) this;
        }

        public Criteria andVbDurationGreaterThan(Short value) {
            addCriterion("vb_duration >", value, "vbDuration");
            return (Criteria) this;
        }

        public Criteria andVbDurationGreaterThanOrEqualTo(Short value) {
            addCriterion("vb_duration >=", value, "vbDuration");
            return (Criteria) this;
        }

        public Criteria andVbDurationLessThan(Short value) {
            addCriterion("vb_duration <", value, "vbDuration");
            return (Criteria) this;
        }

        public Criteria andVbDurationLessThanOrEqualTo(Short value) {
            addCriterion("vb_duration <=", value, "vbDuration");
            return (Criteria) this;
        }

        public Criteria andVbDurationIn(List<Short> values) {
            addCriterion("vb_duration in", values, "vbDuration");
            return (Criteria) this;
        }

        public Criteria andVbDurationNotIn(List<Short> values) {
            addCriterion("vb_duration not in", values, "vbDuration");
            return (Criteria) this;
        }

        public Criteria andVbDurationBetween(Short value1, Short value2) {
            addCriterion("vb_duration between", value1, value2, "vbDuration");
            return (Criteria) this;
        }

        public Criteria andVbDurationNotBetween(Short value1, Short value2) {
            addCriterion("vb_duration not between", value1, value2, "vbDuration");
            return (Criteria) this;
        }

        public Criteria andVbLanguageIsNull() {
            addCriterion("vb_language is null");
            return (Criteria) this;
        }

        public Criteria andVbLanguageIsNotNull() {
            addCriterion("vb_language is not null");
            return (Criteria) this;
        }

        public Criteria andVbLanguageEqualTo(String value) {
            addCriterion("vb_language =", value, "vbLanguage");
            return (Criteria) this;
        }

        public Criteria andVbLanguageNotEqualTo(String value) {
            addCriterion("vb_language <>", value, "vbLanguage");
            return (Criteria) this;
        }

        public Criteria andVbLanguageGreaterThan(String value) {
            addCriterion("vb_language >", value, "vbLanguage");
            return (Criteria) this;
        }

        public Criteria andVbLanguageGreaterThanOrEqualTo(String value) {
            addCriterion("vb_language >=", value, "vbLanguage");
            return (Criteria) this;
        }

        public Criteria andVbLanguageLessThan(String value) {
            addCriterion("vb_language <", value, "vbLanguage");
            return (Criteria) this;
        }

        public Criteria andVbLanguageLessThanOrEqualTo(String value) {
            addCriterion("vb_language <=", value, "vbLanguage");
            return (Criteria) this;
        }

        public Criteria andVbLanguageLike(String value) {
            addCriterion("vb_language like", value, "vbLanguage");
            return (Criteria) this;
        }

        public Criteria andVbLanguageNotLike(String value) {
            addCriterion("vb_language not like", value, "vbLanguage");
            return (Criteria) this;
        }

        public Criteria andVbLanguageIn(List<String> values) {
            addCriterion("vb_language in", values, "vbLanguage");
            return (Criteria) this;
        }

        public Criteria andVbLanguageNotIn(List<String> values) {
            addCriterion("vb_language not in", values, "vbLanguage");
            return (Criteria) this;
        }

        public Criteria andVbLanguageBetween(String value1, String value2) {
            addCriterion("vb_language between", value1, value2, "vbLanguage");
            return (Criteria) this;
        }

        public Criteria andVbLanguageNotBetween(String value1, String value2) {
            addCriterion("vb_language not between", value1, value2, "vbLanguage");
            return (Criteria) this;
        }

        public Criteria andVbSimpledescIsNull() {
            addCriterion("vb_simpledesc is null");
            return (Criteria) this;
        }

        public Criteria andVbSimpledescIsNotNull() {
            addCriterion("vb_simpledesc is not null");
            return (Criteria) this;
        }

        public Criteria andVbSimpledescEqualTo(String value) {
            addCriterion("vb_simpledesc =", value, "vbSimpledesc");
            return (Criteria) this;
        }

        public Criteria andVbSimpledescNotEqualTo(String value) {
            addCriterion("vb_simpledesc <>", value, "vbSimpledesc");
            return (Criteria) this;
        }

        public Criteria andVbSimpledescGreaterThan(String value) {
            addCriterion("vb_simpledesc >", value, "vbSimpledesc");
            return (Criteria) this;
        }

        public Criteria andVbSimpledescGreaterThanOrEqualTo(String value) {
            addCriterion("vb_simpledesc >=", value, "vbSimpledesc");
            return (Criteria) this;
        }

        public Criteria andVbSimpledescLessThan(String value) {
            addCriterion("vb_simpledesc <", value, "vbSimpledesc");
            return (Criteria) this;
        }

        public Criteria andVbSimpledescLessThanOrEqualTo(String value) {
            addCriterion("vb_simpledesc <=", value, "vbSimpledesc");
            return (Criteria) this;
        }

        public Criteria andVbSimpledescLike(String value) {
            addCriterion("vb_simpledesc like", value, "vbSimpledesc");
            return (Criteria) this;
        }

        public Criteria andVbSimpledescNotLike(String value) {
            addCriterion("vb_simpledesc not like", value, "vbSimpledesc");
            return (Criteria) this;
        }

        public Criteria andVbSimpledescIn(List<String> values) {
            addCriterion("vb_simpledesc in", values, "vbSimpledesc");
            return (Criteria) this;
        }

        public Criteria andVbSimpledescNotIn(List<String> values) {
            addCriterion("vb_simpledesc not in", values, "vbSimpledesc");
            return (Criteria) this;
        }

        public Criteria andVbSimpledescBetween(String value1, String value2) {
            addCriterion("vb_simpledesc between", value1, value2, "vbSimpledesc");
            return (Criteria) this;
        }

        public Criteria andVbSimpledescNotBetween(String value1, String value2) {
            addCriterion("vb_simpledesc not between", value1, value2, "vbSimpledesc");
            return (Criteria) this;
        }

        public Criteria andVbLongdescIsNull() {
            addCriterion("vb_longdesc is null");
            return (Criteria) this;
        }

        public Criteria andVbLongdescIsNotNull() {
            addCriterion("vb_longdesc is not null");
            return (Criteria) this;
        }

        public Criteria andVbLongdescEqualTo(String value) {
            addCriterion("vb_longdesc =", value, "vbLongdesc");
            return (Criteria) this;
        }

        public Criteria andVbLongdescNotEqualTo(String value) {
            addCriterion("vb_longdesc <>", value, "vbLongdesc");
            return (Criteria) this;
        }

        public Criteria andVbLongdescGreaterThan(String value) {
            addCriterion("vb_longdesc >", value, "vbLongdesc");
            return (Criteria) this;
        }

        public Criteria andVbLongdescGreaterThanOrEqualTo(String value) {
            addCriterion("vb_longdesc >=", value, "vbLongdesc");
            return (Criteria) this;
        }

        public Criteria andVbLongdescLessThan(String value) {
            addCriterion("vb_longdesc <", value, "vbLongdesc");
            return (Criteria) this;
        }

        public Criteria andVbLongdescLessThanOrEqualTo(String value) {
            addCriterion("vb_longdesc <=", value, "vbLongdesc");
            return (Criteria) this;
        }

        public Criteria andVbLongdescLike(String value) {
            addCriterion("vb_longdesc like", value, "vbLongdesc");
            return (Criteria) this;
        }

        public Criteria andVbLongdescNotLike(String value) {
            addCriterion("vb_longdesc not like", value, "vbLongdesc");
            return (Criteria) this;
        }

        public Criteria andVbLongdescIn(List<String> values) {
            addCriterion("vb_longdesc in", values, "vbLongdesc");
            return (Criteria) this;
        }

        public Criteria andVbLongdescNotIn(List<String> values) {
            addCriterion("vb_longdesc not in", values, "vbLongdesc");
            return (Criteria) this;
        }

        public Criteria andVbLongdescBetween(String value1, String value2) {
            addCriterion("vb_longdesc between", value1, value2, "vbLongdesc");
            return (Criteria) this;
        }

        public Criteria andVbLongdescNotBetween(String value1, String value2) {
            addCriterion("vb_longdesc not between", value1, value2, "vbLongdesc");
            return (Criteria) this;
        }

        public Criteria andVbAvescoreIsNull() {
            addCriterion("vb_avescore is null");
            return (Criteria) this;
        }

        public Criteria andVbAvescoreIsNotNull() {
            addCriterion("vb_avescore is not null");
            return (Criteria) this;
        }

        public Criteria andVbAvescoreEqualTo(String value) {
            addCriterion("vb_avescore =", value, "vbAvescore");
            return (Criteria) this;
        }

        public Criteria andVbAvescoreNotEqualTo(String value) {
            addCriterion("vb_avescore <>", value, "vbAvescore");
            return (Criteria) this;
        }

        public Criteria andVbAvescoreGreaterThan(String value) {
            addCriterion("vb_avescore >", value, "vbAvescore");
            return (Criteria) this;
        }

        public Criteria andVbAvescoreGreaterThanOrEqualTo(String value) {
            addCriterion("vb_avescore >=", value, "vbAvescore");
            return (Criteria) this;
        }

        public Criteria andVbAvescoreLessThan(String value) {
            addCriterion("vb_avescore <", value, "vbAvescore");
            return (Criteria) this;
        }

        public Criteria andVbAvescoreLessThanOrEqualTo(String value) {
            addCriterion("vb_avescore <=", value, "vbAvescore");
            return (Criteria) this;
        }

        public Criteria andVbAvescoreLike(String value) {
            addCriterion("vb_avescore like", value, "vbAvescore");
            return (Criteria) this;
        }

        public Criteria andVbAvescoreNotLike(String value) {
            addCriterion("vb_avescore not like", value, "vbAvescore");
            return (Criteria) this;
        }

        public Criteria andVbAvescoreIn(List<String> values) {
            addCriterion("vb_avescore in", values, "vbAvescore");
            return (Criteria) this;
        }

        public Criteria andVbAvescoreNotIn(List<String> values) {
            addCriterion("vb_avescore not in", values, "vbAvescore");
            return (Criteria) this;
        }

        public Criteria andVbAvescoreBetween(String value1, String value2) {
            addCriterion("vb_avescore between", value1, value2, "vbAvescore");
            return (Criteria) this;
        }

        public Criteria andVbAvescoreNotBetween(String value1, String value2) {
            addCriterion("vb_avescore not between", value1, value2, "vbAvescore");
            return (Criteria) this;
        }

        public Criteria andVbTotalfavorIsNull() {
            addCriterion("vb_totalfavor is null");
            return (Criteria) this;
        }

        public Criteria andVbTotalfavorIsNotNull() {
            addCriterion("vb_totalfavor is not null");
            return (Criteria) this;
        }

        public Criteria andVbTotalfavorEqualTo(Integer value) {
            addCriterion("vb_totalfavor =", value, "vbTotalfavor");
            return (Criteria) this;
        }

        public Criteria andVbTotalfavorNotEqualTo(Integer value) {
            addCriterion("vb_totalfavor <>", value, "vbTotalfavor");
            return (Criteria) this;
        }

        public Criteria andVbTotalfavorGreaterThan(Integer value) {
            addCriterion("vb_totalfavor >", value, "vbTotalfavor");
            return (Criteria) this;
        }

        public Criteria andVbTotalfavorGreaterThanOrEqualTo(Integer value) {
            addCriterion("vb_totalfavor >=", value, "vbTotalfavor");
            return (Criteria) this;
        }

        public Criteria andVbTotalfavorLessThan(Integer value) {
            addCriterion("vb_totalfavor <", value, "vbTotalfavor");
            return (Criteria) this;
        }

        public Criteria andVbTotalfavorLessThanOrEqualTo(Integer value) {
            addCriterion("vb_totalfavor <=", value, "vbTotalfavor");
            return (Criteria) this;
        }

        public Criteria andVbTotalfavorIn(List<Integer> values) {
            addCriterion("vb_totalfavor in", values, "vbTotalfavor");
            return (Criteria) this;
        }

        public Criteria andVbTotalfavorNotIn(List<Integer> values) {
            addCriterion("vb_totalfavor not in", values, "vbTotalfavor");
            return (Criteria) this;
        }

        public Criteria andVbTotalfavorBetween(Integer value1, Integer value2) {
            addCriterion("vb_totalfavor between", value1, value2, "vbTotalfavor");
            return (Criteria) this;
        }

        public Criteria andVbTotalfavorNotBetween(Integer value1, Integer value2) {
            addCriterion("vb_totalfavor not between", value1, value2, "vbTotalfavor");
            return (Criteria) this;
        }

        public Criteria andVbTotalstepIsNull() {
            addCriterion("vb_totalstep is null");
            return (Criteria) this;
        }

        public Criteria andVbTotalstepIsNotNull() {
            addCriterion("vb_totalstep is not null");
            return (Criteria) this;
        }

        public Criteria andVbTotalstepEqualTo(Integer value) {
            addCriterion("vb_totalstep =", value, "vbTotalstep");
            return (Criteria) this;
        }

        public Criteria andVbTotalstepNotEqualTo(Integer value) {
            addCriterion("vb_totalstep <>", value, "vbTotalstep");
            return (Criteria) this;
        }

        public Criteria andVbTotalstepGreaterThan(Integer value) {
            addCriterion("vb_totalstep >", value, "vbTotalstep");
            return (Criteria) this;
        }

        public Criteria andVbTotalstepGreaterThanOrEqualTo(Integer value) {
            addCriterion("vb_totalstep >=", value, "vbTotalstep");
            return (Criteria) this;
        }

        public Criteria andVbTotalstepLessThan(Integer value) {
            addCriterion("vb_totalstep <", value, "vbTotalstep");
            return (Criteria) this;
        }

        public Criteria andVbTotalstepLessThanOrEqualTo(Integer value) {
            addCriterion("vb_totalstep <=", value, "vbTotalstep");
            return (Criteria) this;
        }

        public Criteria andVbTotalstepIn(List<Integer> values) {
            addCriterion("vb_totalstep in", values, "vbTotalstep");
            return (Criteria) this;
        }

        public Criteria andVbTotalstepNotIn(List<Integer> values) {
            addCriterion("vb_totalstep not in", values, "vbTotalstep");
            return (Criteria) this;
        }

        public Criteria andVbTotalstepBetween(Integer value1, Integer value2) {
            addCriterion("vb_totalstep between", value1, value2, "vbTotalstep");
            return (Criteria) this;
        }

        public Criteria andVbTotalstepNotBetween(Integer value1, Integer value2) {
            addCriterion("vb_totalstep not between", value1, value2, "vbTotalstep");
            return (Criteria) this;
        }

        public Criteria andVbTotalvodIsNull() {
            addCriterion("vb_totalvod is null");
            return (Criteria) this;
        }

        public Criteria andVbTotalvodIsNotNull() {
            addCriterion("vb_totalvod is not null");
            return (Criteria) this;
        }

        public Criteria andVbTotalvodEqualTo(Integer value) {
            addCriterion("vb_totalvod =", value, "vbTotalvod");
            return (Criteria) this;
        }

        public Criteria andVbTotalvodNotEqualTo(Integer value) {
            addCriterion("vb_totalvod <>", value, "vbTotalvod");
            return (Criteria) this;
        }

        public Criteria andVbTotalvodGreaterThan(Integer value) {
            addCriterion("vb_totalvod >", value, "vbTotalvod");
            return (Criteria) this;
        }

        public Criteria andVbTotalvodGreaterThanOrEqualTo(Integer value) {
            addCriterion("vb_totalvod >=", value, "vbTotalvod");
            return (Criteria) this;
        }

        public Criteria andVbTotalvodLessThan(Integer value) {
            addCriterion("vb_totalvod <", value, "vbTotalvod");
            return (Criteria) this;
        }

        public Criteria andVbTotalvodLessThanOrEqualTo(Integer value) {
            addCriterion("vb_totalvod <=", value, "vbTotalvod");
            return (Criteria) this;
        }

        public Criteria andVbTotalvodIn(List<Integer> values) {
            addCriterion("vb_totalvod in", values, "vbTotalvod");
            return (Criteria) this;
        }

        public Criteria andVbTotalvodNotIn(List<Integer> values) {
            addCriterion("vb_totalvod not in", values, "vbTotalvod");
            return (Criteria) this;
        }

        public Criteria andVbTotalvodBetween(Integer value1, Integer value2) {
            addCriterion("vb_totalvod between", value1, value2, "vbTotalvod");
            return (Criteria) this;
        }

        public Criteria andVbTotalvodNotBetween(Integer value1, Integer value2) {
            addCriterion("vb_totalvod not between", value1, value2, "vbTotalvod");
            return (Criteria) this;
        }

        public Criteria andVbFirstsourceIsNull() {
            addCriterion("vb_firstsource is null");
            return (Criteria) this;
        }

        public Criteria andVbFirstsourceIsNotNull() {
            addCriterion("vb_firstsource is not null");
            return (Criteria) this;
        }

        public Criteria andVbFirstsourceEqualTo(Short value) {
            addCriterion("vb_firstsource =", value, "vbFirstsource");
            return (Criteria) this;
        }

        public Criteria andVbFirstsourceNotEqualTo(Short value) {
            addCriterion("vb_firstsource <>", value, "vbFirstsource");
            return (Criteria) this;
        }

        public Criteria andVbFirstsourceGreaterThan(Short value) {
            addCriterion("vb_firstsource >", value, "vbFirstsource");
            return (Criteria) this;
        }

        public Criteria andVbFirstsourceGreaterThanOrEqualTo(Short value) {
            addCriterion("vb_firstsource >=", value, "vbFirstsource");
            return (Criteria) this;
        }

        public Criteria andVbFirstsourceLessThan(Short value) {
            addCriterion("vb_firstsource <", value, "vbFirstsource");
            return (Criteria) this;
        }

        public Criteria andVbFirstsourceLessThanOrEqualTo(Short value) {
            addCriterion("vb_firstsource <=", value, "vbFirstsource");
            return (Criteria) this;
        }

        public Criteria andVbFirstsourceIn(List<Short> values) {
            addCriterion("vb_firstsource in", values, "vbFirstsource");
            return (Criteria) this;
        }

        public Criteria andVbFirstsourceNotIn(List<Short> values) {
            addCriterion("vb_firstsource not in", values, "vbFirstsource");
            return (Criteria) this;
        }

        public Criteria andVbFirstsourceBetween(Short value1, Short value2) {
            addCriterion("vb_firstsource between", value1, value2, "vbFirstsource");
            return (Criteria) this;
        }

        public Criteria andVbFirstsourceNotBetween(Short value1, Short value2) {
            addCriterion("vb_firstsource not between", value1, value2, "vbFirstsource");
            return (Criteria) this;
        }

        public Criteria andVbFirstletterIsNull() {
            addCriterion("vb_firstletter is null");
            return (Criteria) this;
        }

        public Criteria andVbFirstletterIsNotNull() {
            addCriterion("vb_firstletter is not null");
            return (Criteria) this;
        }

        public Criteria andVbFirstletterEqualTo(String value) {
            addCriterion("vb_firstletter =", value, "vbFirstletter");
            return (Criteria) this;
        }

        public Criteria andVbFirstletterNotEqualTo(String value) {
            addCriterion("vb_firstletter <>", value, "vbFirstletter");
            return (Criteria) this;
        }

        public Criteria andVbFirstletterGreaterThan(String value) {
            addCriterion("vb_firstletter >", value, "vbFirstletter");
            return (Criteria) this;
        }

        public Criteria andVbFirstletterGreaterThanOrEqualTo(String value) {
            addCriterion("vb_firstletter >=", value, "vbFirstletter");
            return (Criteria) this;
        }

        public Criteria andVbFirstletterLessThan(String value) {
            addCriterion("vb_firstletter <", value, "vbFirstletter");
            return (Criteria) this;
        }

        public Criteria andVbFirstletterLessThanOrEqualTo(String value) {
            addCriterion("vb_firstletter <=", value, "vbFirstletter");
            return (Criteria) this;
        }

        public Criteria andVbFirstletterLike(String value) {
            addCriterion("vb_firstletter like", value, "vbFirstletter");
            return (Criteria) this;
        }

        public Criteria andVbFirstletterNotLike(String value) {
            addCriterion("vb_firstletter not like", value, "vbFirstletter");
            return (Criteria) this;
        }

        public Criteria andVbFirstletterIn(List<String> values) {
            addCriterion("vb_firstletter in", values, "vbFirstletter");
            return (Criteria) this;
        }

        public Criteria andVbFirstletterNotIn(List<String> values) {
            addCriterion("vb_firstletter not in", values, "vbFirstletter");
            return (Criteria) this;
        }

        public Criteria andVbFirstletterBetween(String value1, String value2) {
            addCriterion("vb_firstletter between", value1, value2, "vbFirstletter");
            return (Criteria) this;
        }

        public Criteria andVbFirstletterNotBetween(String value1, String value2) {
            addCriterion("vb_firstletter not between", value1, value2, "vbFirstletter");
            return (Criteria) this;
        }

        public Criteria andVbPinyinIsNull() {
            addCriterion("vb_pinyin is null");
            return (Criteria) this;
        }

        public Criteria andVbPinyinIsNotNull() {
            addCriterion("vb_pinyin is not null");
            return (Criteria) this;
        }

        public Criteria andVbPinyinEqualTo(String value) {
            addCriterion("vb_pinyin =", value, "vbPinyin");
            return (Criteria) this;
        }

        public Criteria andVbPinyinNotEqualTo(String value) {
            addCriterion("vb_pinyin <>", value, "vbPinyin");
            return (Criteria) this;
        }

        public Criteria andVbPinyinGreaterThan(String value) {
            addCriterion("vb_pinyin >", value, "vbPinyin");
            return (Criteria) this;
        }

        public Criteria andVbPinyinGreaterThanOrEqualTo(String value) {
            addCriterion("vb_pinyin >=", value, "vbPinyin");
            return (Criteria) this;
        }

        public Criteria andVbPinyinLessThan(String value) {
            addCriterion("vb_pinyin <", value, "vbPinyin");
            return (Criteria) this;
        }

        public Criteria andVbPinyinLessThanOrEqualTo(String value) {
            addCriterion("vb_pinyin <=", value, "vbPinyin");
            return (Criteria) this;
        }

        public Criteria andVbPinyinLike(String value) {
            addCriterion("vb_pinyin like", value, "vbPinyin");
            return (Criteria) this;
        }

        public Criteria andVbPinyinNotLike(String value) {
            addCriterion("vb_pinyin not like", value, "vbPinyin");
            return (Criteria) this;
        }

        public Criteria andVbPinyinIn(List<String> values) {
            addCriterion("vb_pinyin in", values, "vbPinyin");
            return (Criteria) this;
        }

        public Criteria andVbPinyinNotIn(List<String> values) {
            addCriterion("vb_pinyin not in", values, "vbPinyin");
            return (Criteria) this;
        }

        public Criteria andVbPinyinBetween(String value1, String value2) {
            addCriterion("vb_pinyin between", value1, value2, "vbPinyin");
            return (Criteria) this;
        }

        public Criteria andVbPinyinNotBetween(String value1, String value2) {
            addCriterion("vb_pinyin not between", value1, value2, "vbPinyin");
            return (Criteria) this;
        }

        public Criteria andVbTotallastIsNull() {
            addCriterion("vb_totallast is null");
            return (Criteria) this;
        }

        public Criteria andVbTotallastIsNotNull() {
            addCriterion("vb_totallast is not null");
            return (Criteria) this;
        }

        public Criteria andVbTotallastEqualTo(Integer value) {
            addCriterion("vb_totallast =", value, "vbTotallast");
            return (Criteria) this;
        }

        public Criteria andVbTotallastNotEqualTo(Integer value) {
            addCriterion("vb_totallast <>", value, "vbTotallast");
            return (Criteria) this;
        }

        public Criteria andVbTotallastGreaterThan(Integer value) {
            addCriterion("vb_totallast >", value, "vbTotallast");
            return (Criteria) this;
        }

        public Criteria andVbTotallastGreaterThanOrEqualTo(Integer value) {
            addCriterion("vb_totallast >=", value, "vbTotallast");
            return (Criteria) this;
        }

        public Criteria andVbTotallastLessThan(Integer value) {
            addCriterion("vb_totallast <", value, "vbTotallast");
            return (Criteria) this;
        }

        public Criteria andVbTotallastLessThanOrEqualTo(Integer value) {
            addCriterion("vb_totallast <=", value, "vbTotallast");
            return (Criteria) this;
        }

        public Criteria andVbTotallastIn(List<Integer> values) {
            addCriterion("vb_totallast in", values, "vbTotallast");
            return (Criteria) this;
        }

        public Criteria andVbTotallastNotIn(List<Integer> values) {
            addCriterion("vb_totallast not in", values, "vbTotallast");
            return (Criteria) this;
        }

        public Criteria andVbTotallastBetween(Integer value1, Integer value2) {
            addCriterion("vb_totallast between", value1, value2, "vbTotallast");
            return (Criteria) this;
        }

        public Criteria andVbTotallastNotBetween(Integer value1, Integer value2) {
            addCriterion("vb_totallast not between", value1, value2, "vbTotallast");
            return (Criteria) this;
        }

        public Criteria andVbTotalhotIsNull() {
            addCriterion("vb_totalhot is null");
            return (Criteria) this;
        }

        public Criteria andVbTotalhotIsNotNull() {
            addCriterion("vb_totalhot is not null");
            return (Criteria) this;
        }

        public Criteria andVbTotalhotEqualTo(Integer value) {
            addCriterion("vb_totalhot =", value, "vbTotalhot");
            return (Criteria) this;
        }

        public Criteria andVbTotalhotNotEqualTo(Integer value) {
            addCriterion("vb_totalhot <>", value, "vbTotalhot");
            return (Criteria) this;
        }

        public Criteria andVbTotalhotGreaterThan(Integer value) {
            addCriterion("vb_totalhot >", value, "vbTotalhot");
            return (Criteria) this;
        }

        public Criteria andVbTotalhotGreaterThanOrEqualTo(Integer value) {
            addCriterion("vb_totalhot >=", value, "vbTotalhot");
            return (Criteria) this;
        }

        public Criteria andVbTotalhotLessThan(Integer value) {
            addCriterion("vb_totalhot <", value, "vbTotalhot");
            return (Criteria) this;
        }

        public Criteria andVbTotalhotLessThanOrEqualTo(Integer value) {
            addCriterion("vb_totalhot <=", value, "vbTotalhot");
            return (Criteria) this;
        }

        public Criteria andVbTotalhotIn(List<Integer> values) {
            addCriterion("vb_totalhot in", values, "vbTotalhot");
            return (Criteria) this;
        }

        public Criteria andVbTotalhotNotIn(List<Integer> values) {
            addCriterion("vb_totalhot not in", values, "vbTotalhot");
            return (Criteria) this;
        }

        public Criteria andVbTotalhotBetween(Integer value1, Integer value2) {
            addCriterion("vb_totalhot between", value1, value2, "vbTotalhot");
            return (Criteria) this;
        }

        public Criteria andVbTotalhotNotBetween(Integer value1, Integer value2) {
            addCriterion("vb_totalhot not between", value1, value2, "vbTotalhot");
            return (Criteria) this;
        }

        public Criteria andVbTotalhotfavorIsNull() {
            addCriterion("vb_totalhotfavor is null");
            return (Criteria) this;
        }

        public Criteria andVbTotalhotfavorIsNotNull() {
            addCriterion("vb_totalhotfavor is not null");
            return (Criteria) this;
        }

        public Criteria andVbTotalhotfavorEqualTo(Integer value) {
            addCriterion("vb_totalhotfavor =", value, "vbTotalhotfavor");
            return (Criteria) this;
        }

        public Criteria andVbTotalhotfavorNotEqualTo(Integer value) {
            addCriterion("vb_totalhotfavor <>", value, "vbTotalhotfavor");
            return (Criteria) this;
        }

        public Criteria andVbTotalhotfavorGreaterThan(Integer value) {
            addCriterion("vb_totalhotfavor >", value, "vbTotalhotfavor");
            return (Criteria) this;
        }

        public Criteria andVbTotalhotfavorGreaterThanOrEqualTo(Integer value) {
            addCriterion("vb_totalhotfavor >=", value, "vbTotalhotfavor");
            return (Criteria) this;
        }

        public Criteria andVbTotalhotfavorLessThan(Integer value) {
            addCriterion("vb_totalhotfavor <", value, "vbTotalhotfavor");
            return (Criteria) this;
        }

        public Criteria andVbTotalhotfavorLessThanOrEqualTo(Integer value) {
            addCriterion("vb_totalhotfavor <=", value, "vbTotalhotfavor");
            return (Criteria) this;
        }

        public Criteria andVbTotalhotfavorIn(List<Integer> values) {
            addCriterion("vb_totalhotfavor in", values, "vbTotalhotfavor");
            return (Criteria) this;
        }

        public Criteria andVbTotalhotfavorNotIn(List<Integer> values) {
            addCriterion("vb_totalhotfavor not in", values, "vbTotalhotfavor");
            return (Criteria) this;
        }

        public Criteria andVbTotalhotfavorBetween(Integer value1, Integer value2) {
            addCriterion("vb_totalhotfavor between", value1, value2, "vbTotalhotfavor");
            return (Criteria) this;
        }

        public Criteria andVbTotalhotfavorNotBetween(Integer value1, Integer value2) {
            addCriterion("vb_totalhotfavor not between", value1, value2, "vbTotalhotfavor");
            return (Criteria) this;
        }

        public Criteria andVbTotalsearchIsNull() {
            addCriterion("vb_totalsearch is null");
            return (Criteria) this;
        }

        public Criteria andVbTotalsearchIsNotNull() {
            addCriterion("vb_totalsearch is not null");
            return (Criteria) this;
        }

        public Criteria andVbTotalsearchEqualTo(Integer value) {
            addCriterion("vb_totalsearch =", value, "vbTotalsearch");
            return (Criteria) this;
        }

        public Criteria andVbTotalsearchNotEqualTo(Integer value) {
            addCriterion("vb_totalsearch <>", value, "vbTotalsearch");
            return (Criteria) this;
        }

        public Criteria andVbTotalsearchGreaterThan(Integer value) {
            addCriterion("vb_totalsearch >", value, "vbTotalsearch");
            return (Criteria) this;
        }

        public Criteria andVbTotalsearchGreaterThanOrEqualTo(Integer value) {
            addCriterion("vb_totalsearch >=", value, "vbTotalsearch");
            return (Criteria) this;
        }

        public Criteria andVbTotalsearchLessThan(Integer value) {
            addCriterion("vb_totalsearch <", value, "vbTotalsearch");
            return (Criteria) this;
        }

        public Criteria andVbTotalsearchLessThanOrEqualTo(Integer value) {
            addCriterion("vb_totalsearch <=", value, "vbTotalsearch");
            return (Criteria) this;
        }

        public Criteria andVbTotalsearchIn(List<Integer> values) {
            addCriterion("vb_totalsearch in", values, "vbTotalsearch");
            return (Criteria) this;
        }

        public Criteria andVbTotalsearchNotIn(List<Integer> values) {
            addCriterion("vb_totalsearch not in", values, "vbTotalsearch");
            return (Criteria) this;
        }

        public Criteria andVbTotalsearchBetween(Integer value1, Integer value2) {
            addCriterion("vb_totalsearch between", value1, value2, "vbTotalsearch");
            return (Criteria) this;
        }

        public Criteria andVbTotalsearchNotBetween(Integer value1, Integer value2) {
            addCriterion("vb_totalsearch not between", value1, value2, "vbTotalsearch");
            return (Criteria) this;
        }

        public Criteria andVbDoubanscoreIsNull() {
            addCriterion("vb_doubanscore is null");
            return (Criteria) this;
        }

        public Criteria andVbDoubanscoreIsNotNull() {
            addCriterion("vb_doubanscore is not null");
            return (Criteria) this;
        }

        public Criteria andVbDoubanscoreEqualTo(String value) {
            addCriterion("vb_doubanscore =", value, "vbDoubanscore");
            return (Criteria) this;
        }

        public Criteria andVbDoubanscoreNotEqualTo(String value) {
            addCriterion("vb_doubanscore <>", value, "vbDoubanscore");
            return (Criteria) this;
        }

        public Criteria andVbDoubanscoreGreaterThan(String value) {
            addCriterion("vb_doubanscore >", value, "vbDoubanscore");
            return (Criteria) this;
        }

        public Criteria andVbDoubanscoreGreaterThanOrEqualTo(String value) {
            addCriterion("vb_doubanscore >=", value, "vbDoubanscore");
            return (Criteria) this;
        }

        public Criteria andVbDoubanscoreLessThan(String value) {
            addCriterion("vb_doubanscore <", value, "vbDoubanscore");
            return (Criteria) this;
        }

        public Criteria andVbDoubanscoreLessThanOrEqualTo(String value) {
            addCriterion("vb_doubanscore <=", value, "vbDoubanscore");
            return (Criteria) this;
        }

        public Criteria andVbDoubanscoreLike(String value) {
            addCriterion("vb_doubanscore like", value, "vbDoubanscore");
            return (Criteria) this;
        }

        public Criteria andVbDoubanscoreNotLike(String value) {
            addCriterion("vb_doubanscore not like", value, "vbDoubanscore");
            return (Criteria) this;
        }

        public Criteria andVbDoubanscoreIn(List<String> values) {
            addCriterion("vb_doubanscore in", values, "vbDoubanscore");
            return (Criteria) this;
        }

        public Criteria andVbDoubanscoreNotIn(List<String> values) {
            addCriterion("vb_doubanscore not in", values, "vbDoubanscore");
            return (Criteria) this;
        }

        public Criteria andVbDoubanscoreBetween(String value1, String value2) {
            addCriterion("vb_doubanscore between", value1, value2, "vbDoubanscore");
            return (Criteria) this;
        }

        public Criteria andVbDoubanscoreNotBetween(String value1, String value2) {
            addCriterion("vb_doubanscore not between", value1, value2, "vbDoubanscore");
            return (Criteria) this;
        }

        public Criteria andVbDoubancommentIsNull() {
            addCriterion("vb_doubancomment is null");
            return (Criteria) this;
        }

        public Criteria andVbDoubancommentIsNotNull() {
            addCriterion("vb_doubancomment is not null");
            return (Criteria) this;
        }

        public Criteria andVbDoubancommentEqualTo(String value) {
            addCriterion("vb_doubancomment =", value, "vbDoubancomment");
            return (Criteria) this;
        }

        public Criteria andVbDoubancommentNotEqualTo(String value) {
            addCriterion("vb_doubancomment <>", value, "vbDoubancomment");
            return (Criteria) this;
        }

        public Criteria andVbDoubancommentGreaterThan(String value) {
            addCriterion("vb_doubancomment >", value, "vbDoubancomment");
            return (Criteria) this;
        }

        public Criteria andVbDoubancommentGreaterThanOrEqualTo(String value) {
            addCriterion("vb_doubancomment >=", value, "vbDoubancomment");
            return (Criteria) this;
        }

        public Criteria andVbDoubancommentLessThan(String value) {
            addCriterion("vb_doubancomment <", value, "vbDoubancomment");
            return (Criteria) this;
        }

        public Criteria andVbDoubancommentLessThanOrEqualTo(String value) {
            addCriterion("vb_doubancomment <=", value, "vbDoubancomment");
            return (Criteria) this;
        }

        public Criteria andVbDoubancommentLike(String value) {
            addCriterion("vb_doubancomment like", value, "vbDoubancomment");
            return (Criteria) this;
        }

        public Criteria andVbDoubancommentNotLike(String value) {
            addCriterion("vb_doubancomment not like", value, "vbDoubancomment");
            return (Criteria) this;
        }

        public Criteria andVbDoubancommentIn(List<String> values) {
            addCriterion("vb_doubancomment in", values, "vbDoubancomment");
            return (Criteria) this;
        }

        public Criteria andVbDoubancommentNotIn(List<String> values) {
            addCriterion("vb_doubancomment not in", values, "vbDoubancomment");
            return (Criteria) this;
        }

        public Criteria andVbDoubancommentBetween(String value1, String value2) {
            addCriterion("vb_doubancomment between", value1, value2, "vbDoubancomment");
            return (Criteria) this;
        }

        public Criteria andVbDoubancommentNotBetween(String value1, String value2) {
            addCriterion("vb_doubancomment not between", value1, value2, "vbDoubancomment");
            return (Criteria) this;
        }

        public Criteria andVbReserved0IsNull() {
            addCriterion("vb_reserved_0 is null");
            return (Criteria) this;
        }

        public Criteria andVbReserved0IsNotNull() {
            addCriterion("vb_reserved_0 is not null");
            return (Criteria) this;
        }

        public Criteria andVbReserved0EqualTo(String value) {
            addCriterion("vb_reserved_0 =", value, "vbReserved0");
            return (Criteria) this;
        }

        public Criteria andVbReserved0NotEqualTo(String value) {
            addCriterion("vb_reserved_0 <>", value, "vbReserved0");
            return (Criteria) this;
        }

        public Criteria andVbReserved0GreaterThan(String value) {
            addCriterion("vb_reserved_0 >", value, "vbReserved0");
            return (Criteria) this;
        }

        public Criteria andVbReserved0GreaterThanOrEqualTo(String value) {
            addCriterion("vb_reserved_0 >=", value, "vbReserved0");
            return (Criteria) this;
        }

        public Criteria andVbReserved0LessThan(String value) {
            addCriterion("vb_reserved_0 <", value, "vbReserved0");
            return (Criteria) this;
        }

        public Criteria andVbReserved0LessThanOrEqualTo(String value) {
            addCriterion("vb_reserved_0 <=", value, "vbReserved0");
            return (Criteria) this;
        }

        public Criteria andVbReserved0Like(String value) {
            addCriterion("vb_reserved_0 like", value, "vbReserved0");
            return (Criteria) this;
        }

        public Criteria andVbReserved0NotLike(String value) {
            addCriterion("vb_reserved_0 not like", value, "vbReserved0");
            return (Criteria) this;
        }

        public Criteria andVbReserved0In(List<String> values) {
            addCriterion("vb_reserved_0 in", values, "vbReserved0");
            return (Criteria) this;
        }

        public Criteria andVbReserved0NotIn(List<String> values) {
            addCriterion("vb_reserved_0 not in", values, "vbReserved0");
            return (Criteria) this;
        }

        public Criteria andVbReserved0Between(String value1, String value2) {
            addCriterion("vb_reserved_0 between", value1, value2, "vbReserved0");
            return (Criteria) this;
        }

        public Criteria andVbReserved0NotBetween(String value1, String value2) {
            addCriterion("vb_reserved_0 not between", value1, value2, "vbReserved0");
            return (Criteria) this;
        }

        public Criteria andVbReserved1IsNull() {
            addCriterion("vb_reserved_1 is null");
            return (Criteria) this;
        }

        public Criteria andVbReserved1IsNotNull() {
            addCriterion("vb_reserved_1 is not null");
            return (Criteria) this;
        }

        public Criteria andVbReserved1EqualTo(String value) {
            addCriterion("vb_reserved_1 =", value, "vbReserved1");
            return (Criteria) this;
        }

        public Criteria andVbReserved1NotEqualTo(String value) {
            addCriterion("vb_reserved_1 <>", value, "vbReserved1");
            return (Criteria) this;
        }

        public Criteria andVbReserved1GreaterThan(String value) {
            addCriterion("vb_reserved_1 >", value, "vbReserved1");
            return (Criteria) this;
        }

        public Criteria andVbReserved1GreaterThanOrEqualTo(String value) {
            addCriterion("vb_reserved_1 >=", value, "vbReserved1");
            return (Criteria) this;
        }

        public Criteria andVbReserved1LessThan(String value) {
            addCriterion("vb_reserved_1 <", value, "vbReserved1");
            return (Criteria) this;
        }

        public Criteria andVbReserved1LessThanOrEqualTo(String value) {
            addCriterion("vb_reserved_1 <=", value, "vbReserved1");
            return (Criteria) this;
        }

        public Criteria andVbReserved1Like(String value) {
            addCriterion("vb_reserved_1 like", value, "vbReserved1");
            return (Criteria) this;
        }

        public Criteria andVbReserved1NotLike(String value) {
            addCriterion("vb_reserved_1 not like", value, "vbReserved1");
            return (Criteria) this;
        }

        public Criteria andVbReserved1In(List<String> values) {
            addCriterion("vb_reserved_1 in", values, "vbReserved1");
            return (Criteria) this;
        }

        public Criteria andVbReserved1NotIn(List<String> values) {
            addCriterion("vb_reserved_1 not in", values, "vbReserved1");
            return (Criteria) this;
        }

        public Criteria andVbReserved1Between(String value1, String value2) {
            addCriterion("vb_reserved_1 between", value1, value2, "vbReserved1");
            return (Criteria) this;
        }

        public Criteria andVbReserved1NotBetween(String value1, String value2) {
            addCriterion("vb_reserved_1 not between", value1, value2, "vbReserved1");
            return (Criteria) this;
        }

        public Criteria andVbReserved2IsNull() {
            addCriterion("vb_reserved_2 is null");
            return (Criteria) this;
        }

        public Criteria andVbReserved2IsNotNull() {
            addCriterion("vb_reserved_2 is not null");
            return (Criteria) this;
        }

        public Criteria andVbReserved2EqualTo(String value) {
            addCriterion("vb_reserved_2 =", value, "vbReserved2");
            return (Criteria) this;
        }

        public Criteria andVbReserved2NotEqualTo(String value) {
            addCriterion("vb_reserved_2 <>", value, "vbReserved2");
            return (Criteria) this;
        }

        public Criteria andVbReserved2GreaterThan(String value) {
            addCriterion("vb_reserved_2 >", value, "vbReserved2");
            return (Criteria) this;
        }

        public Criteria andVbReserved2GreaterThanOrEqualTo(String value) {
            addCriterion("vb_reserved_2 >=", value, "vbReserved2");
            return (Criteria) this;
        }

        public Criteria andVbReserved2LessThan(String value) {
            addCriterion("vb_reserved_2 <", value, "vbReserved2");
            return (Criteria) this;
        }

        public Criteria andVbReserved2LessThanOrEqualTo(String value) {
            addCriterion("vb_reserved_2 <=", value, "vbReserved2");
            return (Criteria) this;
        }

        public Criteria andVbReserved2Like(String value) {
            addCriterion("vb_reserved_2 like", value, "vbReserved2");
            return (Criteria) this;
        }

        public Criteria andVbReserved2NotLike(String value) {
            addCriterion("vb_reserved_2 not like", value, "vbReserved2");
            return (Criteria) this;
        }

        public Criteria andVbReserved2In(List<String> values) {
            addCriterion("vb_reserved_2 in", values, "vbReserved2");
            return (Criteria) this;
        }

        public Criteria andVbReserved2NotIn(List<String> values) {
            addCriterion("vb_reserved_2 not in", values, "vbReserved2");
            return (Criteria) this;
        }

        public Criteria andVbReserved2Between(String value1, String value2) {
            addCriterion("vb_reserved_2 between", value1, value2, "vbReserved2");
            return (Criteria) this;
        }

        public Criteria andVbReserved2NotBetween(String value1, String value2) {
            addCriterion("vb_reserved_2 not between", value1, value2, "vbReserved2");
            return (Criteria) this;
        }

        public Criteria andVbReserved3IsNull() {
            addCriterion("vb_reserved_3 is null");
            return (Criteria) this;
        }

        public Criteria andVbReserved3IsNotNull() {
            addCriterion("vb_reserved_3 is not null");
            return (Criteria) this;
        }

        public Criteria andVbReserved3EqualTo(String value) {
            addCriterion("vb_reserved_3 =", value, "vbReserved3");
            return (Criteria) this;
        }

        public Criteria andVbReserved3NotEqualTo(String value) {
            addCriterion("vb_reserved_3 <>", value, "vbReserved3");
            return (Criteria) this;
        }

        public Criteria andVbReserved3GreaterThan(String value) {
            addCriterion("vb_reserved_3 >", value, "vbReserved3");
            return (Criteria) this;
        }

        public Criteria andVbReserved3GreaterThanOrEqualTo(String value) {
            addCriterion("vb_reserved_3 >=", value, "vbReserved3");
            return (Criteria) this;
        }

        public Criteria andVbReserved3LessThan(String value) {
            addCriterion("vb_reserved_3 <", value, "vbReserved3");
            return (Criteria) this;
        }

        public Criteria andVbReserved3LessThanOrEqualTo(String value) {
            addCriterion("vb_reserved_3 <=", value, "vbReserved3");
            return (Criteria) this;
        }

        public Criteria andVbReserved3Like(String value) {
            addCriterion("vb_reserved_3 like", value, "vbReserved3");
            return (Criteria) this;
        }

        public Criteria andVbReserved3NotLike(String value) {
            addCriterion("vb_reserved_3 not like", value, "vbReserved3");
            return (Criteria) this;
        }

        public Criteria andVbReserved3In(List<String> values) {
            addCriterion("vb_reserved_3 in", values, "vbReserved3");
            return (Criteria) this;
        }

        public Criteria andVbReserved3NotIn(List<String> values) {
            addCriterion("vb_reserved_3 not in", values, "vbReserved3");
            return (Criteria) this;
        }

        public Criteria andVbReserved3Between(String value1, String value2) {
            addCriterion("vb_reserved_3 between", value1, value2, "vbReserved3");
            return (Criteria) this;
        }

        public Criteria andVbReserved3NotBetween(String value1, String value2) {
            addCriterion("vb_reserved_3 not between", value1, value2, "vbReserved3");
            return (Criteria) this;
        }

        public Criteria andFcIdIsNull() {
            addCriterion("fc_id is null");
            return (Criteria) this;
        }

        public Criteria andFcIdIsNotNull() {
            addCriterion("fc_id is not null");
            return (Criteria) this;
        }

        public Criteria andFcIdEqualTo(Short value) {
            addCriterion("fc_id =", value, "fcId");
            return (Criteria) this;
        }

        public Criteria andFcIdNotEqualTo(Short value) {
            addCriterion("fc_id <>", value, "fcId");
            return (Criteria) this;
        }

        public Criteria andFcIdGreaterThan(Short value) {
            addCriterion("fc_id >", value, "fcId");
            return (Criteria) this;
        }

        public Criteria andFcIdGreaterThanOrEqualTo(Short value) {
            addCriterion("fc_id >=", value, "fcId");
            return (Criteria) this;
        }

        public Criteria andFcIdLessThan(Short value) {
            addCriterion("fc_id <", value, "fcId");
            return (Criteria) this;
        }

        public Criteria andFcIdLessThanOrEqualTo(Short value) {
            addCriterion("fc_id <=", value, "fcId");
            return (Criteria) this;
        }

        public Criteria andFcIdIn(List<Short> values) {
            addCriterion("fc_id in", values, "fcId");
            return (Criteria) this;
        }

        public Criteria andFcIdNotIn(List<Short> values) {
            addCriterion("fc_id not in", values, "fcId");
            return (Criteria) this;
        }

        public Criteria andFcIdBetween(Short value1, Short value2) {
            addCriterion("fc_id between", value1, value2, "fcId");
            return (Criteria) this;
        }

        public Criteria andFcIdNotBetween(Short value1, Short value2) {
            addCriterion("fc_id not between", value1, value2, "fcId");
            return (Criteria) this;
        }

        public Criteria andAcIdIsNull() {
            addCriterion("ac_id is null");
            return (Criteria) this;
        }

        public Criteria andAcIdIsNotNull() {
            addCriterion("ac_id is not null");
            return (Criteria) this;
        }

        public Criteria andAcIdEqualTo(Short value) {
            addCriterion("ac_id =", value, "acId");
            return (Criteria) this;
        }

        public Criteria andAcIdNotEqualTo(Short value) {
            addCriterion("ac_id <>", value, "acId");
            return (Criteria) this;
        }

        public Criteria andAcIdGreaterThan(Short value) {
            addCriterion("ac_id >", value, "acId");
            return (Criteria) this;
        }

        public Criteria andAcIdGreaterThanOrEqualTo(Short value) {
            addCriterion("ac_id >=", value, "acId");
            return (Criteria) this;
        }

        public Criteria andAcIdLessThan(Short value) {
            addCriterion("ac_id <", value, "acId");
            return (Criteria) this;
        }

        public Criteria andAcIdLessThanOrEqualTo(Short value) {
            addCriterion("ac_id <=", value, "acId");
            return (Criteria) this;
        }

        public Criteria andAcIdIn(List<Short> values) {
            addCriterion("ac_id in", values, "acId");
            return (Criteria) this;
        }

        public Criteria andAcIdNotIn(List<Short> values) {
            addCriterion("ac_id not in", values, "acId");
            return (Criteria) this;
        }

        public Criteria andAcIdBetween(Short value1, Short value2) {
            addCriterion("ac_id between", value1, value2, "acId");
            return (Criteria) this;
        }

        public Criteria andAcIdNotBetween(Short value1, Short value2) {
            addCriterion("ac_id not between", value1, value2, "acId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table video_baseinfo_tbl
     *
     * @mbggenerated do_not_delete_during_merge Wed Jan 23 17:42:39 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table video_baseinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}