package org.apache.nutch.parse.html.video.database.model;

public class VideoPlayinfoTbl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_playinfo_tbl.id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_playinfo_tbl.vs_subvid
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private String vsSubvid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_playinfo_tbl.vp_definition
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private Short vpDefinition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_playinfo_tbl.vp_playurl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private String vpPlayurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_playinfo_tbl.vp_reserved_0
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private String vpReserved0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_playinfo_tbl.vp_reserved_1
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private String vpReserved1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_playinfo_tbl.id
     *
     * @return the value of video_playinfo_tbl.id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_playinfo_tbl.id
     *
     * @param id the value for video_playinfo_tbl.id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_playinfo_tbl.vs_subvid
     *
     * @return the value of video_playinfo_tbl.vs_subvid
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getVsSubvid() {
        return vsSubvid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_playinfo_tbl.vs_subvid
     *
     * @param vsSubvid the value for video_playinfo_tbl.vs_subvid
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVsSubvid(String vsSubvid) {
        this.vsSubvid = vsSubvid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_playinfo_tbl.vp_definition
     *
     * @return the value of video_playinfo_tbl.vp_definition
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Short getVpDefinition() {
        return vpDefinition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_playinfo_tbl.vp_definition
     *
     * @param vpDefinition the value for video_playinfo_tbl.vp_definition
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVpDefinition(Short vpDefinition) {
        this.vpDefinition = vpDefinition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_playinfo_tbl.vp_playurl
     *
     * @return the value of video_playinfo_tbl.vp_playurl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getVpPlayurl() {
        return vpPlayurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_playinfo_tbl.vp_playurl
     *
     * @param vpPlayurl the value for video_playinfo_tbl.vp_playurl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVpPlayurl(String vpPlayurl) {
        this.vpPlayurl = vpPlayurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_playinfo_tbl.vp_reserved_0
     *
     * @return the value of video_playinfo_tbl.vp_reserved_0
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getVpReserved0() {
        return vpReserved0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_playinfo_tbl.vp_reserved_0
     *
     * @param vpReserved0 the value for video_playinfo_tbl.vp_reserved_0
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVpReserved0(String vpReserved0) {
        this.vpReserved0 = vpReserved0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_playinfo_tbl.vp_reserved_1
     *
     * @return the value of video_playinfo_tbl.vp_reserved_1
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getVpReserved1() {
        return vpReserved1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_playinfo_tbl.vp_reserved_1
     *
     * @param vpReserved1 the value for video_playinfo_tbl.vp_reserved_1
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVpReserved1(String vpReserved1) {
        this.vpReserved1 = vpReserved1;
    }
}