package org.apache.nutch.parse.html.video.database.model;

public class VideoSourceinfoTbl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_sourceinfo_tbl.id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_sourceinfo_tbl.vs_subvid
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private String vsSubvid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_sourceinfo_tbl.vs_setnumber
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private String vsSetnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_sourceinfo_tbl.vs_sourceurl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private String vsSourceurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_sourceinfo_tbl.vs_urlvalid
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private Boolean vsUrlvalid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_sourceinfo_tbl.vs_subduration
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private String vsSubduration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_sourceinfo_tbl.vs_subtitle
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private String vsSubtitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_sourceinfo_tbl.vs_subdesc
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private String vsSubdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_sourceinfo_tbl.vs_subthumb
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private String vsSubthumb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_sourceinfo_tbl.vs_host
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private String vsHost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_sourceinfo_tbl.vs_guest
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private String vsGuest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_sourceinfo_tbl.cs_id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private Short csId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_sourceinfo_tbl.vb_id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private Integer vbId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_sourceinfo_tbl.vs_reserved_0
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private String vsReserved0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_sourceinfo_tbl.vs_reserved_1
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private String vsReserved1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_sourceinfo_tbl.vs_reserved_2
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private String vsReserved2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_sourceinfo_tbl.vs_reserved_3
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    private String vsReserved3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_sourceinfo_tbl.id
     *
     * @return the value of video_sourceinfo_tbl.id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_sourceinfo_tbl.id
     *
     * @param id the value for video_sourceinfo_tbl.id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_sourceinfo_tbl.vs_subvid
     *
     * @return the value of video_sourceinfo_tbl.vs_subvid
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getVsSubvid() {
        return vsSubvid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_sourceinfo_tbl.vs_subvid
     *
     * @param vsSubvid the value for video_sourceinfo_tbl.vs_subvid
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVsSubvid(String vsSubvid) {
        this.vsSubvid = vsSubvid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_sourceinfo_tbl.vs_setnumber
     *
     * @return the value of video_sourceinfo_tbl.vs_setnumber
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getVsSetnumber() {
        return vsSetnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_sourceinfo_tbl.vs_setnumber
     *
     * @param vsSetnumber the value for video_sourceinfo_tbl.vs_setnumber
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVsSetnumber(String vsSetnumber) {
        this.vsSetnumber = vsSetnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_sourceinfo_tbl.vs_sourceurl
     *
     * @return the value of video_sourceinfo_tbl.vs_sourceurl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getVsSourceurl() {
        return vsSourceurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_sourceinfo_tbl.vs_sourceurl
     *
     * @param vsSourceurl the value for video_sourceinfo_tbl.vs_sourceurl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVsSourceurl(String vsSourceurl) {
        this.vsSourceurl = vsSourceurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_sourceinfo_tbl.vs_urlvalid
     *
     * @return the value of video_sourceinfo_tbl.vs_urlvalid
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Boolean getVsUrlvalid() {
        return vsUrlvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_sourceinfo_tbl.vs_urlvalid
     *
     * @param vsUrlvalid the value for video_sourceinfo_tbl.vs_urlvalid
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVsUrlvalid(Boolean vsUrlvalid) {
        this.vsUrlvalid = vsUrlvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_sourceinfo_tbl.vs_subduration
     *
     * @return the value of video_sourceinfo_tbl.vs_subduration
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getVsSubduration() {
        return vsSubduration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_sourceinfo_tbl.vs_subduration
     *
     * @param vsSubduration the value for video_sourceinfo_tbl.vs_subduration
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVsSubduration(String vsSubduration) {
        this.vsSubduration = vsSubduration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_sourceinfo_tbl.vs_subtitle
     *
     * @return the value of video_sourceinfo_tbl.vs_subtitle
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getVsSubtitle() {
        return vsSubtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_sourceinfo_tbl.vs_subtitle
     *
     * @param vsSubtitle the value for video_sourceinfo_tbl.vs_subtitle
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVsSubtitle(String vsSubtitle) {
        this.vsSubtitle = vsSubtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_sourceinfo_tbl.vs_subdesc
     *
     * @return the value of video_sourceinfo_tbl.vs_subdesc
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getVsSubdesc() {
        return vsSubdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_sourceinfo_tbl.vs_subdesc
     *
     * @param vsSubdesc the value for video_sourceinfo_tbl.vs_subdesc
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVsSubdesc(String vsSubdesc) {
        this.vsSubdesc = vsSubdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_sourceinfo_tbl.vs_subthumb
     *
     * @return the value of video_sourceinfo_tbl.vs_subthumb
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getVsSubthumb() {
        return vsSubthumb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_sourceinfo_tbl.vs_subthumb
     *
     * @param vsSubthumb the value for video_sourceinfo_tbl.vs_subthumb
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVsSubthumb(String vsSubthumb) {
        this.vsSubthumb = vsSubthumb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_sourceinfo_tbl.vs_host
     *
     * @return the value of video_sourceinfo_tbl.vs_host
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getVsHost() {
        return vsHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_sourceinfo_tbl.vs_host
     *
     * @param vsHost the value for video_sourceinfo_tbl.vs_host
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVsHost(String vsHost) {
        this.vsHost = vsHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_sourceinfo_tbl.vs_guest
     *
     * @return the value of video_sourceinfo_tbl.vs_guest
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getVsGuest() {
        return vsGuest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_sourceinfo_tbl.vs_guest
     *
     * @param vsGuest the value for video_sourceinfo_tbl.vs_guest
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVsGuest(String vsGuest) {
        this.vsGuest = vsGuest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_sourceinfo_tbl.cs_id
     *
     * @return the value of video_sourceinfo_tbl.cs_id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Short getCsId() {
        return csId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_sourceinfo_tbl.cs_id
     *
     * @param csId the value for video_sourceinfo_tbl.cs_id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setCsId(Short csId) {
        this.csId = csId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_sourceinfo_tbl.vb_id
     *
     * @return the value of video_sourceinfo_tbl.vb_id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public Integer getVbId() {
        return vbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_sourceinfo_tbl.vb_id
     *
     * @param vbId the value for video_sourceinfo_tbl.vb_id
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVbId(Integer vbId) {
        this.vbId = vbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_sourceinfo_tbl.vs_reserved_0
     *
     * @return the value of video_sourceinfo_tbl.vs_reserved_0
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getVsReserved0() {
        return vsReserved0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_sourceinfo_tbl.vs_reserved_0
     *
     * @param vsReserved0 the value for video_sourceinfo_tbl.vs_reserved_0
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVsReserved0(String vsReserved0) {
        this.vsReserved0 = vsReserved0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_sourceinfo_tbl.vs_reserved_1
     *
     * @return the value of video_sourceinfo_tbl.vs_reserved_1
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getVsReserved1() {
        return vsReserved1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_sourceinfo_tbl.vs_reserved_1
     *
     * @param vsReserved1 the value for video_sourceinfo_tbl.vs_reserved_1
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVsReserved1(String vsReserved1) {
        this.vsReserved1 = vsReserved1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_sourceinfo_tbl.vs_reserved_2
     *
     * @return the value of video_sourceinfo_tbl.vs_reserved_2
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getVsReserved2() {
        return vsReserved2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_sourceinfo_tbl.vs_reserved_2
     *
     * @param vsReserved2 the value for video_sourceinfo_tbl.vs_reserved_2
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVsReserved2(String vsReserved2) {
        this.vsReserved2 = vsReserved2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_sourceinfo_tbl.vs_reserved_3
     *
     * @return the value of video_sourceinfo_tbl.vs_reserved_3
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public String getVsReserved3() {
        return vsReserved3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_sourceinfo_tbl.vs_reserved_3
     *
     * @param vsReserved3 the value for video_sourceinfo_tbl.vs_reserved_3
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    public void setVsReserved3(String vsReserved3) {
        this.vsReserved3 = vsReserved3;
    }
}