package org.apache.nutch.parse.html.video.database.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.nutch.parse.html.video.database.model.ContentSupplierTbl;
import org.apache.nutch.parse.html.video.database.model.ContentSupplierTblExample;

public interface ContentSupplierTblMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_supplier_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int countByExample(ContentSupplierTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_supplier_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int deleteByExample(ContentSupplierTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_supplier_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int deleteByPrimaryKey(Short csId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_supplier_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int insert(ContentSupplierTbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_supplier_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int insertSelective(ContentSupplierTbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_supplier_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    List<ContentSupplierTbl> selectByExample(ContentSupplierTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_supplier_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    ContentSupplierTbl selectByPrimaryKey(Short csId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_supplier_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int updateByExampleSelective(@Param("record") ContentSupplierTbl record, @Param("example") ContentSupplierTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_supplier_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int updateByExample(@Param("record") ContentSupplierTbl record, @Param("example") ContentSupplierTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_supplier_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int updateByPrimaryKeySelective(ContentSupplierTbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_supplier_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int updateByPrimaryKey(ContentSupplierTbl record);
}