package org.apache.nutch.parse.html.video.database.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.nutch.parse.html.video.database.model.VideoCrawlinfoTbl;
import org.apache.nutch.parse.html.video.database.model.VideoCrawlinfoTblExample;

public interface VideoCrawlinfoTblMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_crawlinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int countByExample(VideoCrawlinfoTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_crawlinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int deleteByExample(VideoCrawlinfoTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_crawlinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_crawlinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int insert(VideoCrawlinfoTbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_crawlinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int insertSelective(VideoCrawlinfoTbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_crawlinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    List<VideoCrawlinfoTbl> selectByExample(VideoCrawlinfoTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_crawlinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    VideoCrawlinfoTbl selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_crawlinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int updateByExampleSelective(@Param("record") VideoCrawlinfoTbl record, @Param("example") VideoCrawlinfoTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_crawlinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int updateByExample(@Param("record") VideoCrawlinfoTbl record, @Param("example") VideoCrawlinfoTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_crawlinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int updateByPrimaryKeySelective(VideoCrawlinfoTbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_crawlinfo_tbl
     *
     * @mbggenerated Wed Jan 23 17:42:39 CST 2013
     */
    int updateByPrimaryKey(VideoCrawlinfoTbl record);
}